### ISSUE TITLE
vigra fails to build on 10.10.3

### ISSUE THREAD

**Issue by bfontaine** [Homebrew/homebrew-science#2540] opened 2015-07-22 13:33 UTC
```
==> Installing homebrew/science/enblend-enfuse dependency: vigra
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://github.com/ukoethe/vigra/releases/download/Version-1-10-0/vigra-1.10.0-src-with-docu.tar.gz
==> Downloading from https://s3.amazonaws.com/github-cloud/releases/2005439/3439098a-55f1-11e3-980c-4b1be6eddc34.gz?response-content-disposition=attachment%3B%20filename%3Dvigra-1.10.0-src-with-docu.tar.
######################################################################## 100,0%
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/vigra/1.10.0_1 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON
==> make
==> make check

/usr/local/Cellar/cmake/3.2.3/bin/cmake -E cmake_progress_report /tmp/vigra20150722-47265-93svcm/vigra-1.10.0/build/CMakeFiles  34
[ 32%] Built target test_gridgraph
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2
```

Logs: https://gist.github.com/d37c7b5c06cc72711cd7

**Comment by dpo** [comment] 2015-07-25 22:32
Duplicate of #2428.

**Closed by dpo** 2015-07-25 22:32 UTC
