### ISSUE TITLE
doesn't upgrade octave to 4.0.3_4, mac 10.12

### ISSUE THREAD

**Issue by mmngreco** [Homebrew/homebrew-science#4347] opened 2016-09-24 19:36 UTC
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
```
mmngreco:~ mmngreco$ brew install octave
==> Installing octave from homebrew/science
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://ftpmirror.gnu.org/octave/octave-4.0.3.tar.gz
Already downloaded: /Users/mmngreco/Library/Caches/Homebrew/octave-4.0.3.tar.gz
==> Downloading http://hg.savannah.gnu.org/hgweb/octave/raw-rev/e870a68742a6
Already downloaded: /Users/mmngreco/Library/Caches/Homebrew/octave--patch-0ddcd8dd032be79d5a846ad2bc190569794e4e1a33ce99f25147d70ae6974682
==> Downloading http://savannah.gnu.org/bugs/download.php?file_id=37717
Already downloaded: /Users/mmngreco/Library/Caches/Homebrew/octave--patch-feeaad0d00be3008caef2162b549c42fd937f3fb02a36d01cde790a589d4eb2d.php
==> Patching
==> Applying e870a68742a6
patching file libgui/src/octave-dock-widget.cc
==> Applying download.php
patching file libinterp/Makefile.in
==> ./configure --prefix=/usr/local/Cellar/octave/4.0.3_4 --enable-dependency-tracking --enable-link-all-dependencies --enable-shared
==> make all
Last 15 lines from /Users/mmngreco/Library/Logs/Homebrew/octave/02.make:
_GL_CXXALIAS_SYS (mkostemp, int, (char * /*template*/, int /*flags*/));
~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../libgnu/stdio.h:271:45: note: expanded from macro '_GL_CXXALIAS_SYS'
      static rettype (*func) parameters = ::func;  \
                                          ~~^
1 error generated.
make[3]: *** [array/array_libarray_la-Array-b.lo] Error 1
make[3]: *** Waiting for unfinished jobs....
1 error generated.
make[3]: *** [array/array_libarray_la-Array-ch.lo] Error 1
1 error generated.
make[3]: *** [array/array_libarray_la-Array-C.lo] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
#### Brief summary of issue:

I'm trying to upgrade octave because have a unusual behavior. When I try to go to editor, crash and exit of gui, that's is why I try to upgrade or reinstall it.

#### The complete command that you issued:

`brew upgrade octave`
`brew reinstall octave`

#### Gist with output of `brew doctor`:

https://gist.github.com/ac7bb882c6116700673e7d435245cc72

#### Link output by `brew gist-logs <formula>`:

https://gist.github.com/anonymous/cb74a046605308994f85d27ac51c287c

#### Output of `brew config`:

```
HOMEBREW_VERSION: 1.0.3-dirty
ORIGIN: https://github.com/Homebrew/brew
HEAD: 8724e11a6b5805dffee7133526bf5457c0a5d02a
Last commit: 26 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: fdcbb7d3e6f0a749d6a823c17ec656c9177f127a
Core tap last commit: 37 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/mmngreco/anaconda3/bin/python => /Users/mmngreco/anaconda3/bin/python3.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_92
macOS: 10.12-x86_64
Xcode: 8.0
CLT: N/A
X11: 2.7.9 => /opt/X11
```

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by agolovenko** [comment] 2016-09-26 11:49
same issue

**Comment by sjaumann** [comment] 2016-09-26 16:32
same issue

**Comment by varnerlab** [comment] 2016-09-27 02:20
same issue

**Comment by dpo** [comment] 2016-09-27 12:40
Duplicate of #4305. Please see instructions there. I'll try to push an upgraded octave formula asap.

**Closed by dpo** 2016-09-27 12:40 UTC
Labels: 10.12

**Comment by mmngreco** [comment] 2016-09-27 15:02
Thanks,  #4305 works for me. 👍
