### ISSUE TITLE
OpenCV 3 macOS 10.12 Sierra QTKit not found build issue

### ISSUE THREAD

**Issue by kushalj1997** [Homebrew/homebrew-science#4104] opened 2016-08-24 16:43 UTC
### Indicate troubleshooting steps taken
- [YES] Ran `brew update` and retried your prior step?
- [YES] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [YES] Checked that a similar issue hasn't already been filed?
- [YES] Looked up the software bug tracker if reporting a build error?
- [YES ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:
- Brief summary of issue:
### Running following command:

`brew install opencv3 --with-ffmpeg --with-tbb --with-contrib`
## Terminal Output

[deleted]
# When trying to build opencv 3 on mac os sierra.

`brew install opencv3 --with-ffmpeg --with-tbb --with-contrib`

`brew gist-logs opencv3`
https://gist.github.com/8801f33b26a3acd5447cdff16a156ff8

**Comment by tdsmith** [comment] 2016-08-30 04:52
upstream observed this is a duplicate of https://github.com/opencv/opencv/issues/6913; pending fix is https://github.com/opencv/opencv/pull/7159

**Comment by normanrz** [comment] 2016-09-24 12:41
https://github.com/opencv/opencv/pull/7159 has been merged. `brew install opencv3 --HEAD --with-contrib` just worked for me

**Comment by singamsetty** [comment] 2016-09-30 00:39
Thanks for the tip. Following worked for me on Sierra
`brew reinstall opencv3 --HEAD --with-python3 --with-ffmpeg --with-tbb --with-contrib`

**Comment by severinsimmler** [comment] 2016-09-30 15:58
This also worked for me, @singamsetty. Thank you!

**Comment by EMacco** [comment] 2016-09-30 16:45
I have been trying to install opencv on Sierra
Error: You must `brew link cmake pkg-config openexr` before homebrew/science/opencv3 can be installed
Please does anyone have a solution?

**Comment by yorelog** [comment] 2016-10-11 13:35
I solved the problem just append a flag `--HEAD` which will install the master branch of [opencv](https://github.com/opencv/opencv).

[pull requests #7266 of opencv ](https://github.com/opencv/opencv/pull/7266) had added the support of OSX AVFoundation , which is a replace framework of QTKit

**Comment by santhosh-kumar** [comment] 2016-10-24 19:19
Is there a patch for OpenCv release version 3.0? Or I will have to start using the develop? 

Thanks.

**Comment by jooni41** [comment] 2016-10-25 14:53
It gets installed but not working properly when I import opencv  it shows the following error:
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: lib/libopencv_reg.3.0.dylib
  Referenced from: /usr/local/lib/python2.7/site-packages/cv2.so
  Reason: image not found

**Comment by singamsetty** [comment] 2016-10-25 15:04
Hi, could you please check if the opencv libraries are loading properly in the python repl ? 
```python
>>> import cv2
>>> cv2.__version__
'3.1.0-dev'
```
If not, you might have to check if the shared object cv2.so was created and properly linked under the site-packages

**Comment by Walid-Ahmed** [comment] 2016-10-25 16:08
I installed without errors using
brew install opencv3 --HEAD

still I can not import CV2 and get the error "ImportError: No module named cv2"

**Comment by Walid-Ahmed** [comment] 2016-10-25 17:08
Solved by running:-
brew install opencv3 --HEAD
 echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth

**Comment by jooni41** [comment] 2016-10-25 17:37
its unable to import cv2  how can I be able to check the version

**Comment by EMacco** [comment] 2016-10-25 18:12
I don't think so bro. I had to restore my El Capitan backup and then
installed opencv

**Comment by Walid-Ahmed** [comment] 2016-10-25 18:55
did you try brew install opencv3 --HEAD

**Comment by jooni41** [comment] 2016-10-25 19:00
Yupps I tried everything

**Comment by Walid-Ahmed** [comment] 2016-10-25 19:01
and 
echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth ?

**Comment by jooni41** [comment] 2016-10-25 19:08
nothing is working I tried everything 3 or 4 times

**Comment by singamsetty** [comment] 2016-10-26 01:53
The shared object should be created somewhere under ```python  /usr/local/Cellar/opencv3/HEAD-XXXX/lib/python2.7/site-packages/cv2.cpython-35m-darwin.so``` which you can symbolically link from your python site-packages as cv2.so.

**Comment by jooni41** [comment] 2016-10-26 08:51
@singamsetty can you please guide me how? it will be really appreciable

**Comment by singamsetty** [comment] 2016-10-27 02:40
Hi,

On my mac, I am using python3.x and here are the settings. Since you are using python 2.7, you might have to adjust the locations accordingly.
```bash
$ echo $PYTHONPATH
/usr/local/lib/python3.5/site-packages
```
I used the below command to install opencv3
```bash
brew install opencv --with-eigen --with-jasper --with-libtiff --with-qt --with-tbb --with-ffmpeg --with-opencl
```
This created a shared object under the below location
```bash
cd /usr/local/Cellar/opencv3/HEAD-6328076_4/lib/python3.5/site-packages/
$ ll|grep cv
-r--r--r--  1 sampathsingamsetty  staff   2.5M Sep 29 19:19 cv2.cpython-35m-darwin.so
```
I created a soft link to this object from my python site-packages dir as follows.
```bash
$ cd /usr/local/lib/python3.5/site-packages

$ ln -s /usr/local/Cellar/opencv3/HEAD-6328076_4/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so cv2.so

$ ll|grep cv
lrwxr-xr-x    1 sampathsingamsetty  staff    94B Sep 29 19:28 cv2.so -> /usr/local/Cellar/opencv3/HEAD-6328076_4/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so
```

Once done, I was able to use the python bindings normally.

**Closed** 2016-12-31 21:56 UTC
Labels: 10.12, upstream
