### ISSUE TITLE
MergePairedFastbs is slow

### ISSUE THREAD

**Issue by ptranvan** [Homebrew/homebrew-science#4380] opened 2016-09-29 16:20 UTC
Hi,

I got some problem with the prepare step, especially the MergePairedFastbs function...

In particular, it writes 10MB in 1 hour.
Is it normal ? if no, how to solve that.

**Comment by dpo** [comment] 2016-09-29 16:29
Hi. Could you explain what makes you think that the problem is due to Homebrew/Science? Did you ask the question upstream?

**Comment by iMichka** [comment] 2017-01-20 19:47
Hi. I will close this issue to try to keep the issue tracker clean.

We do believe that this is not a Homebrew issue. Please reopen a new bug if you believe we are wrong with that assumption.

**Closed by iMichka** 2017-01-20 19:47 UTC
