### ISSUE TITLE
hmmer2: libgcc_s.so.1 must be installed for pthread_cancel to work

### ISSUE THREAD

**Issue by andrewyatz** [Homebrew/homebrew-science#5152] opened 2017-02-16 15:55 UTC
I've just encountered this issue on my local machine. It seems very similar to issue #2546 and was resolved by rebuilding hmmer from source and not using the bottle. My brew is in a non-standard location; not sure if that matters or not. hmmer2 might need rebuilding against the later version of gcc.

**Comment by jonchang** [comment] 2017-03-03 20:41
This is pretty strange, can you write a short test case that demonstrates this? I'm not familiar with the hmmer software.

**Comment by tseemann** [comment] 2017-03-14 04:51
I get this same error all the time on Linuxbrew for certain packages when using bottles.  It seems to be particular to non-standard brew locations (ie. not `/home/linuxbrew/.linuxbrew`, but when even I use that location, it occurs on Centos or RHEL, but not Ubuntu.

Solution is to build the package from source:  `brew reinstall -s hmmer`

**Comment by andrewyatz** [comment] 2017-03-14 09:18
Isn't there a way to indicate if a formula cannot be unpacked from keg if
using a non-standard brew location?

**Comment by sjackman** [comment] 2017-05-08 17:49
Hi, Andrew. The issue is that `glibc`'s `pthread_cancel` is not able to find the shared library `libgcc_s.so.1` which is provided by `gcc`. Here's a work around to put `libgcc_s.so.1` somewhere that `glibc` can find it.
```sh
ln -s $(brew --prefix gcc)/lib/libgcc_s.so.1 $(brew --prefix glibc)/lib/
```

**Comment by sjackman** [comment] 2017-05-08 18:02
This error will be resolved by `https://github.com/Linuxbrew/homebrew-core/pull/2622` once it's merged.

**Comment by sjackman** [comment] 2017-05-08 20:50
This issue is resolved by https://github.com/Linuxbrew/homebrew-core/pull/2622
BWA is also affected by this issue. Run…
```sh
brew update
brew postinstall gcc
brew test bwa hmmer2
```

**Closed by sjackman** 2017-05-08 20:50 UTC
Labels: Linux
