### ISSUE TITLE
octave: help command broken

### ISSUE THREAD

**Issue by ptzz** [Homebrew/homebrew-science#4077] opened 2016-08-20 18:08 UTC
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?

### Bug reports / build errors:
`help` command does not work, e.g. `help fft` produces:

```
error: unable to open /usr/local/Cellar/octave/4.0.3_1/share/octave/4.0.3/etc/macros.texi for reading
error: called from
    __makeinfo__ at line 103 column 5
    help at line 102 column 22
```
Indeed the file `/usr/local/Cellar/octave/4.0.3_1/share/octave/4.0.3/etc/macros.texi` does not exist.

```
~$ octave --version
GNU Octave, version 4.0.3
Copyright (C) 2016 John W. Eaton and others.
This is free software; see the source code for copying conditions.
There is ABSOLUTELY NO WARRANTY; not even for MERCHANTABILITY or
FITNESS FOR A PARTICULAR PURPOSE.

Octave was configured for "x86_64-apple-darwin15.6.0".
```

**Comment by dpo** [comment] 2016-08-22 20:37
@schoeps I can reproduce this on 10.9. Something has gone missing. Do we need to build `--with-docs` to have inline help?

**Comment by schoeps** [comment] 2016-08-22 21:28
Yeah. Sorry. It will be alright in octave 4.2 and I was focussing on the new release and so I messed 4.0.3 up :( I was happy to get rid of `--with-docs` because we have seen that octave fails to build sometimes because of creating the documentation. So, shall we make `--with-docs` default again until 4.2?

**Comment by dpo** [comment] 2016-08-22 21:34
Does `--with-docs` mean the PDF documentation or also the help system? If anything, I think the help system should be available.

**Comment by schoeps** [comment] 2016-08-23 06:51
@ptzz @vicnorton I have made a pull request. For now, you can either build the development sources which also give you the GUI `brew install octave --HEAD --with-gui` or try `brew install octave --with-docs`. Sorry for the inconvenience, we had to release 4.0.3_1 rather quickly since Qt4 is being removed from homebrew.

**Comment by vicnorton** [comment] 2016-08-23 10:27
> On Aug 23, 2016, at 2:51 AM, schoeps <notifications@github.com> wrote:
> 
> @ptzz @vicnorton I have made a pull request. For now, you can either build the development sources which also give you the GUI brew install octave --HEAD --with-gui or try brew install octave --with-docs. Sorry for the inconvenience, we had to release 4.0.3_1 rather quickly since Qt4 is being removed from homebrew.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

No problem, Sebastian. I have switched back to Octave 4.0.3.

Regarding my original note, I am appending a list of some of the stuff that was removed from Octave 4.0.3 to make Octave 4.0.3_1.

Regards,

Vic

tip-off after installing octave 4.0.3_1:
==> Summary
🍺  /usr/local/Cellar/octave/4.0.3_1: 2,166 files, 42.2M
~$ octave
warning: docstring file '/usr/local/Cellar/octave/4.0.3_1/share/octave/4.0.3/etc/built-in-docstrings' not found

The reason for the warning is that all kinds of stuff is missing from
octave 4.0.3_1 (besides "built-in-docstrings"):

example 1:
/usr/local/Cellar/octave/4.0.3/share:
drwxr-xr-x   3 vicnorton  admin  102 Jul 11 16:30 appdata/
drwxr-xr-x   3 vicnorton  admin  102 Jul 11 16:30 icons/
drwxr-xr-x  13 vicnorton  admin  442 Jul 11 16:30 info/
drwxr-xr-x   3 vicnorton  admin  102 Jul 11 16:30 man/
drwxr-xr-x   5 vicnorton  admin  170 Aug 20 20:46 octave/

/usr/local/Cellar/octave/4.0.3_1/share:
drwxr-xr-x  3 vicnorton  admin  102 Jul  1 14:58 appdata/
drwxr-xr-x  3 vicnorton  admin  102 Jul  1 14:58 icons/
drwxr-xr-x  4 vicnorton  admin  136 Jul  1 14:58 octave/
Where is info/ ?
Where is man/ ?

example 2:
/usr/local/Cellar/octave/4.0.3/share/octave/4.0.3
drwxr-xr-x   3 vicnorton  admin   102 Jul 11 16:30 data/
drwxr-xr-x   9 vicnorton  admin   306 Jul 11 16:30 etc/
drwxr-xr-x   6 vicnorton  admin   204 Jul 11 16:30 imagelib/
drwxr-xr-x  15 vicnorton  admin   510 Jul 11 16:30 locale/
drwxr-xr-x  31 vicnorton  admin  1054 Jul 11 16:30 m/

/usr/local/Cellar/octave/4.0.3_1/share/octave/4.0.3:
drwxr-xr-x   3 vicnorton  admin   102 Jul  1 14:58 data/
drwxr-xr-x   5 vicnorton  admin   170 Jul  1 14:58 etc/
drwxr-xr-x   6 vicnorton  admin   204 Jul  1 14:58 imagelib/
drwxr-xr-x  31 vicnorton  admin  1054 Jul  1 14:58 m/
Where is locale/ ?

example 3:
/usr/local/Cellar/octave/4.0.3/share/octave/4.0.3/etc:
-rw-r--r--  1 vicnorton  admin      763 Jul 11 16:30 CITATION
-rw-r--r--  1 vicnorton  admin    13332 Jul 11 16:30 NEWS
-rw-r--r--  1 vicnorton  admin   580558 Jul 11 16:30 built-in-docstrings
-rw-r--r--  1 vicnorton  admin    24473 Jul 11 16:30 default-qt-settings
-rw-r--r--  1 vicnorton  admin  1742358 Jul 11 16:30 doc-cache
-rw-r--r--  1 vicnorton  admin     2945 Jul 11 16:30 macros.texi
drwxr-xr-x  5 vicnorton  admin      170 Jul 11 16:30 tests/

/usr/local/Cellar/octave/4.0.3_1/share/octave/4.0.3/etc:
-rw-r--r--  1 vicnorton  admin    763 Jul  1 14:58 CITATION
-rw-r--r--  1 vicnorton  admin  13332 Jul  1 14:58 NEWS
drwxr-xr-x  5 vicnorton  admin    170 Jul  1 14:58 tests/
Where are the files: built-in-docstrings, default-qt-settings, doc-cache,
macros.texi?

**Comment by dpo** [comment] 2016-08-23 15:34
Fixed now. Please `brew update`.

**Closed by dpo** 2016-08-23 15:34 UTC

**Comment by vicnorton** [comment] 2016-08-23 18:08
> On Aug 23, 2016, at 11:34 AM, Dominique <notifications@github.com> wrote:
> 
> Fixed now. Please brew update.

Unfortunately I can’t graph anything now, but I don’t know what the problem is.

**Comment by schoeps** [comment] 2016-08-23 18:24
@vicnorton are using the gui (requires `--HEAD`) or cli?

**Comment by dpo** [comment] 2016-08-23 18:26
It works for me. Don't forget to set `GNUTERM` if you use the CLI. I use AquaTerm and I noticed I have to fire up AquaTerm before starting Octave.

**Comment by vicnorton** [comment] 2016-08-23 19:09
> On Aug 23, 2016, at 2:26 PM, Dominique <notifications@github.com> wrote:
> 
> It works for me. Don't forget to set GNUTERM if you use the CLI. I use AquaTerm and I noticed I have to fire up AquaTerm before starting Octave.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.

I have been using
  octave-cli
with
  graphics_toolkit gnuplot
  setenv GNUTERM qt
but apparently "GNUTERM qt” is no longer recognized.

Now when I try my macplotbug.m script I see many lines of
  warning: could not match any font: *-normal-normal-10
  warning: ft_render: unable to load appropriate font
followed by
  Unknown or ambiguous terminal name ‘qt'
The image does come up in Aquaterm, which is definitely not what I want.
When I
  setenv GNUTERM aqua
the
  Unknown or ambiguous terminal name ‘qt’
goes away, but all the
  warning: could not match any font: *-normal-normal-10
  warning: ft_render: unable to load appropriate font
lines continue.

It is very frustrating. I quit for today.

**Comment by ptzz** [comment] 2016-08-23 19:53
I also have issues and is using GNUTERM qt. Don't see the errors @vicnorton gets, but it takes really long (~20s) to do plot(x) when x contains 10 values -- and it's getting plotted with x11.

**Comment by dpo** [comment] 2016-08-23 19:59
You would probably receive more meaningful support if you took those comments to the octave tracker.

**Comment by schoeps** [comment] 2016-08-23 20:01
Did you guys update gnuplot recently? If yes, it should have complained about renamed switches (`--with-qt` has been depracted). The new switch is `--with-qt5` since homebrew has dropped qt4 support.

**Comment by ptzz** [comment] 2016-08-23 20:35
Just reinstalled gnuplot with `--with-qt5` but the problem with octave is still the same.

**Comment by vicnorton** [comment] 2016-08-23 20:58
> On Aug 23, 2016, at 4:36 PM, ptzz <notifications@github.com> wrote:
> 
> Just reinstalled gnuplot with --with-qt5 but the problem with octave is still the same.

I also reinstalled gnuplot with --with-qt5:

/usr/local/Cellar/gnuplot/5.0.4 (44 files, 2.3M) *
  Built from source on 2016-08-23 at 16:09:05 with: --with-qt5
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/gnuplot.rb
==> Dependencies
Build: pkg-config ✔
Required: fontconfig ✔, gd ✔, jpeg ✔, libpng ✔, libtiff ✔, readline ✔, webp ✔
Recommended: lua ✔
Optional: pdflib-lite ✘, qt5 ✔, wxmac ✘

But there is no qt terminal in this gnuplot:

Available terminal types:
           canvas  HTML Canvas object
              cgm  Computer Graphics Metafile
          context  ConTeXt with MetaFun (for PDF documents)
            corel  EPS format for CorelDRAW
             dumb  ascii art for anything that prints text
              dxf  dxf-file for AutoCad (default size 120x80)
            eepic  EEPIC -- extended LaTeX picture environment
              emf  Enhanced Metafile format
            emtex  LaTeX picture environment with emTeX specials
         epslatex  LaTeX picture environment using graphicx package
              fig  FIG graphics language for XFIG graphics editor
              gif  GIF images using libgd and TrueType fonts
             hpgl  HP7475 and relatives [number of pens] [eject]
             jpeg  JPEG images using libgd and TrueType fonts
            latex  LaTeX picture environment
              lua  Lua generic terminal driver
               mf  Metafont plotting standard
               mp  MetaPost plotting standard
             pcl5  HP Designjet 750C, HP Laserjet III/IV, etc. (many options)
              png  PNG images using libgd and TrueType fonts
       postscript  PostScript graphics, including EPSF embedded files (*.eps)
         pslatex  LaTeX picture environment with PostScript \specials
            pstex  plain TeX with PostScript \specials
         pstricks  LaTeX picture environment with PSTricks macros
              qms  QMS/QUIC Laser printer (also Talaris 1200 and others)
              svg  W3C Scalable Vector Graphics
          tek40xx  Tektronix 4010 and others; most TEK emulators
          tek410x  Tektronix 4106, 4107, 4109 and 420X terminals
          texdraw  LaTeX texdraw environment
             tgif  TGIF X11 [mode] [x,y] [dashed] ["font" [fontsize]]
             tikz  TeX TikZ graphics macros via the lua script driver
         tkcanvas  Tk canvas widget
             tpic  TPIC -- LaTeX picture environment with tpic \specials
          unknown  Unknown terminal type - not a plotting device
            vttek  VT-like tek40xx terminal emulator
            xterm  Xterm Tektronix 4014 Mode

**Comment by schoeps** [comment] 2016-08-23 22:10
please try 

`brew install https://raw.githubusercontent.com/schoeps/homebrew-core/438a015b876d99ac06f17c019a9faa9c9969c473/Formula/gnuplot.rb --with-qt5`

**Comment by vicnorton** [comment] 2016-08-24 11:52
> On Aug 23, 2016, at 6:10 PM, schoeps <notifications@github.com> wrote:
> 
> please try
> 
> brew install https://raw.githubusercontent.com/schoeps/homebrew-core/438a015b876d99ac06f17c019a9faa9c9969c473/Formula/gnuplot.rb --with-qt5
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

That solved the gnuplot qt problem, Sebastian. But I still have a font problem with octave 4.0.3. My test script sergA.m:

     % sergA.m
     %   An example for <http://savannah.gnu.org/bugs/?48689>
     %   based on the example of
     %     Dmitri A. Sergatskov <mailto:dasergatskov@gmail.com>
     
     clear all;
     
     %% Patches with same number of vertices
     t1 = (1/16:1/8:1)' * 2*pi;
     t2 = ((1/16:1/8:1)' + 1/32) * 2*pi;
     x1 = sin (t1) - 0.8;
     y1 = cos (t1);
     x2 = sin (t2) + 0.8;
     y2 = cos (t2);
     close all;
     hold on;
     patch ([x1,x2], [y1,y2], 'r');
     plot(0, 0, "o", "markersize", 8, ...
       "markeredgecolor", "black", "markerfacecolor", "yellow");
     axis([-0.9,0.9,-0.9,0.9], "equal")
     text(-0.35, 0.2, "hello", "fontsize", 24, ...
       "fontweight", "bold", "rotation", 45);
     text(0.15, -0.35, "world", "fontsize", 24, ...
       "fontweight", "bold", "rotation", 45);
     hold off;

now produces the correct image with
  graphics_toolkit gnuplot;
  setenv GNUTERM qt;

but it also produces lots of error messages:
     octave> sergA
     Fontconfig error: line 152: mismatched tag
     Fontconfig error: Cannot load default config file
     warning: could not match any font: *-normal-normal-10
     warning: called from
         axes at line 66 column 10
         gca at line 58 column 9
         hold at line 64 column 9
         sergA at line 17 column 1
     warning: ft_render: unable to load appropriate font
     warning: could not match any font: *-normal-normal-10
       and many, many more such pairs of warnings with
     warning: ft_render: invalid bounding box, cannot render
       thrown in now and then for good luck.
 
And when I quit octave
     octave> quit
I see
     panic: Segmentation fault: 11 -- stopping myself...
     attempting to save variables to 'octave-workspace'...
     save to 'octave-workspace' complete
     Segmentation fault: 11

The, when I try to run the same script again with octave, I get the same errors but no image. Octave simply quits itself with the last lines
     warning: ft_render: unable to load appropriate font
     warning: could not match any font: *-normal-normal-10
     warning: ft_render: unable to load appropriate font
     panic: Segmentation fault: 11 -- stopping myself...
     attempting to save variables to 'octave-workspace'...
     save to 'octave-workspace' complete
     Segmentation fault: 11


Regards,

Vic

This is what the image is supposed to look like.

**Comment by schoeps** [comment] 2016-08-24 13:24
@vicnorton Sorry, it seems to be neither an Octave nor a Gnuplot problem. Maybe it's related to fontconfig. In this case you may want to reset you font caches, e.g., delete `~/.cache/fontconfig/` (check the documentation of fontconfig"). However, I consider this issue #4077 as solved. Please open a new one if necessary.

**Comment by vicnorton** [comment] 2016-08-25 10:49
> On Aug 24, 2016, at 9:24 AM, schoeps <notifications@github.com> wrote:
> 
> @vicnorton Sorry, it seems to be neither an Octave nor a Gnuplot problem. Maybe it's related to fontconfig. In this case you may want to reset you font caches, e.g., delete ~/.cache/fontconfig/ (check the documentation of fontconfig"). However, I consider this issue #4077 as solved. Please open a new one if necessary.

My fontconfig problem has been solved by following the suggestions on
   http://stackoverflow.com/questions/35249881/octave-fontconfig-error
Now the gnuplot_qt terminal terminal works perfectly, though it takes
quite a while to come up the first time. It would be nice if the
gnuplot formula could be fixed at homebrew so that the instruction
   brew install gnuplot --with-qt5
actually installed gnuplot with the Qt terminal.

Another curiosity: I can no longer get octave-gui from of my 4.0.3.
This is perfectly fine with me, but is something wrong with my system?

**Comment by ptzz** [comment] 2016-08-30 19:33
I finally got QT plots working by putting `graphics_toolkit("gnuplot")` in my .octaverc. I used to have only `setenv GNUTERM qt` there. Perhaps the default value for graphics_toolkit changed from gnuplot to fltk with the update.
