### ISSUE TITLE
octave --without-java not working

### ISSUE THREAD

**Issue by spundun** [Homebrew/homebrew-science#1899] opened 2015-03-03 15:51 UTC
When I install octave with the options `brew install octave --without-java` it still seems to look for Java 6 which I don't have on my system and just terminates.

**Comment by xu-cheng** [comment] 2015-03-03 15:57
Could you please follow [these instructions](http://git.io/brew-troubleshooting) and provide the requested diagnostics? Thanks!

**Comment by spundun** [comment] 2015-03-03 17:30
https://gist.github.com/anonymous/e7196655d25210089527

Is that all? I had run brew update, brew upgrade and brew doctor. The only complain it had was related to case sensitive file system

**Comment by spundun** [comment] 2015-03-03 17:32
I've tried many different ways, building from source, passing `--without-java` also tried to checkout the last version of `octave.rb` all result in the same thing.

**Comment by spundun** [comment] 2015-03-03 17:45
A new gist just to be sure I knew the entire context. https://gist.github.com/1dce6623e38c10c8eb5f

Installed `octave` using `brew install octave --build-from-source`. 

```
$ echo $JAVA_HOME 
/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home
$ /usr/libexec/java_home 
/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home
```

**Comment by spundun** [comment] 2015-03-03 17:47
Let me know if you'd like anything else. 

```
$ uname -mrsv
Darwin 14.0.0 Darwin Kernel Version 14.0.0: Fri Sep 19 00:26:44 PDT 2014; root:xnu-2782.1.97~2/RELEASE_X86_64 x86_64
```

**Comment by dpo** [comment] 2015-03-03 20:25
When I `brew install -v octave --without-java`, the `--without-java` is passed to `configure`:
````
==> ./configure --prefix=/usr/local/Cellar/octave/3.8.1_1 --disable-docs --without-opengl --without-java --with-x=no
````
but your gist doesn't reflect that.

**Comment by spundun** [comment] 2015-03-04 03:46
Yes, the log messages are for the run where I didn't pass `without-java` I can upload a gist with that setting also. But this run also has a problem. The problem that even though I'm compiling from scratch and my `JAVA_HOME` is pointed to `1.8`, octave, once compiled, looks for Java 6.

**Comment by spundun** [comment] 2015-03-04 04:01
Here's a new gist https://gist.github.com/d826a4bee6f9a847c11b . This time with command `brew install octave --build-from-source --without-java` . Even during make check I get a dialog box popping up asking me to download Java 6, the install finishes and once I run octave I get error and immediate termination, with the Java 6 pop up.

```
$ octave
No Java runtime present, requesting install.
```

**Comment by dpo** [comment] 2015-03-04 04:17
This sounds like a core issue with the `:java` dependency. Would you open an issue at https://github.com/Homebrew/homebrew/issues and point to this one?

**Comment by xu-cheng** [comment] 2015-03-04 04:39
@dpo I am the one working on JavaDependency on the core. And I'm not convinced that this is a core issue. So let's not disturb core too soon. 

@spundun I am a little confusing about your issue.

> octave, once compiled, looks for Java 6.

Can you be more specific about this?

As for compiling octave without Java, I noticed `configure: WARNING: unrecognized options: --without-java` in your log. This should be a issue of octave.rb. @dpo

**Comment by dpo** [comment] 2015-03-04 05:33
Well that's true. It should be `--disable-java`.

**Comment by spundun** [comment] 2015-03-04 05:57
@xu-cheng  Like I posted in my comment 2 hours ago.

```
$ octave
No Java runtime present, requesting install.
```
When I try to run octave using command line, I get the above error. And the system pops up a dialog box that looks like this https://www.google.com/search?q=to+open+this+java+application+yosemite&espv=2&biw=1088&bih=704&source=lnms&tbm=isch&sa=X&ei=VZ72VMHCF4L0oATT5YKADw&ved=0CAcQ_AUoAg  

From this I'm *inferring* that the octave is still looking for java even when I compile with `--without-java` option.

**Comment by spundun** [comment] 2015-03-04 06:00
@dpo @xu-cheng  If I'm able to disable java because of @dpo 's fix then I might be fine, because I don't need Java at present. That would be great. But this issue will still be open since octave is not working with java.

**Comment by xu-cheng** [comment] 2015-03-04 06:02
> But this issue will still be open since octave is not working with java.

@spundun That's my main concentration. Can you be more specific about this? What happens when you compiling octave **with** Java.

**Comment by spundun** [comment] 2015-03-04 06:05
Exactly what I discribed in https://github.com/Homebrew/homebrew-science/issues/1899#issuecomment-77101558

And also like I said previously... Even during the `make check` phase, I get the same dialog box popping up asking me to download Java 6, the install finishes and once I run octave I get the same error and popup dialog as above.

**Comment by spundun** [comment] 2015-03-04 06:06
It's as if octave is getting compiled such that its looking for java at the Java1.6 path which does not exist on my machine.

**Comment by xu-cheng** [comment] 2015-03-04 06:07
What will happen if you run command `/usr/libexec/java_home`?

**Comment by spundun** [comment] 2015-03-04 06:08
https://github.com/Homebrew/homebrew-science/issues/1899#issuecomment-76995774 shows the output

```
$ echo $JAVA_HOME 
/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home
$ /usr/libexec/java_home 
/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home
```

**Comment by xu-cheng** [comment] 2015-03-04 06:12
That's strange. If `/usr/libexec/java_home` finds the JVM, there shouldn't be a pop out existing. Can you try run commands `java` and `javac` ? Will there be a pop out?

**Comment by spundun** [comment] 2015-03-04 06:13
No pop ups.

```
$ java -version
java version "1.8.0_11"
Java(TM) SE Runtime Environment (build 1.8.0_11-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.11-b03, mixed mode)
$ javac -version
javac 1.8.0_11
```

**Comment by xu-cheng** [comment] 2015-03-04 06:20
That's strange. Where's the output of following commands?
```
which java
which javac
ls -a -l $(/usr/libexec/java_home)/bin
```

**Comment by spundun** [comment] 2015-03-04 06:30
```
$ which java
/usr/bin/java
$ which javac
/usr/bin/javac
$ ls -a -l $(/usr/libexec/java_home)/bin
total 8064
drwxrwxr-x  2 root  wheel    1530 Jun 16  2014 .
drwxrwxr-x  8 root  wheel     544 Jun 16  2014 ..
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 appletviewer
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 extcheck
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 idlj
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jar
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jarsigner
-rwxrwxr-x  1 root  wheel   99296 Jun 16  2014 java
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 javac
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 javadoc
-rwxrwxr-x  1 root  wheel    2062 Jun 16  2014 javafxpackager
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 javah
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 javap
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jcmd
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jconsole
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jdb
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jdeps
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jhat
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jinfo
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jjs
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jmap
-rwxrwxr-x  1 root  wheel     405 Jun 16  2014 jmc
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jps
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jrunscript
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jsadebugd
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jstack
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jstat
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 jstatd
-rwxrwxr-x  1 root  wheel    5183 Sep 11  2013 jvisualvm
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 keytool
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 native2ascii
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 orbd
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 pack200
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 policytool
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 rmic
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 rmid
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 rmiregistry
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 schemagen
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 serialver
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 servertool
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 tnameserv
-rwxrwxr-x  1 root  wheel  116448 Jun 16  2014 unpack200
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 wsgen
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 wsimport
-rwxrwxr-x  1 root  wheel   99360 Jun 16  2014 xjc
$ 
```

**Comment by spundun** [comment] 2015-03-04 06:34
Also, `javac` and `java` seem to work fine.

```
$ cat HelloWorld.java 
public class HelloWorld { 
   public static void main(String[] args) { 
      System.out.println("Hello, World");
   }
}
$ javac HelloWorld.java 
$ java HelloWorld
Hello, World
$ 
```

**Comment by xu-cheng** [comment] 2015-03-04 06:46
So everything works as it should be. I have not idea where the pop out comes from.

**Comment by xu-cheng** [comment] 2015-03-04 07:07
@spundun I wonder will running these commands result to pop out:
```
/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/bin/javac
/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/bin/java
/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/jre/bin/java
```

Also, other than the pop outs, do you have any other troubles? Does octave work if you just ignore these pop out?

**Comment by spundun** [comment] 2015-03-04 07:18
No popups ...

Octave terminates immediately. So no, it doesn't work. In fact it terminates as soon as I even see the pop up, before I have a chance to click OK

**Comment by dpo** [comment] 2015-03-04 16:03
@spundun Does the updated `octave` formula work for you?

**Comment by dpo** [comment] 2015-03-05 16:27
@spundun Are there issues remaining?

**Comment by spundun** [comment] 2015-03-05 17:54
@dpo I will be able to check in a few hours, I will be sure to let you know. My guess (based on what I saw in your patch) is that it might work with the `--without-java` option but a regular install with java might still break.

**Comment by spundun** [comment] 2015-03-05 23:20
@dpo As you can see below, octave simple install is still looking for Java SE 6 even though I have Apple's Java 8 installed. (I'm pasting the whole output, but you probably want to ignore all those messages about GUI

```
$ brew install octave
==> Installing octave from homebrew/homebrew-science
==> Downloading https://homebrew.bintray.com/bottles-science/octave-3.8.1_1.yose
######################################################################## 100.0%
==> Pouring octave-3.8.1_1.yosemite.bottle.4.tar.gz
==> Caveats

gnuplot's Qt terminal is supported by default with the Octave GUI.
Use other gnuplot graphics terminals by setting the environment variable
GNUTERM in ~/.octaverc, and building gnuplot with the matching options.

  setenv('GNUTERM','qt')    # Default graphics terminal with Octave GUI
  setenv('GNUTERM','x11')   # Requires XQuartz; install gnuplot --with-x
  setenv('GNUTERM','wxt')   # wxWidgets/pango; install gnuplot --wx
  setenv('GNUTERM','aqua')  # Requires AquaTerm; install gnuplot --with-aquaterm

  You may also set this variable from within Octave.


The Octave GUI is experimental and not enabled by default. To use it,
use the command-line argument "--force-gui"; e.g.,
    octave --force-gui

==> Summary
🍺  /usr/local/Cellar/octave/3.8.1_1: 2089 files, 50M
$ octave
No Java runtime present, requesting install.
$ 
```

**Comment by spundun** [comment] 2015-03-05 23:36
Now when I install octave using the command `brew install octave --build-from-source --without-java`, it works! I have octave that is running.
I do get a warning during the `make install` phase
```
Warning: octave dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
```
Hopefully it's not a big deal.

**Comment by spundun** [comment] 2015-03-05 23:37
This does not mean that there is no problem. The regular octave installation still breaks, and I can't use Java(I don't need it at the moment personally). So this issue should stay open.

**Comment by xu-cheng** [comment] 2015-03-06 01:00
Have you try `brew install octave --build-from-source`?

**Comment by dpo** [comment] 2015-03-06 01:34
@xu-cheng Could the cause be that the bottle was built against Java 6?

**Comment by xu-cheng** [comment] 2015-03-06 01:46
It's possible but unlikely. The bottle was built on the bot with Java 8 installed. And `depends_on :java` will set JAVA_HOME to it. So the bottle should be built against Java 8.

**Comment by spundun** [comment] 2015-03-06 04:24
@xu-cheng As expected `brew install octave --build-from-source` still shows the same problem.

**Comment by xu-cheng** [comment] 2015-03-07 14:22
I may find the cause. Notice:
```
Java CPPFLAGS:  
-I/Library/Java/JavaVirtualMachines/jdk1.8.0_11.jdk/Contents/Home/include
-I/System/Library/Frameworks/JavaVM.framework/Home/include
-I/System/Library/Frameworks/JavaVM.framework/Versions/CurrentJDK/Headers
-I/System/Library/Frameworks/JavaVM.framework/Versions/Current/Headers
```

The last three are the system Java header paths. At the other header, `depends_on :java` should [add](https://github.com/Homebrew/homebrew/blob/master/Library/Homebrew/requirements/java_dependency.rb#L15-L16) `$JAVA_HOME/include` and `$JAVA_HOME/include/darwin` to `cflags`. But this is not picked up by octave.

@dpo Knowing what's wrong, any idea how to fix this?

**Comment by dpo** [comment] 2015-03-07 17:00
I'll look into it.

@spundun This may be a long shot, but could you try `brew install octave --env=std`? (With and without `--build-from-source.)

**Comment by spundun** [comment] 2015-03-07 18:39
@dpo  Same problem with `--env=std`

**Comment by dpo** [comment] 2015-03-12 18:45
`configure` will let us specify the following:
````
--with-java-homedir=DIR Java JDK directory in DIR
--with-java-includedir=DIR
                        look for java include file <jni.h> in DIR
--with-java-libdir=DIR  look for java library libjvm in DIR
````

**Comment by xu-cheng** [comment] 2015-03-13 09:45
@dpo Is there way to config `cflags`? 

If anyone can show me the way to uninstall Apple Java 1.6, I will try to reproduce this issue on my Mac.

**Comment by lpil** [comment] 2015-04-05 21:52
I am experiencing the same problem. Is there a recommended solution, and is there anything I can do to help with this issue?

Thanks,
Louis

**Comment by spundun** [comment] 2015-04-06 03:02
@lpil Like I said in one of the comments above... `brew install octave --build-from-source --without-java` should work now. It will disable the java bindings but the other features of octave should work. Good luck to @xu-cheng  and @dpo in fixing the issue with java.

**Comment by dpo** [comment] 2015-04-06 14:40
All I know is what I stated above and that the Octave `configure` script says it reads (among others)
````
  CC          C compiler command
  CFLAGS      C compiler flags
  LDFLAGS     linker flags, e.g. -L<lib dir> if you have libraries in a
              nonstandard directory <lib dir>
  CPPFLAGS    (Objective) C/C++ preprocessor flags, e.g. -I<include dir> if
              you have headers in a nonstandard directory <include dir>
  CXXFLAGS    C++ compiler flags
  FFLAGS      Fortran 77 compiler flags
  JAVA_HOME   path to Java JDK installation
````
@xu-cheng Is that what you're asking?

I also noticed that the `INSTALL.OCTAVE` file states, in the requirements list:
````
Java Development Kit
     Java programming language compiler and libraries.  The OpenJDK free
     software implementation is recommended
     (<http://openjdk.java.net/>), although other JDK implementations
     may work.  Java is required to be able to call Java functions from
     within Octave.
````
I don't know enough about Java to understand if using Apple/Oracle Java vs. OpenJDK makes a difference.

**Comment by XBOOS** [comment] 2015-08-15 14:19
Hi, there's still the java binding problem now. Normal installation still pops up the "No Java runtime present, requesting install." Hope it will be fixed soon.

**Comment by dpo** [comment] 2015-08-15 16:24
I'm hoping octave 4.0 might have more clever Java support. @schoeps had a tentative formula a little while back. Perhaps it's time to submit it and test it.

**Comment by schoeps** [comment] 2015-08-15 17:56
I will clean up the formula for Octave 4.0 and make a pull request. Then we can start a public test phase. I recall it took some time until the last formula was working for everybody. I will host the next OctConf in September and if the remaining problems are not solved before I will try to devote some time of our code sprints for octave on mac os.

**Comment by dpo** [comment] 2015-08-17 22:09
See #2660 for an update `octave` formula.

**Comment by dpo** [comment] 2015-09-04 16:31
@spundun Octave was just upgraded to version 4. Could you see if you're still experiencing the same problems?

**Comment by Indy9000** [comment] 2015-09-24 12:52
Octave fails loading saying no Java
Octave was fresh installed using Brew


    MacBook-Pro:~ indy9000$ octave
	No Java runtime present, requesting install.
	MacBook-Pro:~ indy9000$ java -version
	java version "1.8.0_25"
	Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
	Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)

**Comment by schoeps** [comment] 2015-09-24 13:12
Probably you need Java 6 from here https://support.apple.com/kb/DL1572

**Comment by Indy9000** [comment] 2015-09-24 13:16
Ta, Yes that fixed it. But hard dependency on a deprecated Java version is in many ways undesirable.

**Comment by schoeps** [comment] 2015-09-24 13:39
Well, I agree that this is unfortunate. One should probably disable Java by default. Feel free to propose a changeset :)

**Comment by ReaddyEddy** [comment] 2015-10-01 15:25
I'm seeing the same issue when doing both 
brew install octave
and  
brew install --build-from-source 
My current configuration is  
Yosemite 10.10 
java "version" 1.8.0.60
javac version 1.8.0.60

uninstalling Java 8 is not an option as other things depend on it.


When building from source I've also seen references to 
A BLAS library was detected but found incompatible with your Fortran 77 settings though uninstalling gcc and openblas and reinstalling via home-brew seems to have resolved that.

**Comment by schoeps** [comment] 2015-10-01 15:40
Well then, I will submit immediately a changeset to disable Java by default.

> I'm seeing the same issue when doing both 
[...]
> uninstalling Java 8 is not an option as other things depend on it.

Either install *additionally* Java 6 as mentioned above or install octave without java, e.g.

`brew install octave --without-java`

setting like those can be found using `brew info`.

> When building from source I've also seen references to 
> A BLAS library was detected but found incompatible with your Fortran 77 settings though uninstalling gcc and openblas and reinstalling via home-brew seems to have resolved that.

This might have been due to incomplete upgrades. I don't think it's an octave issue.

**Comment by dpo** [comment] 2016-05-20 13:32
I'll close this as octave was updated recently. Please open a new issue if problems persist.

**Closed by dpo** 2016-05-20 13:32 UTC
Labels: Math, upstream
