### ISSUE TITLE
OPEBCV3 install in MAC Error: SHA256 mismatch

### ISSUE THREAD

**Issue by btsantos** [Homebrew/homebrew-science#2527] opened 2015-07-16 20:04 UTC
==> Downloading https://downloads.sourceforge.net/project/opencvlibrary/3rdparty/ippicv/ippicv_macosx_20141027.tgz
==> Downloading from http://downloads.sourceforge.net/#!/project/opencvlibrary/3rdparty/ippicv/ippicv_macosx_20141027.tgz
######################################################################## 100.0%
Error: SHA256 mismatch
Expected: 07e9ae595154f1616c6c3e33af38695e2f1b0c99c925b8bd3618aadf00cd24cb
Actual: 818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821
Archive: /Library/Caches/Homebrew/opencv3--icv-macosx-20141027.tgz
To retry an incomplete download, remove the file above.
MacBts:~ btsantos$ wget https://downloads.sourceforge.net/project/opencvlibrary/3rdparty/ippicv/ippicv_macosx_20140429.tgz
--2015-07-16 20:58:40--  https://downloads.sourceforge.net/project/opencvlibrary/3rdparty/ippicv/ippicv_macosx_20140429.tgz
Resolving downloads.sourceforge.net... 54.230.69.100, 54.230.70.141, 54.192.69.238, ...
Connecting to downloads.sourceforge.net|54.230.69.100|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: http://downloads.sourceforge.net/#!/project/opencvlibrary/3rdparty/ippicv/ippicv_macosx_20140429.tgz [following]
--2015-07-16 20:58:41--  http://downloads.sourceforge.net/
Connecting to downloads.sourceforge.net|54.230.69.100|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 639 [text/html]
Saving to: 'ippicv_macosx_20140429.tgz'

ippicv_macosx_20140429.tgz            100%[========================================================================>]     639  --.-KB/s   in 0s     

2015-07-16 20:58:42 (21.8 MB/s) - 'ippicv_macosx_20140429.tgz' saved [639/639]

MacBts:~ btsantos$ shasum -a 256 ippicv_macosx_20140429.tgz
818a4b8bbcb50878a8b1b9f71b4274d242ab46bf860c74676e98dec1d0248821  ippicv_macosx_20140429.tgz
MacBts:~ btsantos$

**Comment by btsantos** [comment] 2015-07-16 20:12
direct download from http://sourceforge.net/projects/opencvlibrary/files/3rdparty/ippicv/ippicv_macosx_20141027.tgz/download

give de correct shasum

**Comment by tdsmith** [comment] 2015-07-17 01:07
Thanks for reporting. Sourceforge is serving HTML instead of tarballs because it's in disaster recovery mode. Hopefully it comes back soon. Closing as duplicate of https://github.com/Homebrew/homebrew/issues/41778.

**Closed by tdsmith** 2015-07-17 01:07 UTC
