### ISSUE TITLE
openblas fails to build with --with-openmp on MacOS Sierra

### ISSUE THREAD

**Issue by jyaworski** [Homebrew/homebrew-science#4554] opened 2016-11-01 23:01 UTC
### Indicate troubleshooting steps taken

- [X] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:
```shell
2016-11-01 18:54:53 -0400

make
CC=gcc-4.2
FC=/usr/local/bin/gfortran
libs
netlib
shared

<built-in>:0: error: Unknown value ‘10.12’ of -mmacosx-version-min
<built-in>:0: error: Unknown value ‘10.12’ of -mmacosx-version-min
make: *** [getarch] Error 1
Makefile.system:165: Makefile.conf: No such file or directory
Makefile.system:906: Makefile.: No such file or directory
make: *** No rule to make target `Makefile.'.  Stop.

...output of brew config....

HOMEBREW_CC: gcc-4.2
HOMEBREW_CXX: g++-4.2
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j8                                                                                                                                                                    
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/gcc/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/opt/apple-gcc42/bin:/usr/local/bin
```
#### Brief summary of issue:
openblas fails to build with --with-openmp on MacOS Sierra

#### The complete command that you issued:
`brew install openblas --with-openmp`
#### Link output by `brew gist-logs <formula>`:
Running gives me:

```ruby
Error: undefined method `[]' for nil:NilClass
Please report this bug:
  https://git.io/brew-troubleshooting
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:107:in `create_gist'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:46:in `gistify_logs'
/usr/local/Homebrew/Library/Homebrew/cmd/gist-logs.rb:118:in `gist_logs'
/usr/local/Homebrew/Library/Homebrew/brew.rb:94:in `<main>'
```
#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.0.9
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8a7317aa8ff5f12067eb65e529a13490bc69deda
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: f54ac758351831919913be979d21a1035846cff3
Core tap last commit: 2 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit sandybridge
Homebrew Ruby: 2.0.0-p648
GCC-4.2: build 5666
Clang: 8.0 build 800
Git: 2.10.2 => /usr/local/bin/git
Perl: /usr/local/bin/perl => /usr/local/Cellar/perl/5.24.0_1/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.12_2/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /Users/joseph.yaworski/.rubies/ruby-2.3.1/bin/ruby
Java: 1.8.0_112, 1.8.0_102, 1.8.0_92
macOS: 10.12.1-x86_64
Xcode: 8.1
CLT: 8.1.0.0.1.1476494586
X11: 2.7.11 => /opt/X11
```

**Comment by dpo** [comment] 2016-11-02 21:57
I can't reproduce locally. It seems something's up with your installation. Please try
```
cd /usr/local/Library/Taps/homebrew/homebrew-science && git fetch && git reset --hard origin/master
```
followed by `brew update` and `brew install openblas --with-openmp`. Please also post a link to a gist with the output of `brew doctor`.

**Comment by jyaworski** [comment] 2016-11-06 22:45
I believe this is actually related to gcc-4.2. It compiles with with --cc=gcc-6.

**Comment by dpo** [comment] 2016-11-06 23:42
`--with-openmp` shouldn't select gcc-4.2. Please provide the details requested.

**Comment by iMichka** [comment] 2017-03-10 22:36
Without more details, it will be difficult to debug. This could not be reproduced locally.
I'll close this the time being.

**Closed by iMichka** 2017-03-10 22:36 UTC

**Comment by silwalr** [comment] 2017-04-05 20:22
i have run into compilation issue on mac OS sierra (10.12): please help.
cmd: brew install -sv openblas --with-openmp
Error:
-----------------------------------
gcc-6 -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DASMNAME=_dtrmm_kernel_LN -DASMFNAME=_dtrmm_kernel_LN_ -DNAME=dtrmm_kernel_LN_ -DCNAME=dtrmm_kernel_LN -DCHAR_NAME=\"dtrmm_kernel_LN_\" -DCHAR_CNAME=\"dtrmm_kernel_LN\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -DLEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_4x8_sandy.S -o dtrmm_kernel_LN.o
gcc-6 -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DASMNAME=_dtrmm_kernel_LT -DASMFNAME=_dtrmm_kernel_LT_ -DNAME=dtrmm_kernel_LT_ -DCNAME=dtrmm_kernel_LT -DCHAR_NAME=\"dtrmm_kernel_LT_\" -DCHAR_CNAME=\"dtrmm_kernel_LT\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -DLEFT -DTRANSA ../kernel/x86_64/dgemm_kernel_4x8_sandy.S -o dtrmm_kernel_LT.o
gcc-6 -O2 -DMAX_STACK_ALLOC=2048 -DEXPRECISION -m128bit-long-double -fopenmp -Wall -m64 -DF_INTERFACE_GFORT -fPIC -DSMP_SERVER -DUSE_OPENMP -DNO_WARMUP -DMAX_CPU_NUMBER=8 -DASMNAME=_dtrmm_kernel_RN -DASMFNAME=_dtrmm_kernel_RN_ -DNAME=dtrmm_kernel_RN_ -DCNAME=dtrmm_kernel_RN -DCHAR_NAME=\"dtrmm_kernel_RN_\" -DCHAR_CNAME=\"dtrmm_kernel_RN\" -DNO_AFFINITY -I.. -DDOUBLE  -UCOMPLEX -c -DTRMMKERNEL -DDOUBLE -UCOMPLEX -ULEFT -UTRANSA ../kernel/x86_64/dgemm_kernel_4x8_sandy.S -o dtrmm_kernel_RN.o
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1847:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_LN.o] Error 1
make[1]: *** Waiting for unfinished jobs....
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1847:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_LT.o] Error 1
../kernel/x86_64/dgemm_kernel_4x8_sandy.S:1847:1: error: unexpected token at start of statement
#### Writing Back ####
^
make[1]: *** [dtrmm_kernel_RN.o] Error 1
make: *** [libs] Error 1
---------------------------------
MORE INFO:
==> Formula
Tap: homebrew/science
Path: /usr/local/Homebrew/Library/Taps/homebrew/homebrew-science/openblas.rb
==> Configuration
HOMEBREW_VERSION: 1.1.12
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 8ea778f7c7ea790694485030d105a92a9416ef33
Last commit: 3 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 7abbb82651fb6998b7710b752611e1188e1476ed
Core tap last commit: 4 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit ivybridge
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.9.0 => /usr/local/bin/git
Perl: /usr/bin/perl
Python: /Users/silwal/progs/anaconda/bin/python => /Users/silwal/progs/anaconda/bin/python3.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_112
macOS: 10.12.3-x86_64
Xcode: 8.3
CLT: 8.3.0.0.1.1490382677
X11: 2.7.11 => /opt/X11
==> ENV
HOMEBREW_CC: gcc-6
HOMEBREW_CXX: g++-6
SDKROOT: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.sdk
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local
CMAKE_INCLUDE_PATH: /usr/include/libxml2:/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
MACOSX_DEPLOYMENT_TARGET: 10.12
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig:/usr/local/Homebrew/Library/Homebrew/os/mac/pkgconfig/10.12
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/super:/usr/local/opt/gcc/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/Cellar/gcc/6.3.0_1/bin
----------------------------------

i did the following before trying to install openblas:
brew reinstall gcc --without-multilib

Log files:
[01.make.cc.txt](https://github.com/Homebrew/homebrew-science/files/900713/01.make.cc.txt)
[01.make.txt](https://github.com/Homebrew/homebrew-science/files/900712/01.make.txt)

**Comment by iMichka** [comment] 2017-04-05 20:24
Please don't hijack old issues. Open a new one and fill out the issue template. Thanks
