### ISSUE TITLE
-[]Ran 'brew upgrade root' and got a massive error

### ISSUE THREAD

**Issue by tommy9l** [Homebrew/homebrew-science#4452] opened 2016-10-13 09:19 UTC
### Indicate troubleshooting steps taken

- [x ] Ran `brew update` and retried your prior step?
- [ x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [ ] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
computer crashes or brew stops midway through
#### Gist with output of `brew doctor`:
only warnings, no fatal errors so don't see anything wrong
#### Output of `brew config`:
HOMEBREW_VERSION: 1.0.7
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: 0546d90e3dbdae30407e5256d680be5ed5f5f000
Last commit: 4 days ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 106d0878ee812cb8f5c403f717bdebe836445aee
Core tap last commit: 27 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: octa-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.0 build 800
Git: 2.8.4 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /Users/tommylam/anaconda/bin/python => /Users/tommylam/anaconda/bin/python3.5
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: N/A
macOS: 10.12-x86_64
Xcode: 8.0
CLT: N/A
X11: 2.7.9 => /opt/X11
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

copied after putting "brew install root"
similar error for when i put "brew upgrade root"

CODE WHEN TRYING TO RUN 'BREW INSTALL ROOT'
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
==> Installing root from homebrew/science
==> Downloading https://root.cern.ch/download/root_v5.34.36.source.tar.gz
Already downloaded: /Users/tommylam/Library/Caches/Homebrew/root-5.34.36.tar.gz
==> ./configure --all --enable-builtin-glew --enable-builtin-freetype --disable-
==> make
Last 15 lines from /Users/tommylam/Library/Logs/Homebrew/root/02.make:
cint/cint/src/dict/gcc4strm.cxx:863:56: error: no type named '__istream_type' in 'std::__1::basic_istream<char>'
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->read((basic_istream<char,char_traits<char> >::char_type*) G__int(libp->para[0]), (streamsize) G__Longlong(libp->para[1]));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
cint/cint/src/dict/gcc4strm.cxx:891:56: error: no type named '__istream_type' in 'std::__1::basic_istream<char>'
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->seekg((basic_istream<char,char_traits<char> >::pos_type) G__Longlong(libp->para[0]));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
cp core/pcre/src/pcre-7.8/.libs/libpcre.a lib/libpcre.a
20 errors generated.
make: *** [cint/cint/src/dict/gcc4strm.o] Error 1
make: *** Waiting for unfinished jobs....
g++ -dynamiclib -single_module -undefined suppress -install_name /usr/local/Cellar/root/5.34.36_1/lib/root/libReflex.dylib -O2 -m64 -mmacosx-version-min=10.12 -bind_at_load -o lib/libReflex.dylib cint/reflex/src/Any.o cint/reflex/src/Array.o cint/reflex/src/Base.o cint/reflex/src/BuilderContainer.o cint/reflex/src/Callback.o cint/reflex/src/Class.o cint/reflex/src/ClassBuilder.o cint/reflex/src/ClassTemplateInstance.o cint/reflex/src/DataMember.o cint/reflex/src/DictionaryGenerator.o cint/reflex/src/Enum.o cint/reflex/src/EnumBuilder.o cint/reflex/src/FuncHandler.o cint/reflex/src/Function.o cint/reflex/src/FunctionBuilder.o cint/reflex/src/FunctionMember.o cint/reflex/src/FunctionMemberTemplateInstance.o cint/reflex/src/Fundamental.o cint/reflex/src/GenreflexMemberBuilder.o cint/reflex/src/Kernel.o cint/reflex/src/LiteralString.o cint/reflex/src/Member.o cint/reflex/src/MemberBase.o cint/reflex/src/MemberTemplate.o cint/reflex/src/MemberTemplateImpl.o cint/reflex/src/MemberTemplateName.o cint/reflex/src/NameLookup.o cint/reflex/src/Namespace.o cint/reflex/src/NamespaceBuilder.o cint/reflex/src/Object.o cint/reflex/src/OnDemandBuilder.o cint/reflex/src/OwnedPropertyList.o cint/reflex/src/PluginFactoryMap.o cint/reflex/src/PluginService.o cint/reflex/src/Pointer.o cint/reflex/src/PointerToMember.o cint/reflex/src/PropertyList.o cint/reflex/src/PropertyListImpl.o cint/reflex/src/Scope.o cint/reflex/src/ScopeBase.o cint/reflex/src/ScopeName.o cint/reflex/src/ScopedType.o cint/reflex/src/TemplateInstance.o cint/reflex/src/Tools.o cint/reflex/src/Type.o cint/reflex/src/TypeBase.o cint/reflex/src/TypeBuilder.o cint/reflex/src/TypeName.o cint/reflex/src/TypeTemplate.o cint/reflex/src/TypeTemplateImpl.o cint/reflex/src/TypeTemplateName.o cint/reflex/src/Typedef.o cint/reflex/src/TypedefBuilder.o cint/reflex/src/Union.o cint/reflex/src/UnionBuilder.o cint/reflex/src/VariableBuilder.o -ldl -Llib -lCore -lCint
ld: library not found for -lCore
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [lib/libReflex.dylib] Error 1

**Comment by dpo** [comment] 2016-10-13 16:05
Please post the output of `brew doctor`.

**Comment by tommy9l** [comment] 2016-10-13 17:07
Here is the output of brew doctor

Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/tommylam/anaconda/bin/curl-config
  /Users/tommylam/anaconda/bin/freetype-config
  /Users/tommylam/anaconda/bin/libdynd-config
  /Users/tommylam/anaconda/bin/libpng-config
  /Users/tommylam/anaconda/bin/libpng16-config
  /Users/tommylam/anaconda/bin/python3-config
  /Users/tommylam/anaconda/bin/python3.5-config
  /Users/tommylam/anaconda/bin/python3.5m-config
  /Users/tommylam/anaconda/bin/xml2-config
  /Users/tommylam/anaconda/bin/xslt-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4-config
  /Library/Frameworks/Python.framework/Versions/3.4/bin/python3.4m-config

Warning: Python is installed at /Library/Frameworks/Python.framework

Homebrew only supports building against the System-provided Python or a
brewed Python. In particular, Pythons installed to /Library can interfere
with other software installs.

Warning: Unbrewed dylibs were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected dylibs:
  /usr/local/lib/libaspell.15.1.4.dylib
  /usr/local/lib/libpspell.15.1.4.dylib

Warning: Unbrewed header files were found in /usr/local/include.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected header files:
  /usr/local/include/aspell.h
  /usr/local/include/pspell/pspell.h

Warning: Unbrewed .la files were found in /usr/local/lib.
If you didn't put them there on purpose they could cause problems when
building Homebrew formulae, and may need to be deleted.

Unexpected .la files:
  /usr/local/lib/libaspell.la
  /usr/local/lib/libpspell.la

**Comment by nhartland** [comment] 2016-10-19 19:06
I'm getting the exact same issue on 10.12 also, after a complete un- and re-installation of homebrew and root. brew doctor is clean for me.

**Comment by dpo** [comment] 2016-10-19 20:08
`brew doctor` is clean and you're getting the same issue as in the original post?

**Comment by nhartland** [comment] 2016-10-19 20:13
Yep, exactly, errors in cint/cint/src/dict/gcc4strm.cxx. The problem is also occurring when I attempt to do a diy installation of ROOT. 


```
==> Installing homebrew/science/root
==> Downloading https://root.cern.ch/download/root_v5.34.36.source.tar.gz
######################################################################## 100.0%
==> ./configure --all --enable-builtin-glew --enable-builtin-freetype --disable-ruby --prefix=/usr/local/Cellar/root/5.34.36_1 --etcdir=/usr/local/Cellar/root/5.34.36_1/etc
==> make
Last 15 lines from /Users/hartland/Library/Logs/Homebrew/root/02.make:
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->ignore((streamsize) G__Longlong(libp->para[0]));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
cint/cint/src/dict/gcc4strm.cxx:851:56: error: no type named '__istream_type' in 'std::__1::basic_istream<char>'
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->ignore();
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
cint/cint/src/dict/gcc4strm.cxx:863:56: error: no type named '__istream_type' in 'std::__1::basic_istream<char>'
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->read((basic_istream<char,char_traits<char> >::char_type*) G__int(libp->para[0]), (streamsize) G__Longlong(libp->para[1]));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
cint/cint/src/dict/gcc4strm.cxx:891:56: error: no type named '__istream_type' in 'std::__1::basic_istream<char>'
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->seekg((basic_istream<char,char_traits<char> >::pos_type) G__Longlong(libp->para[0]));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [cint/cint/src/dict/gcc4strm.o] Error 1
make: *** Waiting for unfinished jobs....
```

**Comment by mckunkel** [comment] 2016-10-20 09:57
Greetings, 
I am having the same issue installing ROOT via Homebrew.
`==> Installing root from homebrew/science
==> Downloading https://root.cern.ch/download/root_v5.34.36.source.tar.gz
######################################################################## 100.0%
==> ./configure --all --enable-builtin-glew --enable-builtin-freetype --disable-ruby --prefix=/usr/local/Cellar/root/5.34.36_1 --etcdir=/usr/loc
==> make
Last 15 lines from /Users/michaelkunkel/Library/Logs/Homebrew/root/02.make:
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->ignore((streamsize) G__Longlong(libp->para[0]));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
cint/cint/src/dict/gcc4strm.cxx:851:56: error: no type named '__istream_type' in 'std::__1::basic_istream<char>'
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->ignore();
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
cint/cint/src/dict/gcc4strm.cxx:863:56: error: no type named '__istream_type' in 'std::__1::basic_istream<char>'
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->read((basic_istream<char,char_traits<char> >::char_type*) G__int(libp->para[0]), (streamsize) G__Longlong(libp->para[1]));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
cint/cint/src/dict/gcc4strm.cxx:891:56: error: no type named '__istream_type' in 'std::__1::basic_istream<char>'
         const basic_istream<char,char_traits<char> >::__istream_type& obj = ((basic_istream<char,char_traits<char> >*) G__getstructoffset())->seekg((basic_istream<char,char_traits<char> >::pos_type) G__Longlong(libp->para[0]));
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make: *** [cint/cint/src/dict/gcc4strm.o] Error 1`

brew doctor
`Warning: "config" scripts exist outside your system or Homebrew directories.
`./configure` scripts often look for *-config scripts to determine if
software packages are installed, and what additional flags to use when
compiling and linking.

Having additional scripts in your path can confuse software installed via
Homebrew if the config script overrides a system or Homebrew provided
script of the same name. We found the following "config" scripts:
  /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/freetype-config
  /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/libpng-config
  /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/libpng16-config
  /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/python-config
  /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/python2-config
  /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/python2.7-config
  /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/wx-config
  /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/xml2-config
  /Users/michaelkunkel/Library/Enthought/Canopy_64bit/User/bin/xslt-config

Warning: Enthought Python was found in your PATH.
This can cause build problems, as this software installs its own
copies of iconv and libxml2 into directories that are picked up by
other build systems.`

**Comment by dpo** [comment] 2016-10-20 19:31
It's hard to tell if the issue with `root` is connected to Python but you're running either Anaconda or Enthought Python, which we don't support and have been known to interfere with Homebrew. If at all possible, could you move those Python distributions out of the way (at least temporarily) to build against System or Homebrew Python?

**Comment by tommy9l** [comment] 2016-10-20 22:16
So after removing anaconda, clearing my brew doctor, brew prune, the entire procedure, 
brew install root 
didn't work so I did a bit of work and the following set of commands worked for me
brew tap homebrew/science
brew install root6 
and it works as i expect it to. i just need to try it with maybe some root files and it'll be ok.

**Comment by dpo** [comment] 2016-10-20 22:31
> brew install root didn't work 

Did it fail with the same error as above? Could you `brew gist-logs root`?

**Comment by tommy9l** [comment] 2016-10-20 22:39
This is the result I got
https://gist.github.com/0b102b9249f847ad4787f5f3f367e8fd

**Comment by dpo** [comment] 2016-10-20 22:47
For reference, here's the first error:
```
g++ -O2 -m64 -pipe -Wshadow -W -Wall -Woverloaded-virtual -fsigned-char -fno-common -Iinclude -DR__HAVE_CONFIG       -pthread -UR__HAVE_CONFIG -DROOTBUILD -I/private/tmp/root-20161020-16750-1cw3bh5/root/core/utils/src -o core/utils/src/RStl_tmp.o -c core/utils/src/RStl_tmp.cxx
In file included from cint/cint/src/dict/gcc4strm.cxx:7:
In file included from /private/tmp/root-20161020-16750-1cw3bh5/root/cint/cint/src/dict/gcc4strm.h:30:
cint/cint/lib/gcc4strm/iostrm.h:85:17: error: no type named '__streambuf_type' in 'std::__1::basic_ostream<char>'
static ostream::__streambuf_type *G__store_cout;
       ~~~~~~~~~^
```

**Comment by dpo** [comment] 2016-10-20 22:47
> CLT: N/A

It looks like you didn't install the command-line tools. Try
```
xcode-select --install
```

**Comment by dpo** [comment] 2016-10-21 20:59
I can't reproduce it locally but I'm not running 10.12. I opened https://github.com/Homebrew/homebrew-science/pull/4505 to see if it's reproducible on the bot.

**Comment by dpo** [comment] 2016-10-22 15:32
Should be fixed. Please `brew update`.

**Closed** 2016-10-22 15:31 UTC

**Comment by mckunkel** [comment] 2016-10-25 18:17
Greetings,

I installed CLT and my problem was solved. Oddly, several sources state that native install of Xcode 8 comes with CLT. 

BR
MK 
----------------------------------------
Michael C. Kunkel, USMC, PhD
Forschungszentrum Jülich
Nuclear Physics Institute and Juelich Center for Hadron Physics
Experimental Hadron Structure (IKP-1)
www.fz-juelich.de/ikp
