### ISSUE TITLE
superlu_dist fails make test when installing

### ISSUE THREAD

**Issue by McNoggins** [Homebrew/homebrew-science#6435] opened 2017-11-09 19:00 UTC
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:

Basically, the formula is not able to pass the `make test` stage when compiling. It may or may not be related to the OpenMPI 3.0 update, as the issue which prompted me to reinstall superlu_dist in the first place is similar to #6433 when I try to use the (previously working) piece of software:

```
dyld: Library not loaded: /usr/local/opt/open-mpi/lib/libmpi.20.dylib
Referenced from: /usr/local/opt/superlu_dist/lib/libsuperlu_dist.5.dylib
Reason: image not found
```

Basically, when I saw these issues I tried to reinstall superlu_dist only for the build to fail, which is the reason for me opening this issue.

#### The complete command that you issued:

`brew reinstall superlu_dist`

#### Gist with output of `brew doctor`:

https://gist.github.com/anonymous/4c683f2aa5965ecb1e78ef956dd2eb21#file-00-doctor-out

#### Link output by `brew gist-logs superlu_dist`:

https://gist.github.com/4c683f2aa5965ecb1e78ef956dd2eb21

#### Output of `brew config`:

```
HOMEBREW_VERSION: 1.3.6-207-g934480c
ORIGIN: https://github.com/Homebrew/brew
HEAD: 934480ca44b292cb6a50b2fc4a6aa78e065c1e47
Last commit: 35 hours ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: 66b919a489a2fed751f9630c034d1eec2c9ce047
Core tap last commit: 3 hours ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_DEV_CMD_RUN: 1
HOMEBREW_GIT_CONFIG_FILE: /usr/local/Homebrew/.git/config
CPU: quad-core 64-bit broadwell
Homebrew Ruby: 2.3.3 => /usr/local/Homebrew/Library/Homebrew/vendor/portable-ruby/2.3.3/bin/ruby
Clang: 9.0 build 900
Git: 2.15.0 => /usr/local/bin/git
Curl: 7.54.0 => /usr/bin/curl
Perl: /usr/bin/perl
Python: /usr/local/opt/python/libexec/bin/python => /usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
Java: N/A
macOS: 10.13.1-x86_64
Xcode: N/A
CLT: 9.0.1.0.1.1506734476
X11: N/A
```

### Additional details

1.  Here is the output of `make test` (it is also in the gist-logs)

```
2017-11-09 13:11:10 -0500

make
test

Running tests...
/usr/local/Cellar/cmake/3.9.5/bin/ctest --force-new-ctest-process 
Test project /tmp/superlu_dist-20171109-38129-qgzjm8/SuperLU_DIST_5.1.0/build
    Start 1: pddrive
1/2 Test #1: pddrive ..........................***Failed    0.15 sec
    Start 2: pddrive1
2/2 Test #2: pddrive1 .........................***Failed    0.05 sec

0% tests passed, 2 tests failed out of 2

Total Test time (real) =   0.20 sec

The following tests FAILED:
	  1 - pddrive (Failed)
	  2 - pddrive1 (Failed)
Errors while running CTest
make: *** [test] Error 8
```
2. Tested it on `linuxbrew` on a different computer and got the same `make test` failure.

**Comment by ramet** [comment] 2017-11-10 16:43
I try to reproduce the ctest errors in the build repository from homebrew (VERBOSE=1 brew upgrade superlu_dist --keep-tmp). On MacOS HighSierra with clang from command-line tools, I got: 

```
/usr/local/bin/mpiexec -n 4 pddrive -r 2 -c 2 /tmp/superlu_dist-20171110-37854-14q2t7/SuperLU_DIST_5.1.0/EXAMPLE/big.rua
--------------------------------------------------------------------------
There are not enough slots available in the system to satisfy the 4 slots
that were requested by the application:
  pddrive

Either request fewer slots for your application, or make more slots available
for use.
--------------------------------------------------------------------------
```

It seems to be an MPI problem.
With 2 cores, for instance, it works:

```
mpirun -n 2 pddrive -r 2 -c 1 /tmp/superlu_dist-20171110-37854-14q2t7/SuperLU_DIST_5.1.0/EXAMPLE/big.rua
Input matrix file: /tmp/superlu_dist-20171110-37854-14q2t7/SuperLU_DIST_5.1.0/EXAMPLE/big.rua
	Process grid	2 X 1
**************************************************
.. blocking parameters from sp_ienv():
**    relaxation           :       20
**    max supernode        :      128
**    estimated fill ratio :        5
**************************************************
**************************************************
.. options:
**    Fact             :    0
**    Equil            :    1
**    ParSymbFact      :    0
**    ColPerm          :    4
**    RowPerm          :    1
**    ReplaceTinyPivot :    1
**    IterRefine       :    2
**    Trans            :    0
**    num_lookaheads   :   10
**    SymPattern       :    0
**    lookahead_etree  :    0
**************************************************
	Nonzeros in L       48493
	Nonzeros in U       48493
	nonzeros in L+U     92026
	nonzeros in LSUB    12699
.. dQuery_Space: peak_buffer 3118412 * 1.0e-6 (MB)
.. dQuery_Space: peak_buffer 3110220 * 1.0e-6 (MB)

** Memory Usage **********************************
** NUMfact space (MB): (sum-of-all-processes)
    L\U :            0.82 |  Total :     7.05
** Total highmark (MB):
    Sum-of-all :     7.05 | Avg :     3.52  | Max :     3.55
**************************************************
	Sol  0: ||X-Xtrue||/||X|| = 1.088019e-14
**************************************************
**** Time (seconds) ****
	EQUIL time             0.00
	ROWPERM time           0.00
	COLPERM time           0.02
	SYMBFACT time          0.00
	DISTRIBUTE time        0.00
	FACTOR time            0.00
	Factor flops	9.667910e+05	Mflops 	  268.86
	SOLVE time             0.00
	Solve flops	1.856430e+05	Mflops 	  209.76
	REFINEMENT time        0.00	Steps       1

**************************************************
```

**Comment by McNoggins** [comment] 2017-11-10 16:57
Try adding `--oversubscribe` to your mpi command. I think oversubscription may be disabled by default. If that's the problem, it should just be added to the test.

**Comment by ramet** [comment] 2017-11-10 17:01
It works with the oversubscribe option. Thanks.
```
/usr/local/bin/mpiexec --oversubscribe -n 4 pddrive -r 2 -c 2 /tmp/superlu_dist-20171110-41313-q8e342/SuperLU_DIST_5.1.0/EXAMPLE/big.rua
Input matrix file: /tmp/superlu_dist-20171110-41313-q8e342/SuperLU_DIST_5.1.0/EXAMPLE/big.rua
	Process grid	2 X 2
**************************************************
.. blocking parameters from sp_ienv():
**    relaxation           :       20
**    max supernode        :      128
**    estimated fill ratio :        5
**************************************************
**************************************************
.. options:
**    Fact             :    0
**    Equil            :    1
**    ParSymbFact      :    0
**    ColPerm          :    4
**    RowPerm          :    1
**    ReplaceTinyPivot :    1
**    IterRefine       :    2
**    Trans            :    0
**    num_lookaheads   :   10
**    SymPattern       :    0
**    lookahead_etree  :    0
**************************************************
	Nonzeros in L       48493
	Nonzeros in U       48493
	nonzeros in L+U     92026
	nonzeros in LSUB    12699
.. dQuery_Space: peak_buffer 3115384 * 1.0e-6 (MB)
.. dQuery_Space: peak_buffer 3115384 * 1.0e-6 (MB)
.. dQuery_Space: peak_buffer 3107192 * 1.0e-6 (MB)
.. dQuery_Space: peak_buffer 3107192 * 1.0e-6 (MB)

** Memory Usage **********************************
** NUMfact space (MB): (sum-of-all-processes)
    L\U :            0.82 |  Total :    13.27
** Total highmark (MB):
    Sum-of-all :    13.27 | Avg :     3.32  | Max :     3.48
**************************************************
	Sol  0: ||X-Xtrue||/||X|| = 1.110223e-14
**************************************************
**** Time (seconds) ****
	EQUIL time             0.00
	ROWPERM time           0.00
	COLPERM time           0.02
	SYMBFACT time          0.00
	DISTRIBUTE time        0.01
	FACTOR time            0.02
	Factor flops	9.667910e+05	Mflops 	   56.79
	SOLVE time             0.00
	Solve flops	1.856430e+05	Mflops 	   72.12
	REFINEMENT time        0.00	Steps       1

**************************************************
```

**Comment by McNoggins** [comment] 2017-11-10 17:02
OK, I'll try to update the formula soon!

**Comment by McNoggins** [comment] 2017-11-10 17:19
Hum, this is a bit more complicated than I thought since it involves changing the `EXAMPLE/CMakeLists.txt` file upstream. If anybody has an idea, it would be welcome.

**Comment by ilovezfs** [comment] 2017-11-10 17:57
This should be fixed if you `brew update` and `brew upgrade`

**Closed by ilovezfs** 2017-11-10 17:57 UTC

**Comment by McNoggins** [comment] 2017-11-10 18:20
FYI: For it to build correctly, I have to do `brew install superlu_dist --without-test` and change the Formula as follows:
```
diff --git a/superlu_dist.rb b/superlu_dist.rb
index bc57c0cf..5dd924e6 100644
--- a/superlu_dist.rb
+++ b/superlu_dist.rb
@@ -54,6 +54,6 @@ class SuperluDist < Formula
     cp pkgshare/"EXAMPLE/pddrive.c", testpath
     cp pkgshare/"EXAMPLE/g20.rua", testpath
     system "mpicc", "-o", "pddrive", "pddrive.c", "dcreate_matrix.c", "-L#{Formula["superlu_dist"].opt_lib}", "-lsuperlu_dist"
-    system "mpirun", "-np", "4", "./pddrive", "-r", "2", "-c", "2", "g20.rua"
+    system "mpirun", "--oversubscribe","-np", "4", "./pddrive", "-r", "2", "-c", "2", "g20.rua"
   end
 end
```
I think it has to do with oversubscription being disabled by default in new versions of openmpi or something like that.
