### ISSUE TITLE
root6 directories (fonts, icons) end up in wrong place?

### ISSUE THREAD

**Issue by wickles** [Homebrew/homebrew-science#6012] opened 2017-07-25 18:41 UTC
ROOT expects directories `fonts` and `icons` in the top level `root6` directory, but brew installs them into `root6/share/root`. Upstream claims this may be an error in the formula, but it's not clear to me yet if that's true. Errors appear in basic usage: 

```
> % env ROOTSYS=/usr/local/opt/root6 root -l data.root
root [0]
Attaching file data.root as _file0...
(TFile *) 0x7f808891da60
root [1] save->Draw("targetPos")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
```

More information here: https://root-forum.cern.ch/t/latest-root6-from-homebrew-cannot-find-fonts-and-icons/25562

**Comment by jonchang** [comment] 2017-07-26 01:32
Thanks for the report @wickles. I don't see `data.root` in the `root6` installation and therefore can't reproduce your issue. Could you possibly provide this file (or ideally reproduce the issue using a `.root` file from the `root6` install?)

**Comment by wickles** [comment] 2017-07-26 17:23
Hi, my apologies, that was just an example with placeholder filename and contents. 

Here is an example you can actually try.
```
> % root -l /usr/local/opt/root6/share/doc/root/tutorials/mlp/mlpHiggs.root
root [0]
Attaching file tutorials/mlp/mlpHiggs.root as _file0...
(TFile *) 0x7fe98ee5b640
root [1] sig_filtered->Draw("msumf")
Error in <TSystem::ExpandFileName>: input: $ROOTSYS/icons/Root6Icon.png, output: $ROOTSYS/icons/Root6Icon.png
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
```

**Comment by jonchang** [comment] 2017-07-26 18:18
Your instructions seem to work without error when sourcing the Bash script from the caveats section:

```
$   . $(brew --prefix root6)/libexec/thisroot.sh
$ root -l /usr/local/opt/root6/share/doc/root/tutorials/mlp/mlpHiggs.root
root [0] 
Attaching file /usr/local/opt/root6/share/doc/root/tutorials/mlp/mlpHiggs.root as _file0...
(TFile *) 0x7f8514dad890
root [1] sig_filtered->Draw("msumf")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
```

Is there something I'm overlooking here?

**Comment by wickles** [comment] 2017-07-26 18:24
Try this instead, changing line `root [1]`.
```
> % root -l /usr/local/opt/root6/share/doc/root/tutorials/mlp/mlpHiggs.root
root [0]
Attaching file /usr/local/opt/root6/share/doc/root/tutorials/mlp/mlpHiggs.root as _file0...
(TFile *) 0x7fde868968d0
root [1] sig_filtered->Draw("msumf - 1")
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
Error in <FontCache::SelectSymbolFont>: symbol.ttf file not found
```
You should also see that the ROOT applet's icon is not correct unless you symlink the directories as described in the thread on the ROOT forums.

**Comment by jonchang** [comment] 2017-07-27 19:37
The file `cmake/modules/RootInstallDirs.cmake` sets the following install locations for the font and icons files, relative to the installation prefix (`brew --prefix root6`):

```cmake
  if(gnuinstall)
    set(CMAKE_INSTALL_ICONDIR "${CMAKE_INSTALL_DATADIR}/icons")
  else()
    set(CMAKE_INSTALL_ICONDIR "icons")
  endif()
```

where `CMAKE_INSTALL_DATADIR` is set by

```cmake
  if(gnuinstall)
    set(CMAKE_INSTALL_DATADIR "${CMAKE_INSTALL_DATAROOTDIR}/root")
  else()
    set(CMAKE_INSTALL_DATADIR ".")
  endif()
```

and `CMAKE_INSTALL_DATAROOTDIR` is set by

```cmake
  if(gnuinstall)
    set(CMAKE_INSTALL_DATAROOTDIR "share" CACHE PATH "root for the data (share)")
  else()
    set(CMAKE_INSTALL_DATAROOTDIR "." CACHE PATH "root for the data ()")
  endif()
```

thus relative to the prefix directory the icons and fonts will be installed to `/usr/local/opt/root6/share/root/` directory. Homebrew sets the `-Dgnuinstall` option as we are performing a "fixed install" per their instructions in `README/INSTALL`:

```
3.2. Fixed location build:
---------------------------

You want to install ROOT in a fixed location, not depending on
ROOTSYS. Typically you want to do this when installing in a location
like `/usr/local/bin' or even `/usr/bin'. This allows you, and all
others on your system, to run ROOT without having to setup ROOTSYS and
special PATH and LD_LIBRARY_PATH variables.

It's _strongly_ recommended to enable version numbers in sonames (if
possible) using this method (see 'soversion' option below). Also,
using the 'rpath' option to "cmake" you can set the load
path to the ROOT libraries on the applications. However, this is not
recommended if you have some other way (like /etc/ld.so.conf) of
making the dynamic loader aware of where you installed the ROOT
libraries.

   1) Get the sources of latest ROOT (see above)

   2) Now type the build commands:
        mkdir <builddir>
        cd <builddir>
        cmake ../root -DCMAKE_INSTALL_PREFIX=<prefix> -Dgnuinstall=ON 
        cmake --build .                  [ or simply "make -j<N>" on Unix systems ]
        cmake --build . --target install [ or simply "make install" on Unix systems ]
```

@wickles, as a ***temporary*** fix please specify the correct location of `CMAKE_INSTALL_ICONDIR` and `CMAKE_INSTALL_FONTDIR` in the `root6.rb` formula. I can help with this so ping me if you need assistance. Please also report this issue to upstream since this is either a problem with their documentation, packaging defaults, or how the `root` executable locates architecture-independent files.

**Closed by jonchang** 2017-07-27 19:37 UTC

**Comment by wickles** [comment] 2017-07-27 20:59
Thanks for your help in identifying the problem, I've reported it upstream.

**Comment by wickles** [comment] 2017-08-28 16:12
Problem has been [fixed upstream](https://sft.its.cern.ch/jira/browse/ROOT-8970), thanks again.
