### ISSUE TITLE
regression: brew upgrade homebrew/science/opencv3 fails

### ISSUE THREAD

**Issue by timotheecour** [Homebrew/homebrew-science#4400] opened 2016-10-04 23:42 UTC
brew gist-logs homebrew/science/opencv3
https://gist.github.com/e00f6e3f21eebb9f5c022f241612ec44

(used to work)

```
Usage: /home/timothee/.linuxbrew/bin/python-config [--prefix|--exec-prefix|--includes|--libs|--cflags|--ldflags|--help]
==> Downloading https://raw.githubusercontent.com/opencv/opencv_3rdparty/81a676001ca8075ada498583e4166079e5744668/ippicv/ippicv_linux_20151201.tgz
Already downloaded: /home/timothee/.cache/Homebrew/opencv3--icv-linux-20151201.tgz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/home/timothee/.linuxbrew/Cellar/opencv3/3.1.0_4 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DCMAK
==> make
Last 15 lines from /home/timothee/.cache/Homebrew/Logs/opencv3/02.make:
make[2]: Leaving directory '/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild'
[100%] Built target opencv_traincascade
cd /tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild && /home/timothee/.linuxbrew/Cellar/cmake/3.6.2/bin/cmake -E cmake_depends "Unix Makefiles" /tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0 /tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/python/python2 /tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild /tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild/modules/python2 /tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild/modules/python2/CMakeFiles/opencv_python2.dir/DependInfo.cmake --color=
Scanning dependencies of target opencv_python2
make[2]: Leaving directory '/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild'
make -f modules/python2/CMakeFiles/opencv_python2.dir/build.make modules/python2/CMakeFiles/opencv_python2.dir/build
make[2]: Entering directory '/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild'
make[2]: *** No rule to make target '/libpython2.7.so', needed by 'lib/cv2.so'.  Stop.
make[2]: *** Waiting for unfinished jobs....
[100%] Building CXX object modules/python2/CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o
cd /tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild/modules/python2 && /home/timothee/.linuxbrew/bin/g++-5   -D__OPENCV_BUILD=1 -Dopencv_python2_EXPORTS -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/3rdparty/ippicv/unpack/ippicv_lnx/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild -isystem /home/timothee/.linuxbrew/include/eigen3 -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/python/python2/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/python/python2/src -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild/modules/python2 -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/core/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/flann/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/imgproc/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/ml/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/photo/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/video/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/imgcodecs/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/shape/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/videoio/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/highgui/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/objdetect/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/superres/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/features2d/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/calib3d/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/stitching/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/videostab/include -I/home/timothee/.linuxbrew/Cellar/python/2.7.12_1/include/python2.7 -I/home/timothee/.linuxbrew/lib/python2.7/site-packages/numpy/core/include -I/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/python/src2  -Os -w -pipe -march=native    -fsigned-char -W -Wall -Werror=return-type -Werror=non-virtual-dtor -Werror=address -Werror=sequence-point -Wformat -Werror=format-security -Wmissing-declarations -Wundef -Winit-self -Wpointer-arith -Wshadow -Wsign-promo -Wno-narrowing -Wno-delete-non-virtual-dtor -Wno-unnamed-type-template-args -fdiagnostics-show-option -Wno-long-long -pthread -fomit-frame-pointer -msse -msse2 -mno-avx -msse3 -mno-ssse3 -mno-sse4.1 -mno-sse4.2 -ffunction-sections -fvisibility=hidden -fvisibility-inlines-hidden -Wno-unused-function -DNDEBUG  -DNDEBUG -fPIC   -o CMakeFiles/opencv_python2.dir/__/src2/cv2.cpp.o -c /tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/modules/python/src2/cv2.cpp
make[2]: Leaving directory '/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild'
make[1]: *** [CMakeFiles/Makefile2:3681: modules/python2/CMakeFiles/opencv_python2.dir/all] Error 2
make[1]: Leaving directory '/tmp/opencv3-20161004-6085-1tszp1q/opencv-3.1.0/macbuild'
make: *** [Makefile:164: all] Error 2
```

**Comment by rwhogg** [comment] 2016-10-20 02:07
I think this might be a duplicate of https://github.com/Homebrew/homebrew-science/issues/2905

**Comment by dpo** [comment] 2016-10-22 16:12
Duplicate of #2905. There's an indication there on how to fix the problem.

**Closed by dpo** 2016-10-22 16:12 UTC
