### ISSUE TITLE
vigra-1.10.0 did not build

### ISSUE THREAD

**Issue by habi** [Homebrew/homebrew-science#2428] opened 2015-06-20 23:09 UTC
I wanted to install `homebrew/science/enblend-enfuse` which has `vigra` as dependency.
This failed to build on OS X 10.10.4 (14E33b).

Logs: https://gist.github.com/11f85ad1a2db789301de

Output:

```
$ brew install vigra
==> Installing vigra from homebrew/homebrew-science
==> Downloading https://github.com/ukoethe/vigra/releases/download/Version-1-10-
Already downloaded: /Library/Caches/Homebrew/vigra-1.10.0.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE= -DCMAKE_CXX_FLAGS_RELEASE= -DCMAKE_INSTALL
==> make
==> make check

/usr/local/Cellar/cmake/3.2.3/bin/cmake -E cmake_progress_report /tmp/vigra20150621-62775-cexkzn/vigra-1.10.0/build/CMakeFiles  33 34
[ 42%] Built target test_gridgraph
make[1]: *** [CMakeFiles/check.dir/rule] Error 2
make: *** [check] Error 2
```

**Comment by tseemann** [comment] 2015-06-25 09:49
I can confirm I get the same error on Yosemite.

**Comment by sergeyk** [comment] 2015-06-29 05:15
Getting the same error, same OS. Temporary solution: `brew install --without-check vigra`.

https://gist.github.com/anonymous/654f8cdddeccbffe0fec

**Comment by dpo** [comment] 2015-06-30 10:20
Please post the output of `brew gist-logs vigra`.

**Comment by habi** [comment] 2015-06-30 10:29
@dpo I think I did, see at the top.

**Comment by dpo** [comment] 2015-07-03 10:10
Oh, sorry. I missed it somehow. [This thread](http://octave.1599824.n4.nabble.com/Building-Octave-on-Mac-OS-10-10-Yosemite-td4667033.html) suggests it's a bug in clang from Xcode 6.x. I'm getting the same error with Xcode 6.2. See also http://savannah.gnu.org/bugs/?43298. There's apparently [a patch](https://savannah.gnu.org/patch/index.php?8551) for a similar error in `octave`. I'll report the issue to the `vigra` folks.

You might try to build `vigra` with gcc until we know how to fix this.

**Comment by twlz0ne** [comment] 2016-01-13 03:26
Same on 10.9.5

**Comment by jakirkham** [comment] 2016-02-23 19:15
This is not a `vigra` error. It is a clang bug. ( https://llvm.org/bugs/show_bug.cgi?id=21083 )

We encountered this as well when adding Mac CI testing for `vigra`. It turns out that no version of XCode 6.x works because they all suffer from this bug. Switching to XCode 7.3 solved this problem. There may be earlier versions of XCode 7.x that work, as well, but I don't believe they worked either.

**Comment by 0x00B1** [comment] 2016-03-30 21:39
Upgrading Xcode to 7.3 has not resolved this issue for me.

**Comment by fitzyjoe** [comment] 2016-09-26 15:15
I upgraded to macOS Sierra and building `vigra` fails for me.

```
joefitz@Plum:~/Documents/Projects/Tesla/git/nginx-jwt-module/libjwt-master $ brew upgrade
==> Upgrading 1 outdated package, with result:
homebrew/science/vigra 1.10.0_2
==> Not upgrading 1 pinned package:
mysql 5.7.15
==> Upgrading homebrew/science/vigra
==> Downloading https://github.com/ukoethe/vigra/releases/download/Version-1-10-0/vigra-1.10.0-src-with-docu.tar.gz
Already downloaded: /Users/joefitz/Library/Caches/Homebrew/vigra-1.10.0.tar.gz
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/vigra/1.10.0_2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LA
==> make
Last 15 lines from /Users/joefitz/Library/Logs/Homebrew/vigra/02.make:
  "_jpeg_stdio_dest", referenced from:
      vigra::JPEGEncoderImpl::JPEGEncoderImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in jpeg.cxx.o
  "_jpeg_stdio_src", referenced from:
      vigra::JPEGDecoderImpl::JPEGDecoderImpl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&) in jpeg.cxx.o
  "_jpeg_write_m_byte", referenced from:
      _write_icc_profile in iccjpeg.c.o
  "_jpeg_write_m_header", referenced from:
      _write_icc_profile in iccjpeg.c.o
  "_jpeg_write_scanlines", referenced from:
      vigra::JPEGEncoder::nextScanline() in jpeg.cxx.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [src/impex/libvigraimpex.5.1.10.0.dylib] Error 1
make[1]: *** [src/impex/CMakeFiles/vigraimpex.dir/all] Error 2
make: *** [all] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/brew):
  https://github.com/Homebrew/homebrew-science/issues

These open issues may also help:
vigra-1.10.0 did not build https://github.com/Homebrew/homebrew-science/issues/2428
```

**Comment by iMichka** [comment] 2017-02-24 19:49
Vigra now builds since #5026. Closing.

**Closed by iMichka** 2017-02-24 19:49 UTC
Labels: build-error
