### ISSUE TITLE
OpenCV3 brew --with-python3

### ISSUE THREAD

**Issue by Neabfi** [Homebrew/homebrew-science#5472] opened 2017-04-22 08:09 UTC
I'm trying to install OpenCV for Python 3.

```brew install opencv3 --with-contrib --with-python3 --HEAD```

But this creates 

```/usr/local/opt/opencv3/lib/python2.7/```

but not

```/usr/local/opt/opencv3/lib/python3.5/```

So I can't import OpenCV in Python 3

    Python 3.5.1 (v3.5.1:37a07cee5969, Dec  5 2015, 21:12:44) 
    [GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import cv2
    Traceback (most recent call last):
    File "<stdin>", line 1, in <module>
    ImportError: No module named 'cv2'
    >>>

**Comment by iMichka** [comment] 2017-04-22 09:40
Hi

- We do not support `--HEAD` builds completely. Using this means you know what you are doing.
- Next time, please fill out the issue template.

This is a duplicate of #5463

**Closed by iMichka** 2017-04-22 09:40 UTC
