### ISSUE TITLE
Sambamba compilation error (undefined identifier pthread_t)

### ISSUE THREAD

**Issue by karel-brinda** [Homebrew/homebrew-science#2933] opened 2015-10-26 11:33 UTC
```
$ brew install sambamba
==> Installing sambamba from homebrew/homebrew-science
==> Cloning https://github.com/lomereiter/sambamba.git
Updating /Library/Caches/Homebrew/sambamba--git
==> Checking out tag v0.5.6
==> make sambamba-ldmd2-64
Last 15 lines from /Users/karel/Library/Logs/Homebrew/sambamba/01.make:
cram/htslib.d(618): Error: undefined identifier pthread_t
cram/htslib.d(619): Error: undefined identifier pthread_cond_t
cram/htslib.d(633): Error: undefined identifier pthread_mutex_t
cram/htslib.d(634): Error: undefined identifier pthread_cond_t
cram/htslib.d(635): Error: undefined identifier pthread_cond_t
cram/htslib.d(636): Error: undefined identifier pthread_cond_t
cram/htslib.d(651): Error: undefined identifier pthread_mutex_t
cram/htslib.d(652): Error: undefined identifier pthread_cond_t
cram/htslib.d(1013): Error: undefined identifier pthread_mutex_t
cram/htslib.d(1087): Error: undefined identifier off_t
cram/htslib.d(1096): Error: undefined identifier pthread_mutex_t
cram/htslib.d(1097): Error: undefined identifier pthread_mutex_t
cram/htslib.d(1099): Error: undefined identifier pthread_mutex_t
cram/htslib.d(1513): Error: undefined identifier off_t
make: *** [sambamba-ldmd2-64] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues
```

**OS:**  OS X (El Capitan, 10.11.1)

**Comment by tseemann** [comment] 2015-10-27 02:52
@karel-brinda Can you send the link to the output of `brew gist-logs sambamba` please?

**Comment by karel-brinda** [comment] 2015-10-27 15:01
@tseemann Here it is: https://gist.github.com/e223abe944650ba615df.

**Comment by lomereiter** [comment] 2016-03-09 06:57
Hi, this is a duplicate of https://github.com/lomereiter/sambamba/issues/194
Please report compilation errors upstream in the future, thanks!

**Comment by iMichka** [comment] 2017-04-30 08:22
Hi. We are providing sambamba v0.6.6 now, and it has even bottles. The upstream bug seems to have been fixed.

@karel-brinda If you have still troubles installing sambamba, please open a new issue. Thanks.

**Closed by iMichka** 2017-04-30 08:22 UTC
Labels: 10.11, Bioinformatics, build-error
