### ISSUE TITLE
ipopt does not work with the openblas option

### ISSUE THREAD

**Issue by micrain** [Homebrew/homebrew-science#3533] opened 2016-04-12 18:49 UTC
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [X] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X] Checked that a similar issue hasn't already been filed?
- [X] Looked up the software bug tracker if reporting a build error?
- [X] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

I tried to install ipopt with --with-openblas but it is not working. The command I tried was `brew install homebrew/science/ipopt [--with-openblas]`. I tried running `brew untap homebrew/science` and rerunning the install command again but it does not seem to help. I keep on getting the following error message.

-----

Error: Formulae found in multiple taps: 
 * homebrew/core/n
 * homebrew/science/r

Please use the fully-qualified name e.g. homebrew/core/n to refer the formula.

-----

I don't get any issues when I run `brew install homebrew/science/ipopt`.

**Comment by dpo** [comment] 2016-04-12 21:02
What happens when you just say `brew install ipopt --with-openblas`? If there's an error, could you please post a link to the output of `brew doctor`?

**Comment by dpo** [comment] 2016-04-23 21:44
I can't reproduce this. It works fine for me.

**Comment by dpo** [comment] 2016-05-19 10:55
@micrain

**Comment by dpo** [comment] 2016-06-12 00:01
Closing this as unreproducible. Please reopen if the issue persists.

**Closed by dpo** 2016-06-12 00:01 UTC
Labels: Math, needs response, unreproducible
