### ISSUE TITLE
gfortran problem while installing Octave

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-science#2806] opened 2015-10-01 20:44 UTC
_From @brkztrk on October 1, 2015 19:58_

Hi there,

I am trying to install Octave on my mac, OS X El Capitan. I got this issue, i searched but nothing found.

make
check

gfortran -o tester -O tester.f90 vecLibFort.o -framework Accelerate 
ld: framework not found Accelerate
collect2: error: ld returned 1 exit status
make: *** [check] Error 1

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

How can I fix that?

Thanks in advance.

_Copied from original issue: Homebrew/homebrew#44502_

**Comment by dpo** [comment] 2015-10-01 21:25
Duplicate of #2802.

**Closed by dpo** 2015-10-01 21:25 UTC
