### ISSUE TITLE
Octave: imshow() image scaling incorrect with qt

### ISSUE THREAD

**Issue by ixig** [Homebrew/homebrew-science#4827] opened 2017-01-08 11:17 UTC
On my MacBook Pro Sierra, imshow() displays the image at half-size. Upon showing the 'axis' in the figure viewer, I can see that the image is only half the size of the axis labels -- i.e. the image fills only (0,0) to (256,256) of the graph's viewplot (which is sized to 512x512, corresponding to the image size).

If I switch to "graphics_toolkit('gnuplot')" -- the default seems to be set for qt -- the image is sized correctly, so I suspect that the qt graph/image viewer, using opengl to render the image, is using retina scaling for image rendering, but the rest of the viewer is not. Not sure if this is an octave or brew package issue?

https://gist.github.com/anonymous/15e31b6704410abac420fb83b045d806

**Comment by ixig** [comment] 2017-01-08 12:57
Looks like this issue is with Octave ... but although 'Sebastian' indicated a patch was already made in Homebrew 4.2, if so, it didn't work for my install.

**Comment by ilovezfs** [comment] 2017-01-08 12:58
CC @schoeps any idea what the problem is?

**Comment by schoeps** [comment] 2017-01-08 16:07
It's a known bug in Octave. Therefore I suggedt to close the issue here.

Background: qt5 deals properly with retina displays but octave was not adapted when switching from qt4 to qt5. The current formula comes with a first patch (as mentined above) that fixes most issues with the regular plot command, many other plotting routines are not yet tackled.

If anybody has experience with qt development on macOS then he/she would be very welcome to help!

**Comment by ilovezfs** [comment] 2017-01-08 16:10
Given that http://savannah.gnu.org/bugs/?49053 is still open, I think we can close this issue.

**Closed by ilovezfs** 2017-01-08 16:10 UTC
