### ISSUE TITLE
LAMMPS install issues with libgfortran.3.dylib

### ISSUE THREAD

**Issue by ouojeda** [Homebrew/homebrew-science#3801] opened 2016-07-01 18:16 UTC
Hi, Tried installing home-brew and then lammps on mac. Seems to work fine (no errors, just a python directory warning). When I try to test it, it fails, asking for a Fc dynamic library issue:

Testing homebrew/science/lammps
==> Using the sandbox
/usr/bin/sandbox-exec -f /tmp/homebrew20160701-59955-1kjiwvs.sb /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby -W0 -I /usr/local/Library/Homebrew -- /usr/local/Library/Homebrew/test.rb /usr/local/Library/Taps/homebrew/homebrew-science/lammps.rb -v
==> lammps -in /usr/local/share/lammps/bench/in.lj
dyld: Library not loaded: /usr/local/lib/gcc/5/libgfortran.3.dylib
  Referenced from: /usr/local/bin/lammps
  Reason: image not found
Error: homebrew/science/lammps: failed
Failed executing: lammps -in /usr/local/share/lammps/bench/in.lj
/usr/local/Library/Homebrew/formula.rb:1486:in `block in system'
/usr/local/Library/Homebrew/formula.rb:1423:in `open'
/usr/local/Library/Homebrew/formula.rb:1423:in `system'
/usr/local/Library/Taps/homebrew/homebrew-science/lammps.rb:212:in `block (2 levels) in <class:Lammps>'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Taps/homebrew/homebrew-science/lammps.rb:211:in `block in <class:Lammps>'
/usr/local/Library/Homebrew/formula.rb:1328:in `block in run_test'
/usr/local/Library/Homebrew/extend/fileutils.rb:14:in `block in mktemp'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `block in run'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `chdir'
/usr/local/Library/Homebrew/extend/fileutils.rb:75:in `run'
/usr/local/Library/Homebrew/extend/fileutils.rb:13:in `mktemp'
/usr/local/Library/Homebrew/formula.rb:1322:in `run_test'
/usr/local/Library/Homebrew/test.rb:28:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/timeout.rb:66:in `timeout'
/usr/local/Library/Homebrew/test.rb:27:in `<main>'

Let me know if anybody experiences this, or how to fix.
Thanks

**Comment by dpo** [comment] 2016-07-01 19:36
Duplicate of #3791.

**Closed by dpo** 2016-07-01 19:36 UTC
