### ISSUE TITLE
OCE Package Issues

### ISSUE THREAD

**Issue by rajeeja** [Homebrew/homebrew-science#5499] opened 2017-04-25 18:58 UTC
### Indicate troubleshooting steps taken

- [ ] Ran `brew update` and retried your prior step?
yes
- [ ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
yes
- [ ] Checked that a similar issue hasn't already been filed?
yes
- [ ] Looked up the software bug tracker if reporting a build error?
yes
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
yes
### Bug reports / build errors:
No build errors.

#### Brief summary of issue:

The following error shows up after launching DRAWEXE

==> DRAWEXE
**can't read "::env(CASROOT)"**: no such variable
Draw[1]> Draw[2]> exit

Another library (https://bitbucket.org/fathomteam/cgm/) that I link with OCE gives the following error:
[ 84%] Linking CXX executable brick_facet
**ld: library not found for -lDRAWEXE**
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [test/brick_facet] Error 1
make[1]: *** [test/CMakeFiles/brick_facet.dir/all] Error 2
make: *** [all] Error 2

I have CASROOT set and also DYLD_LIBRARY_PATH

lDRAWEXE is not available in the installation

#### The complete command that you issued:
==> DRAWEXE
**can't read "::env(CASROOT)"**: no such variable
Draw[1]> Draw[2]> exit
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by jonchang** [comment] 2017-04-25 21:27
> ==> DRAWEXE
> can't read "::env(CASROOT)": no such variable
> Draw[1]> Draw[2]> exit

How are you setting `CASROOT`? The test was passing as of Apr 22 and ran this command:

```
CASROOT=/usr/local/Cellar/oce/0.18_2/share/oce-0.18 DRAWEXE -v -c "pload ALL"
```

> I have CASROOT set and also DYLD_LIBRARY_PATH

Setting `DYLD_LIBRARY_PATH` is really not recommended and is a sign that there's something wrong with your installation.

> lDRAWEXE is not available in the installation

There's no library named `libDRAWEXE.dylib` in the installation. I looked at the `CMakeLists.txt` of `oce` and it doesn't seem like this is supposed to get built. I believe `DRAWEXE` is an executable so it doesn't really make sense to link against it. This sounds like something that you should report to the other library's authors.

**Comment by rajeeja** [comment] 2017-04-25 21:51
**Brew installed OCE**
==> ls /usr/local/Cellar/oce/0.18_2/lib/libTKDraw*
ls: /usr/local/Cellar/oce/0.18_2/lib/libTKDraw*: No such file or directory

**My own OCE using CMake**
~/install/oce/lib
==> ls libTKDraw.
libTKDraw.11.0.0.dylib  libTKDraw.11.dylib      libTKDraw.dylib

**Now CASROOT -** 
~/install/oce/lib
==> CASROOT=/usr/local/Cellar/oce/0.18_2/share/oce-0.18 DRAWEXE -v -c "pload ALL"
1
~/install/oce/lib
==> DRAWEXE
can't read "::env(CASROOT)": no such variable

**Comment by rajeeja** [comment] 2017-04-25 21:55
Ah I see there is folder in lib -
/usr/local/Cellar/oce/0.18_2/lib/oce-0.18
==> ls libTKDraw.
libTKDraw.11.0.0.dylib  libTKDraw.11.dylib      libTKDraw.dylib

**Why another folder one-0.18?**

**Comment by iMichka** [comment] 2017-04-28 22:01
I do not know why there is a `oce-0.18` subfolder, and I am not sure that it is directly due to homebrew.
Here is what is passed to cmake:

```
cmake . -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/oce/0.18_2 -DCMAKE_BUILD_TYPE=Release -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_VERBOSE_MAKEFILE=ON -Wno-dev -DOCE_INSTALL_PREFIX:STRING=/usr/local/Cellar/oce/0.18_2 -DOCE_COPY_HEADERS_BUILD:BOOL=ON -DOCE_DRAW:BOOL=ON -DOCE_MULTITHREAD_LIBRARY:STRING=TBB -DFREETYPE_INCLUDE_DIRS=/usr/local/opt/freetype/include/freetype2 -DOCE_WITH_FREEIMAGE:BOOL=ON -DOCE_WITH_GL2PS:BOOL=ON -DOCE_WITH_OPENCL:BOOL=ON -DOPENCL_LIBRARIES:PATH=/System/Library/Frameworks/OpenCL.framework -D_OPENCL_CPP_INCLUDE_DIRS:PATH=/System/Library/Frameworks/OpenCL.framework/Headers
```

You may play around and try to find out if you can reproduce this with your local build too. Or look at the CMakeList.txt file of the project, which probably says were stuff should be installed.

**Comment by iMichka** [comment] 2017-05-06 22:20
Closing here as this was just the wrong path used to link against the `libTKDraw.dylib` libraries.

**Closed by iMichka** 2017-05-06 22:20 UTC
