### ISSUE TITLE
arpack failed to built on OS X 10.11

### ISSUE THREAD

**Issue by colstat** [Homebrew/homebrew-science#3141] opened 2015-12-22 00:42 UTC
I am trying to install Octave 4.0 from source on El Capitan.

I am having trouble with arpack. 

I get the follow error:

    ./configure --prefix=/usr/local/Cellar/arpack/3.2.0/libexec --with-blas=-L/usr/local/opt/veclibfort/lib -lvecLibFort`
    checking whether make supports nested variables... yes
    checking whether to enable maintainer-specific portions of Makefiles... no
    checking whether the Fortran 77 compiler works... no`
    configure: error: in `/private/tmp/arpack20151221-8794-zw9q3a/arpack-ng-3.2.0':
    configure: error: Fortran 77 compiler cannot create executables
    See `config.log' for more details`

It is discussed on here before by installing XCode.  #2741 But, I already have XCode.

Here's the config.log,
https://gist.github.com/3001cc533d971a3bbc30

**Comment by dpo** [comment] 2015-12-22 00:48
It seems like you have a (possibly non-brewed) gcc/gfortran in /usr/local. It would be best if you could uninstall it. See what location [these libraries](https://gist.github.com/anonymous/3001cc533d971a3bbc30#file-00-doctor-out-L27) point to.

**Comment by colstat** [comment] 2015-12-22 00:52
Few weeks ago, I started using brew and Linux commands, could you give me specific instructions?  What should I do?

**Comment by Moisan** [comment] 2015-12-22 13:44
Start by following the directions gave by ``brew doctor``.

**Comment by dpo** [comment] 2015-12-22 16:41
Please post the output of `ls -l` on each of the libraries I pointed to above.

**Comment by colstat** [comment] 2015-12-22 21:22
@dpo I don't understand what you mean,

**Comment by dpo** [comment] 2015-12-22 22:10
What is the output of the following commands (type each one individually at the terminal command prompt):
```
ls -l /usr/local/lib/libgcc_s.1.dylib
ls -l /usr/local/lib/libgcc_s.10.4.dylib
ls -l /usr/local/lib/libgcc_s.10.5.dylib
ls -l /usr/local/lib/libgfortran.2.0.0.dylib
ls -l /usr/local/lib/libgsl.0.dylib
ls -l /usr/local/lib/libgslcblas.0.dylib
ls -l /usr/local/lib/libtcl8.6.dylib
ls -l /usr/local/lib/libtk8.6.dylib
```

**Comment by colstat** [comment] 2015-12-23 03:03
Here's the output

    Colins-MacBook-Air:octave-4.0.0 Colin$ ls -l /usr/local/lib/libgcc_s.1.dylib
    -rw-rw-r--  1 Colin  wheel  736903 Feb 24  2008 /usr/local/lib/libgcc_s.1.dylib
    Colins-MacBook-Air:octave-4.0.0 Colin$ ls -l /usr/local/lib/libgcc_s.10.4.dylib
    -rw-rw-r--  1 Colin  wheel  33144 Feb 24  2008 /usr/local/lib/libgcc_s.10.4.dylib
    Colins-MacBook-Air:octave-4.0.0 Colin$ ls -l /usr/local/lib/libgcc_s.10.5.dylib
    -rw-rw-r--  1 Colin  wheel  33508 Feb 24  2008 /usr/local/lib/libgcc_s.10.5.dylib
    Colins-MacBook-Air:octave-4.0.0 Colin$ ls -l /usr/local/lib/libgfortran.2.0.0.dylib
    -rwxrwxr-x  1 Colin  wheel  8094839 Feb 24  2008 /usr/local/lib/libgfortran.2.0.0.dylib
    Colins-MacBook-Air:octave-4.0.0 Colin$ ls -l /usr/local/lib/libgsl.0.dylib
    -rwxr-xr-x  1 Colin  wheel  2677312 Sep 18  2012 /usr/local/lib/libgsl.0.dylib
    Colins-MacBook-Air:octave-4.0.0 Colin$ ls -l /usr/local/lib/libgslcblas.0.dylib
    -rwxr-xr-x  1 Colin  wheel  268828 Sep 18  2012 /usr/local/lib/libgslcblas.0.dylib
    Colins-MacBook-Air:octave-4.0.0 Colin$ ls -l /usr/local/lib/libtcl8.6.dylib
    -r-xr-xr-x  1 Colin  wheel  1419604 Mar 29  2013 /usr/local/lib/libtcl8.6.dylib
    Colins-MacBook-Air:octave-4.0.0 Colin$ ls -l /usr/local/lib/libtk8.6.dylib
    -rwxr-xr-x  1 Colin  wheel  1239868 Mar 29  2013 /usr/local/lib/libtk8.6.dylib

**Comment by dpo** [comment] 2015-12-24 16:10
Do you remember how you installed `gcc`?

**Comment by colstat** [comment] 2015-12-24 16:36
I believed I have updated gcc for this installation.  What is wrong with my gcc?

**Comment by colstat** [comment] 2015-12-28 20:46
Anyone else have any ideas?

**Comment by dpo** [comment] 2015-12-28 21:07
Your current gcc wasn't installed with Homebrew and it's probably the cause of your troubles. I recommend asking someone around you to help you uninstall it.

**Comment by colstat** [comment] 2015-12-28 21:08
Thanks so much.  I will do that and let you know the result!

**Comment by colstat** [comment] 2015-12-28 23:29
Actually, I just checked.  This is what I get
   nat-tvwna-inside-visitornet101-c-23420:octave-4.0.0 $ brew install gcc
   Warning: gcc-5.3.0 already installed

**Comment by dpo** [comment] 2015-12-28 23:40
Perhaps, but you also seem to have another `gcc` installed. What is the output of `ls -l /usr/local/bin/gcc*`?

**Comment by colstat** [comment] 2015-12-28 23:43
This is the output:

    nat-tvwna-inside-visitornet101-c-23420:octave-4.0.0 Colin$ ls -l /usr/local/bin/gcc*
    lrwxr-xr-x  1 Colin  admin  29 Dec 18 13:27 /usr/local/bin/gcc-5 -> ../Cellar/gcc/5.3.0/bin/gcc-5
    lrwxr-xr-x  1 Colin  admin  32 Dec 18 13:27 /usr/local/bin/gcc-ar-5 -> ../Cellar/gcc/5.3.0/bin/gcc-ar-5
    lrwxr-xr-x  1 Colin  admin  32 Dec 18 13:27 /usr/local/bin/gcc-nm-5 -> ../Cellar/gcc/5.3.0/bin/gcc-nm-5
    lrwxr-xr-x  1 Colin  admin  36 Dec 18 13:27 /usr/local/bin/gcc-ranlib-5 -> ../Cellar/gcc/5.3.0/bin/gcc-ranlib-5

I really think the cause is, Mac El Capitan update screwed me up.  They changed /usr/bin folder to somewhere else.

**Comment by dpo** [comment] 2015-12-29 01:17
That looks ok, but the libraries [above](https://github.com/Homebrew/homebrew-science/issues/3141#issuecomment-166793841) appear to belong to another install of gcc. That's what should be uninstalled. For instance, my gcc libraries are in `/usr/local/lib/gcc/5` and nowhere else.

**Comment by colstat** [comment] 2015-12-29 01:20
Ok, let me dig in a little more and see how I can uninstall and install.

I have no idea what's gong on.  I am getting a bit frustrated at this point, it's like walking in a dark room trying find a light switch.

**Comment by dpo** [comment] 2015-12-29 22:45
`brew doctor` points to what may be going on. Unrecognized gcc libraries are a strong hint. You might have installed that gcc with MacPorts, or some other precompiled binaries, or even have compiled it yourself.

**Comment by mrscholz** [comment] 2016-02-09 07:12
I had a similar/ the same issue, at least `brew install octave` gave similar output as given by the TO. Also, I had the same output from `ls -l /usr/local/bin/gcc*`. Running `brew doctor` gave the hint: 

```
Warning:
You have unlinked kegs in your Cellar
Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
those kegs to fail to run properly once built. Run `brew link` on these:
    isl
    lua51
```

I just did as suggested and afterwards `brew install octave` worked like a charm. Hope this helps anyone having the same issue.

**Comment by colstat** [comment] 2016-02-09 13:34
There is no need, they've already put out tar.gz file for Octave 4.0+

**Comment by waitingkuo** [comment] 2016-03-26 09:33
I solved the issue by removing gfortran, gcc and install gcc back

    $ brew uninstall gfortran
    $ brew uninstall gcc
    $ brew install octave

**Comment by colstat** [comment] 2016-03-29 00:53
They have put out the dmg file about a week after I post this.  It's ready to install, there's no need for gcc or linux commands.

**Comment by dpo** [comment] 2016-04-01 20:14
I'll close this then. Please open a new issue if there are other problems.

**Closed by dpo** 2016-04-01 20:14 UTC
Labels: 10.11, user configuration

**Comment by mjdousti** [comment] 2016-04-10 01:08
This command solved my problem:
`brew link --overwrite gcc`
