### ISSUE TITLE
Probable gfortran error.

### ISSUE THREAD

**Issue by DomT4** [Homebrew/homebrew-science#2813] opened 2015-10-02 18:18 UTC
_From @mbarsacchi on October 2, 2015 18:10_

I've had some problems in installing veclibfort. 
I've posted it in Homebrew/homebrew-science but it seems to be related to gfortran.
```
$brew install veclibfor

...

make
check

gfortran -o tester -O tester.f90 vecLibFort.o -framework Accelerate
ld: framework not found Accelerate
collect2: error: ld returned 1 exit status
make: *** [check] Error 1
```

Here's the gist link.
https://gist.github.com/7e063ac3b14266dceef1

_Copied from original issue: Homebrew/homebrew#44536_

**Comment by dpo** [comment] 2015-10-02 18:37
Another dupe of #2802.

**Closed by dpo** 2015-10-02 18:37 UTC
