### ISSUE TITLE
harvest-tools 1.2 build failure - "Import failed: /capnp/c++.capnp" "Not defined: Cxx"

### ISSUE THREAD

**Issue by tseemann** [Homebrew/homebrew-science#2633] opened 2015-08-08 08:36 UTC
@iml - you recently patched this to 1.2 and now it fails for me on Linux.  

Here are the logs: https://gist.github.com/18c4cc29d87ccae7b618

./configure seems ok, but make failing:

```
/bio/linuxbrew/bin/gcc-5 -c -o src/harvest/memcpyWrap.o src/harvest/memcpyWrap.c
harvest.capnp:9:20-38: error: Import failed: /capnp/c++.capnp
harvest.capnp:10:2-5: error: Not defined: Cxx
make: *** [src/harvest/capnp/harvest.capnp.h] Error 1
make: *** Waiting for unfinished jobs....
harvest.capnp:9:20-38: error: Import failed: /capnp/c++.capnp
harvest.capnp:10:2-5: error: Not defined: Cxx
make: *** [src/harvest/capnp/harvest.capnp.c++] Error 1
```

**Comment by iml** [comment] 2015-08-09 00:35
This is caused by the updated capnp formula, it works after reverting to the previous non-cmake build.

**Comment by tseemann** [comment] 2015-10-03 06:14
I can confirm that `brew switch capnp 0.5.2` allows `harvest-tools 1.2` to build.

**Comment by user569** [comment] 2015-12-16 12:55
I'm having the same issue and cannot switch to capnp 0.5.2; it's not on homebrew/versions.

Any work around to get Harvest-tools to install?

**Comment by sjackman** [comment] 2016-03-09 19:15
I'm having the same issue trying to install `mash`.

**Comment by sjackman** [comment] 2016-03-09 19:39
To install `capnp` 0.5.2
```sh
brew install https://raw.githubusercontent.com/Linuxbrew/linuxbrew/8dd3478131b232553f4c0cab197f8443a0a559a6/Library/Formula/capnp.rb
```
Note that `make check` fails on CentOS 5.11 with Linux 2.6.18, but works with later kernels.

**Comment by sjackman** [comment] 2016-03-09 19:44
Because `capnp` is statically linked, you can switch back to the current release of `capnp` after you've installed `harvest-tools`.

**Comment by sjackman** [comment] 2016-07-30 14:36
@ondovb @aphillippy Any thoughts on resolving this `capnp` build error of `mash`?

**Comment by ondovb** [comment] 2016-08-02 22:39
This should be fixed in the latest harvest-tools source.

**Comment by Moisan** [comment] 2016-11-07 22:10
`harvest-tools` depends on `capnp` [which is currently broken](https://github.com/Homebrew/homebrew-core/issues/5435).

**Closed** 2017-11-24 05:13 UTC
Labels: Bioinformatics, build-error, help wanted
