### ISSUE TITLE
Octave 4.0 install from bottle can't find symbol from graphicsmagick library

### ISSUE THREAD

**Issue by ezemiron** [Homebrew/homebrew-science#2737] opened 2015-09-15 13:44 UTC
I have installed Octave 4.0 in OS X 10.9.5 which installs from maveriks bottle.
I am unable to use any of the image io functions. for example:

    > imread(path_to_file );
    error: default_formats: /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin13.4.0/__magick_read__.oct: failed to load: dlopen(/usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin13.4.0/__magick_read__.oct, 2): Symbol not found: __ZN6Magick5ColorC1Ehhh
      Referenced from: /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin13.4.0/__magick_read__.oct
      Expected in: /usr/local/lib/libGraphicsMagick++.11.dylib
     in /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin13.4.0/__magick_read__.oct
    error: called from
        imformats>default_formats at line 256 column 11
        imformats at line 79 column 3
        imageIO at line 106 column 11
        imread at line 106 column 30

I have run brew update for all the recipes and reinstalled graphicsmagick from where that symbol should come from.

    $ otool -L /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin13.4.0/__magick_read__.oct 
    /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin13.4.0/__magick_read__.oct:
    [...]
            /usr/local/lib/libGraphicsMagick++.11.dylib (compatibility version 12.0.0, current version 12.0.0)
            /usr/local/lib/libGraphicsMagick.3.dylib (compatibility version 17.0.0, current version 17.0.0)
     [...]
    $ nm -gU  /usr/local/Cellar/graphicsmagick/1.3.21/lib/libGraphicsMagick.3.dylib | grep 5ColorC1E    
    $ nm -gU  /usr/local/Cellar/graphicsmagick/1.3.21/lib/libGraphicsMagick++.11.dylib | grep 5ColorC1E
    0000000000004558 T __ZN6Magick5ColorC1EPKc
    00000000000046be T __ZN6Magick5ColorC1EPN9MagickLib12_PixelPacketENS0_9PixelTypeE
    0000000000004666 T __ZN6Magick5ColorC1ERKN9MagickLib12_PixelPacketE
    00000000000043f8 T __ZN6Magick5ColorC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
    000000000000436c T __ZN6Magick5ColorC1ERKS0_
    00000000000041e8 T __ZN6Magick5ColorC1Ettt
    00000000000042a0 T __ZN6Magick5ColorC1Etttt
    0000000000004160 T __ZN6Magick5ColorC1Ev

**Comment by dpo** [comment] 2015-09-15 15:32
That's odd. Here's what I have:
```
$ nm libGraphicsMagick++.11.dylib | grep __ZN6Magick5ColorC1Ehhh
0000000000003f0c T __ZN6Magick5ColorC1Ehhh
0000000000003fc4 T __ZN6Magick5ColorC1Ehhhh
```
I'm also on Mavericks. Could you try `brew uninstall $(brew deps octave)` followed by `brew reinstall octave`?

**Comment by ezemiron** [comment] 2015-09-15 17:47
No, that does not solve the issue. 
I can see graphicsmagick installed as a dep upon reinstallation, but I get the same error and the symbols with "...5ColorC1Ettt /tttt/ v " instead of the hhh hhhh its looking for (and you have).

As a note, when uninstalling brew deps octave I also observed the following missing deps:

    Error: No such keg: /usr/local/Cellar/d-bus
    Error: No such keg: /usr/local/Cellar/giflib
    Error: No such keg: /usr/local/Cellar/graphite2
    Error: No such keg: /usr/local/Cellar/ilmbase
    Error: No such keg: /usr/local/Cellar/intltool
    Error: No such keg: /usr/local/Cellar/jasper
    Error: No such keg: /usr/local/Cellar/libcroco
    Error: No such keg: /usr/local/Cellar/libgsf
    Error: No such keg: /usr/local/Cellar/liblqr
    Error: No such keg: /usr/local/Cellar/librsvg
    Error: No such keg: /usr/local/Cellar/libvpx
    Error: No such keg: /usr/local/Cellar/libwmf
    Error: No such keg: /usr/local/Cellar/little-cms
    Error: No such keg: /usr/local/Cellar/makedepend
    Error: No such keg: /usr/local/Cellar/metis4
    Error: No such keg: /usr/local/Cellar/mysql
    Error: No such keg: /usr/local/Cellar/open-mpi
    Error: No such keg: /usr/local/Cellar/openblas
    Error: No such keg: /usr/local/Cellar/openexr
    Error: No such keg: /usr/local/Cellar/pdflib-lite
    Error: No such keg: /usr/local/Cellar/postgresql
    Error: No such keg: /usr/local/Cellar/webp
    Error: No such keg: /usr/local/Cellar/wxmac
    Error: No such keg: /usr/local/Cellar/yasm

Though I don't believe this is the cause of the issue

**Comment by dpo** [comment] 2015-09-15 20:13
Does `brew doctor` say anything?

**Comment by ezemiron** [comment] 2015-09-17 15:27
brew doctor 
says the following:

    Warning: Some directories in /usr/local/share/man aren't writable.
    This can happen if you "sudo make install" software that isn't managed
    by Homebrew. If a brew tries to add locale information to one of these
    directories, then the install will fail during the link step.
    You should probably `chown` them:
        /usr/local/share/man/de
        /usr/local/share/man/de/man1
        /usr/local/share/man/mann

    Warning: Unbrewed dylibs were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected dylibs:
    /usr/local/lib/libtcl8.6.dylib
    /usr/local/lib/libtk8.6.dylib

    Warning: Unbrewed header files were found in /usr/local/include.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected header files:
        /usr/local/include/fakemysql.h
        /usr/local/include/fakepq.h
        /usr/local/include/fakesql.h
        /usr/local/include/itcl.h
        /usr/local/include/itcl2TclOO.h
        /usr/local/include/itclDecls.h
        /usr/local/include/itclInt.h
        /usr/local/include/itclIntDecls.h
        /usr/local/include/itclMigrate2TclCore.h
        /usr/local/include/itclTclIntStubsFcn.h
        /usr/local/include/mysqlStubs.h
        /usr/local/include/odbcStubs.h
        /usr/local/include/pqStubs.h
        /usr/local/include/tcl.h
        /usr/local/include/tclDecls.h
        /usr/local/include/tclOO.h
        /usr/local/include/tclOODecls.h
        /usr/local/include/tclPlatDecls.h
        /usr/local/include/tclThread.h
        /usr/local/include/tclTomMath.h
        /usr/local/include/tclTomMathDecls.h
        /usr/local/include/tdbc.h
        /usr/local/include/tdbcDecls.h
        /usr/local/include/tdbcInt.h
        /usr/local/include/tk.h
        /usr/local/include/tkDecls.h
        /usr/local/include/tkPlatDecls.h
        /usr/local/include/ublio.h

    Warning: Unbrewed .pc files were found in /usr/local/lib/pkgconfig.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected .pc files:
        /usr/local/lib/pkgconfig/tcl.pc
        /usr/local/lib/pkgconfig/tk.pc

    Warning: Unbrewed static libraries were found in /usr/local/lib.
    If you didn't put them there on purpose they could cause problems when
    building Homebrew formulae, and may need to be deleted.

    Unexpected static libraries:
        /usr/local/lib/libtclstub8.6.a
        /usr/local/lib/libtkstub8.6.a

    Warning: You have unlinked kegs in your Cellar
    Leaving kegs unlinked can lead to build-trouble and cause brews that depend on
    those kegs to fail to run properly once built. Run `brew link` on these:
        pyqt

    Warning: Homebrew's sbin was not found in your PATH but you have installed
    formulae that put executables in /usr/local/sbin.
    Consider setting the PATH for example like so
        echo 'export PATH="/usr/local/sbin:$PATH"' >> ~/.bash_profile

    Warning: Your Xcode (5.1.1) is outdated
    Please update to Xcode 6.4.
    Xcode can be updated from the App Store.

I have now upgraded to 10.10 and am running the latest Xcode version. I have also done  brew uninstall $(brew deps octave) followed by brew reinstall octave (now from Yosemite bottle
but I have the same issue as before

    > imread(path_to_file );
    error: default_formats: /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin14.5.0/__magick_read__.oct: failed to load: dlopen(/usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin14.5.0/__magick_read__.oct, 2): Symbol not found: __ZN6Magick5ColorC1Ehhh
      Referenced from: /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin14.5.0/__magick_read__.oct
      Expected in: /usr/local/lib/libGraphicsMagick++.11.dylib
     in /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/oct/x86_64-apple-darwin14.5.0/__magick_read__.oct
    error: called from
        imformats>default_formats at line 256 column 11
        imformats at line 79 column 3
        imageIO at line 106 column 11
        imread at line 106 column 30


    $ nm -gU  /usr/local/Cellar/graphicsmagick/1.3.21/lib/libGraphicsMagick++.11.dylib | grep 5ColorC1E
    0000000000004558 T __ZN6Magick5ColorC1EPKc
    00000000000046be T __ZN6Magick5ColorC1EPN9MagickLib12_PixelPacketENS0_9PixelTypeE
    0000000000004666 T __ZN6Magick5ColorC1ERKN9MagickLib12_PixelPacketE
    00000000000043f8 T __ZN6Magick5ColorC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
    000000000000436c T __ZN6Magick5ColorC1ERKS0_
    00000000000041e8 T __ZN6Magick5ColorC1Ettt
    00000000000042a0 T __ZN6Magick5ColorC1Etttt
    0000000000004160 T __ZN6Magick5ColorC1Ev

**Comment by dpo** [comment] 2015-09-18 00:21
Maybe @schoeps will have an idea.

**Comment by schoeps** [comment] 2015-09-18 06:24
Can you try as a first step to compile octave and graphicsmagic freshly from sources, i.e., with "--build-from-source"?

(be aware that there is a brand new xcode since a fee days. I had to xcode-select --install again)

**Comment by ezemiron** [comment] 2015-09-29 17:27
Building with "--build-from-source" fixes the issue.
But reinstalling from the yosemite bottle breaks again identically.
I have one more system where I can reproduce this issue. 

Is there anything I can do to help fix this?

**Comment by schoeps** [comment] 2015-09-30 17:41
@ezemiron: Not really sure. Let's try if this gives an explanation: can you compare the output of `otool -L /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/liboctave.dylib` of the bottled and self compiled version?

**Comment by ezemiron** [comment] 2015-10-01 13:13
For the self compiled version:

    $ otool -L /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/liboctave.dylib
    /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/liboctave.dylib:
	    /usr/local/lib/octave/4.0.0/liboctave.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	    /System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM (compatibility version 1.0.0, current version 1.0.0)
	    /usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	    /usr/local/opt/arpack/libexec/lib/libarpack.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	    /usr/local/lib/libqrupdate.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	    /usr/local/lib/libfftw3_threads.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	    /usr/local/lib/libfftw3.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	    /usr/local/lib/libfftw3f_threads.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	    /usr/local/lib/libfftw3f.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	    /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib (compatibility version 1.0.0, current version 1.0.0)
	    /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	    /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	    /usr/local/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.5.0)
	    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	    /usr/local/opt/readline/lib/libreadline.6.dylib (compatibility version 6.0.0, current version 6.3.0)
	    /usr/local/lib/gcc/5/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	    /usr/local/lib/gcc/5/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)

For the bottled version:

    $ otool -L /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/liboctave.dylib
    /usr/local/Cellar/octave/4.0.0/lib/octave/4.0.0/liboctave.dylib:
	    /usr/local/lib/octave/4.0.0/liboctave.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	    /System/Library/Frameworks/JavaVM.framework/Versions/A/JavaVM (compatibility version 1.0.0, current version 1.0.0)
	    /usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
	    /usr/local/opt/arpack/libexec/lib/libarpack.2.dylib (compatibility version 3.0.0, current version 3.0.0)
	    /usr/local/lib/libqrupdate.1.dylib (compatibility version 0.0.0, current version 0.0.0)
	    /usr/local/lib/libfftw3_threads.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	    /usr/local/lib/libfftw3.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	    /usr/local/lib/libfftw3f_threads.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	    /usr/local/lib/libfftw3f.3.dylib (compatibility version 8.0.0, current version 8.4.0)
	    /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libLAPACK.dylib (compatibility version 1.0.0, current version 1.0.0)
	    /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib (compatibility version 1.0.0, current version 1.0.0)
	    /usr/lib/libncurses.5.4.dylib (compatibility version 5.4.0, current version 5.4.0)
	    /usr/local/lib/libpcre.1.dylib (compatibility version 4.0.0, current version 4.5.0)
	    /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1213.0.0)
	    /usr/local/opt/readline/lib/libreadline.6.dylib (compatibility version 6.0.0, current version 6.3.0)
	    /usr/local/lib/gcc/5/libgfortran.3.dylib (compatibility version 4.0.0, current version 4.0.0)
	    /usr/local/lib/gcc/5/libquadmath.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	    /usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 120.0.0)

The outputs seem the same to me.

Also, I have not knowingly disabled any features of graphicsmagick.

**Comment by schoeps** [comment] 2015-10-01 14:18
Sorry, the otool output for liboctave was not very helpful since the problem occured in __magick_read__.oct. Did you recompile GraphicsMagick and octave? or just one?

I checked my libGraphicsMagick and indeed I have the symbol that you were missing:
```
nm -gU  /usr/local/Cellar/graphicsmagick/1.3.21/lib/libGraphicsMagick++.11.dylib | grep 5ColorC1E
0000000000004950 T __ZN6Magick5ColorC1EPKc
0000000000004a10 T __ZN6Magick5ColorC1EPN9MagickLib12_PixelPacketENS0_9PixelTypeE
00000000000049e6 T __ZN6Magick5ColorC1ERKN9MagickLib12_PixelPacketE
0000000000004850 T __ZN6Magick5ColorC1ERKNSt3__112basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE
0000000000004714 T __ZN6Magick5ColorC1ERKS0_
00000000000045b6 T __ZN6Magick5ColorC1Ehhh
000000000000466e T __ZN6Magick5ColorC1Ehhhh
0000000000004522 T __ZN6Magick5ColorC1Ev
```

**Comment by ezemiron** [comment] 2015-10-01 14:48
I have reinstalled graphicsmagick with homebrew also, but I do not get the missing symbols.

**Comment by dpo** [comment] 2015-10-01 16:38
[Here](https://github.com/Homebrew/homebrew-science/issues/2737#issuecomment-144128470) you mention the Yosemite bottle, but in your initial post, you stated that you are on Mavericks. Which one is it?

**Comment by ezemiron** [comment] 2015-10-01 16:45
I upgraded to Yosemite as the newer version of Xcode was not available for mavericks. Here, at the end of the previous post:
https://github.com/Homebrew/homebrew-science/issues/2737#issuecomment-141122206

**Comment by ezemiron** [comment] 2015-10-06 12:19
To recap, I started with this issue in Maveriks. A warning from "brew doctor" prompted me to update Xcode, but I had to upgrade to Yosemite to get this from the App store. After the upgrade and update the issue was still not solved when building with the Yosemite bottle, but I was able to fix it when I tried "--build-from-source".

**Comment by nadeemyasin61** [comment] 2015-10-21 14:09
+1 having same issue.
@ezemiron can you please put down the complete command here?

**Comment by dpo** [comment] 2015-10-21 14:24
I could suggest the drastic method:
```
brew uninstall -f $(brew deps octave)
brew install octave [with-options-you-want]
```
Does that resolve it?

**Comment by nadeemyasin61** [comment] 2015-10-21 14:33
Thanks @dpo 

Here is the output

``$ brew install octave --build-from-source``

``Warning: homebrew/science/octave-4.0.0_1 already installed``

**Comment by nadeemyasin61** [comment] 2015-10-21 14:44
@dpo Just did another clean install. But looks like same error. Can you recommend something else?
```
octave:1> ap1 = imread('img.pgm');
error: default_formats: /usr/local/Cellar/octave/4.0.0_1/lib/octave/4.0.0/oct/x86_64-apple-darwin14.5.0/__magick_read__.oct: failed to load: 
dlopen(/usr/local/Cellar/octave/4.0.0_1/lib/octave/4.0.0/oct/x86_64-apple-darwin14.5.0/__magick_read__.oct, 2): 
Library not loaded: /usr/local/lib/libGraphicsMagick++.11.dylib
```

**Comment by schoeps** [comment] 2015-10-21 14:45
What gives `ls /usr/local/lib/libGraphicsMagick*`?

**Comment by nadeemyasin61** [comment] 2015-10-21 14:48
```
$ ls /usr/local/lib/libGraphicsMagick*
/usr/local/lib/libGraphicsMagick++.12.dylib	
/usr/local/lib/libGraphicsMagick.3.dylib	
/usr/local/lib/libGraphicsMagickWand.2.dylib
/usr/local/lib/libGraphicsMagick++.dylib	
/usr/local/lib/libGraphicsMagick.dylib		
/usr/local/lib/libGraphicsMagickWand.dylib
/usr/local/lib/libGraphicsMagick++.la		
/usr/local/lib/libGraphicsMagick.la		
/usr/local/lib/libGraphicsMagickWand.la
```
Looks like libGraphicsMagick++.11.dylib is missing.

**Comment by dpo** [comment] 2015-10-21 14:49
Are you installing `graphicsmagicks` from a bottle? Could you try it with `--build-from-source` before reinstalling `octave`?

**Comment by schoeps** [comment] 2015-10-21 14:50
@dpo: Octave seems to link to libGraphicsMagick++.11.dylib instead of libGraphicsMagick++.dylib and this is not available with version 12...

**Comment by nadeemyasin61** [comment] 2015-10-21 15:00
@dpo Can you suggest some command to install graphicsmagicks with ``--build-from-source`` ? I am not sure how did i installed it, probably as a part of imagemagick, and i installed imagemagick using ``homebrew``

@schoeps sounds logical. Octave 4 is tied to 11.dylib and not with the latest one, probably.

**Comment by nadeemyasin61** [comment] 2015-10-21 15:09
Just reinstalled the MagickGraphics from source. But,

```
$ ls /usr/local/lib/libGraphicsMagick*
```
Showing the same output. 11.dylib is still missing. 

```
/usr/local/lib/libGraphicsMagick++.12.dylib	
/usr/local/lib/libGraphicsMagick.3.dylib	
/usr/local/lib/libGraphicsMagickWand.2.dylib
/usr/local/lib/libGraphicsMagick++.dylib	
/usr/local/lib/libGraphicsMagick.dylib		
/usr/local/lib/libGraphicsMagickWand.dylib
/usr/local/lib/libGraphicsMagick++.la		
/usr/local/lib/libGraphicsMagick.la		
/usr/local/lib/libGraphicsMagickWand.la
```

Any recommendations?

**Comment by schoeps** [comment] 2015-10-21 15:11
If you compile octave from source it will graciously take the available libGraphicsMagick: `brew install octave --build-from-source`

**Comment by dpo** [comment] 2015-10-21 15:21
Yes, that was my suggestion.

**Comment by schoeps** [comment] 2015-10-21 15:32
anyway, this problem should disappear soon since a new revision of the octave formula is waiting for merge (and this will hopefully be compiled using a GraphicsMagick 12).

**Comment by nadeemyasin61** [comment] 2015-10-21 15:37
Guys, your support is much appreciated. 
building octave with srouce is pretty good, but just gave out an error in the end. 

```
configure: error: A BLAS library was detected but found incompatible with your Fortran 77 compiler settings.
```
my gcc is up to date.

**Comment by nadeemyasin61** [comment] 2015-10-21 15:54
@dpo not sure if its relevant here. But wanted to share the failure logs where i am stuck on.
Do i need to reinstall some BLAS?

```

checking whether LSAME is called correctly from Fortran... yes
checking whether ISAMAX is called correctly from Fortran... yes
checking whether SDOT is called correctly from Fortran... no
checking whether DDOT is called correctly from Fortran... no
checking whether CDOTU is called correctly from Fortran... no
checking whether ZDOTU is called correctly from Fortran... no
checking whether the integer size is correct... no
configure: error: A BLAS library was detected but found incompatible with your Fortran 77 compiler settings.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues

```

**Comment by schoeps** [comment] 2015-10-21 15:58
Last thing I can do today: try `brew install octave --build-from-source --with-openblas` if you have compiled also other codes with openblas

**Comment by carandraug** [comment] 2015-11-21 17:38
I believe to know what the issue is. This is the same as [launchpad bug #1372202](https://bugs.launchpad.net/ubuntu/+source/octave/+bug/1372202). In @ezemiron 's system, he installed GraphicsMagick with quantum depth 16 (I will guess that when re-installing all the dependencies, homebrew remembers previous options) but Octave's bottle was built against GraphicsMagick with quantum depth 8. This explains why building Octave from source fixes it.

The solution is that Octave's recipe must check GraphicsMagick quantum depth and default to build from source unless it matches the one expected. To get the quantum depth from the `gm` the following can be used:

    $ gm -version | head -n 1 | grep -Po '(?<=Q)\d+'
    16
    $ gm -version | grep -Po '(?<=--with-quantum-depth=)\d+'
    16

I think the last one may be best. I'm not sure Apple's grep has perl regex support, but I'll guess that even Apple will accept this alternative:

    $ gm -version | grep -Eo -e '--with-quantum-depth=[0-9]+' | grep -Eo -e '[0-9]+'
    16

A possible better alternative, to guard against corner cases such as GraphicsMagick built with options that change its executable name (I think there's a imagemagick compatibility option for that) or a change on the format of `gm -version` is to have the recipe build a small program that simply prints the quantum depth (octave's configure used to this):

    $ cat say-gm-quantum-depth.cc 
    #include <iostream>
    #include <Magick++.h>
    
    int
    main ()
    {
      std::cout << QuantumDepth << std::endl;
      return 0;
    }
$ g++ -L/usr/local/lib -I/usr/local/include/GraphicsMagick -lGraphicsMagick -o say-gm-quantum-depth say-gm-quantum-depth.cc 
$ ./say-gm-quantum-depth 
16

**Comment by carandraug** [comment] 2015-11-21 17:45
On a related note, see discussion on issue homebrew/homebrew#46101 and pull request homebrew/homebrew#46248 to change the default quantum depth of GraphicsMagick.

**Comment by schoeps** [comment] 2015-11-22 12:24
I don't think a formula can decide to not use its binary. However, I  could recommend to install GraphicsMagickwith Depth 16 in octave.rb, e.g. https://raw.githubusercontent.com/schoeps/homebrew-science/a687f74f59f8359cf6b4b6fb65dfda42263a4749/octave.rb

I do not have to check as you did above since I can ask homebrew which installation options were used to install an arbitary package. I could exit the installation of octave with an appropriate error message...

**Comment by carandraug** [comment] 2015-12-15 16:06
Speaking with @tdsmith on IRC, I was told how to code logic that will skip the bottle.

The answer is overloading [`pour_bottle?`](http://www.rubydoc.info/github/Homebrew/homebrew/master/Formula#pour_bottle%3F-instance_method) to return false if for some reason we want to force `--build-from-source`.

> tdsmith: you ~could~ define a pour_bottle? method on the Formula that creates a Tab object like `Tab.for_name("homebrew/dupes/tcl-tk")`, which has the same methods as `build`, so you can see what it was built with
> tdsmith: i don't know a really nice way to determine if the defaults are default or not
> tdsmith: you could check whether it was poured from a bottle or not
> tdsmith: and build from source if the dependency wasn't poured from a bottle
> tdsmith: think that's Tab#poured_from_bottle?
>
> carandraug: checking if the dependency was poured from a bottle would leave to false positives. I mean tha's not so important, forcing build-from-source will always work but if I can guess better...
>
> tdsmith: but then the second formula has to be updated if the defaults change in the first

If my understanding of ruby and homebrew is correct, this would mean adding something like this to the octave Formula:

      def pour_bottle?
        # https://github.com/Homebrew/homebrew-science/issues/2737
        Tab.for_formula("graphicsmagick").bottle?
      end

The main implication of the above is that it may trigger a build from source in cases where graphicsmagick was built from source despite not changing the quantum-depth (for example, building graphicsmagick with support for extra file formats).

**Comment by schoeps** [comment] 2015-12-15 20:48
@carandraug: do you propose this for octave? Once the changes in homebrew are accepted, we could just increase the revision of the octave formula? (I would like to make a new revision anyway using some recent fixes)

**Comment by carandraug** [comment] 2015-12-16 12:44
> do you propose this for octave?

Yes

> Once the changes in homebrew are accepted, we could just increase the revision of the octave formula? (I would like to make a new revision anyway using some recent fixes) 

But increasing the revision won't fix cases where the users still change gm's quantum depth (or are you changing something else?). At the moment, the problem are users building gm from source with quantum-depth 16. But there are cases where the user will want to have quantum depth 32 (for very special images such as DNA microarrays) or even go back to 8 (it does have the advantage of smaller memory usage and so it's valuable for ridiculously large images or systems with reduced memory).

**Comment by schoeps** [comment] 2015-12-16 13:10
True. I was not aware that you want to keep that hight level of flexibility. Most ports just force a particular variant of their dependencies. I assumed that you were aiming for depth 16 everywhere.

**Comment by carandraug** [comment] 2015-12-22 01:47
Homebrew/homebrew#46248 (change graphicsmagick default quantum depth to 16) and Homebrew/homebrew#47017 (change libtiff dependency to recommended) fixed, applied, and closed, and with #3123 fixed (bumped octave revision number), this should also be fixed.

@ezemiron you should no longer have any issue (or any reason to rebuild graphicsmagick from source). Does octave's `imread` works fine after the following?

    brew uninstall octave graphicsmagick
    brew install octave

Still, to avoid it from happening again, something more should be done. @schoeps should I submit a pull request with https://github.com/carandraug/homebrew-science.git octave-gm-incompatible-bottle branch ? I think that the flexibility proposed is a nice thing, and does not add much complexity.

**Comment by schoeps** [comment] 2015-12-22 09:10
@carne can you post a link to the patch? I am preparing a new octave formula release (with some gui patches) and I could incorporate your proposal. Alternatively, you just make a pull request and I will look at it.

**Comment by carandraug** [comment] 2015-12-22 17:10
The cset is carandraug/homebrew-science@a9614acdbe469a3dd9ec055120c6f133e9d8fe85

Alternatively, since the discussion already happened all here, github used to support something like this (to transform this issue on a pull request from my branch)

    curl --user "schoeps" --request POST --data '{"issue":"2737","head":"carandraug:octave-gm-incompatible-bottle","base":"master"}' https://api.github.com/repos/Homebrew/homebrew-science/pulls

**Comment by schoeps** [comment] 2015-12-23 16:36
@carandraug: I would prefer to check the install options... what about this changeset?

https://github.com/schoeps/homebrew-science/blob/octave4r3/octave.rb

**Comment by carandraug** [comment] 2015-12-23 17:09
@schoeps on the case of graphicsmagick, it seems odd to check what it shouldn't be instead of checking what it should be. But I guess homebrew does not allow to simply query `with? "quantum-depth-16"` which would be a lot more natural.

Also, this looks cleaner and less repetitive to me:

    ["arpack", "qrupdate", "suite-sparse421"].all? {|n| Tab.for_name(n).with? "openblas"}

**Comment by schoeps** [comment] 2015-12-23 18:07
@carandraug: you may recall that I suggested the strange syntax "--without-depth-16 --with-depth-n" to install graphicsmagick with a non-standard depth? That was exactly the reason... if you now install without any parameters homebrew does *not* set "--with-depth-16". Therefore we cannot check for it.

Regarding your code: it is obviously much more elegant. I am still a lousy ruby programmer :) New version at https://github.com/schoeps/homebrew-science/blob/octave4r3/octave.rb

**Comment by carandraug** [comment] 2015-12-23 20:08
> you may recall that I suggested the strange syntax "--without-depth-16 --with-depth-n" to install graphicsmagick with a non-standard depth? That was exactly the reason... 

Ah! Yes, I recall that. At the time I didn't understood what you meant.

It still looks like a limitation of the framework to me, but I don't know how to do any better either.

**Comment by dpo** [comment] 2016-05-20 13:31
I'll close this because `octave` was updated recently. Please open a new issue if problems persist.

**Closed by dpo** 2016-05-20 13:31 UTC
