### ISSUE TITLE
Open cv gives incorrect instructions when using `--with-python3` option

### ISSUE THREAD

**Issue by NickRSearcy** [Homebrew/homebrew-science#2665] opened 2015-08-18 17:34 UTC
After installing opencv3 using the command `brew install opencv3 --with-python3` homebrew provides the following instructions:

```
If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth
```

This is fine if you want to be able to `import cv2` in python2.7 but not if you want to `import cv2` in python3.4. The instructions *should* be responsive to the `--with-python3` flag as follows:

```
If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/opencv3/lib/python3.4/site-packages >> /usr/local/lib/python3.4/site-packages/opencv3.pth
```

I can't find where the instructions come from (looks like not the opencv3.rb) but this could easily be fixed by inserting an if statement and/or replacing the version text with `#{py3_version}`. If someone can tell me where I should do this, I'd be happy to submit a pull request.

**Comment by tdsmith** [comment] 2015-08-18 20:59
The python2 bindings are always built, so message that you saw is correct but incomplete. I agree that we should also print a message for python3 bindings. The check is in Library/Homebrew/caveats.rb.

**Comment by SamusAranX** [comment] 2016-01-30 14:58
Sorry for digging this back up, but I just ran into the same problem. I tried to install opencv3 for use with Python 3.5.1 using `brew install opencv3 --c++11 --with-contrib --with-cuda --with-ffmpeg --with-python3 --with-tbb` and all I got was

`If you need Python to find bindings for this keg-only formula, run:`
`  echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth`
`  mkdir -p /Users/peterwunder/Library/Python/2.7/lib/python/site-packages`
`  echo 'import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")' >> /Users/peterwunder/Library/Python/2.7/lib/python/site-packages/homebrew.pth`

I checked `/usr/local/opt/opencv3/lib/` but there's no python3* folder there, just a python2.7 one that's useless to me. Additionally, my Python 3 resides at `/Library/Frameworks/Python.framework/Versions/3.5/bin/python3` and apparently I'm literally the only person on planet Earth with that setup. What do I do?

**Comment by neil-tan** [comment] 2016-03-14 10:52
It seems to be caused by a dirty python environment.
My python3 was installed under pyenv. In my case, this line of the formula is problematic:
"-DPYTHON3_LIBRARY=#{py3_config}/libpython#{py3_version}.#{dylib}"
As the the library file ends with .a instead of .dylib. There is probably something odd with my pyenv installation.

Reinstalling python helped. Here is what I did:
Uninstalling all versions of python (pyenv, pyenv, virtualenv and brew's) except for the system python.
Clearing homebrew's cache.
brew install python3
brew install opencv3  [options]
followed by, ln -s /usr/local/opt/opencv3/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so /usr/local/lib/python3.5/site-packages/cv2.so

**Comment by Hey-Red-Chan** [comment] 2016-10-23 07:12
@SamusAranX 
Sorry for digging AGAIN.
Also feel happy that finally someone has exactly the same problem with me. I didn't find python3* folder in  /usr/local/opt/opencv3/lib/ either. I created one and copied the folders in python2.7 into python3* but failed.
Will be thankful if you can tell me how you solve it

**Comment by tdsmith** [comment] 2016-10-23 17:08
That's not a related problem. I'll close this since there is no bug here.

If you are having trouble building the python3 modules, which is distinct from failing to get a message about how to use them, please open a new ticket with the output of `brew gist-logs opencv3`.

**Closed by tdsmith** 2016-10-23 17:08 UTC
