### ISSUE TITLE
bowtie creates output files filled with zeros

### ISSUE THREAD

**Issue by maximilianh** [Homebrew/homebrew-science#4110] opened 2016-08-25 12:42 UTC
### Indicate troubleshooting steps taken
- [X ] Ran `brew update` and retried your prior step?
- [X ] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [X ] Checked that a similar issue hasn't already been filed?
- [X ] Looked up the software bug tracker if reporting a build error?
- [X ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
### Bug reports / build errors:
- Brief summary of issue: bowtie creates binary output files with the --refout option
  see https://github.com/BenLangmead/bowtie/issues/26
- Please state the complete command that you issued. /usr/local/bin/bowtie /usr/local/share/bowtie/indexes/e_coli /usr/local/share/bowtie/reads/e_coli_1000.fq --refout

This creates a file ref00000.map which is binary. When I recompile bowtie from source myself, the first line of the file looks like this instead:
r0  -   gi|110640213|ref|NC_008253.1|   3658049 ATGCTGGAATGGCGATAGTTGGGTGGGTATCGTTC 45567778999:9;;<===>?@@@@AAAABCCCDE 0   32:T>G,34:G>A

**Comment by tdsmith** [comment] 2016-08-30 04:43
Unless this is caused by https://github.com/BenLangmead/bowtie/pull/25 (plausible) I don't think this is a Homebrew bug. If you apply that patch before building from source do you see the same failure mode?

**Comment by iMichka** [comment] 2017-02-17 21:22
This was maybe fixed in homebrew by 1e68a7081ce66dadc481e70a7bf2605999d9bdc2
Bowtie 1.2.0 contains the fix, we will upgrade to that version soon: #5156

Closing here. Once bowtie 1.2.0 is added to homebrew, please upgrade, and open a new issue if you still encounter problems. Thanks.

**Closed by iMichka** 2017-02-17 21:22 UTC
Labels: needs response
