### ISSUE TITLE
Could you help fix homebrew-science/pymol.rb?

### ISSUE THREAD

**Issue by zhujianwei31415** [Homebrew/homebrew-science#5696] opened 2017-05-12 14:32 UTC
The old pymol.rb is dependent on "homebrew/dupes/tcl-tk", but "homebrew/dupes/tcl-tk" is deprecated and the new dependency is tcl-tk. The pymol will crash once I type pymol on command line.

Could you update the pymol to latest version 1.8.6 and fix the dependency on tcl-tk?

Thank you!

**Comment by iMichka** [comment] 2017-05-12 21:30
Closing as duplicate of #5505

**Closed by iMichka** 2017-05-12 21:30 UTC
