### ISSUE TITLE
brew install hdf5 --with-fortran fails

### ISSUE THREAD

**Issue by oliviermarti** [Homebrew/homebrew-science#5973] opened 2017-07-17 08:27 UTC
Hi,

I can't install hdf5 with fortran support. Could you help ? Details following.

Best regards,

Olivier

### Troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [x] Looked up the software bug tracker if reporting a build error?
- [x] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?
All OK

### Bug reports / build errors:
```
user@Computer-~ 👉  brew install hdf5 --with-fortran
==> Using the sandbox
==> Using Homebrew-provided fortran compiler.
This may be changed by setting the FC environment variable.
==> Downloading https://www.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.1/src/hdf5-1.10.1.tar.bz2
Already downloaded: /Users/marti/Library/Caches/Homebrew/hdf5-1.10.1.tar.bz2
==> autoreconf -fiv
==> ./configure --disable-silent-rules --prefix=/usr/local/Cellar/hdf5/1.10.1 --with-szlib=/usr/local/opt/szip --enable-build-mode=production --disable-cxx --enable-fortran
==> make install
Last 15 lines from /Users/marti/Library/Logs/Homebrew/hdf5/03.make:
Error: Function 'buf' at (1) has no IMPLICIT type
H5_gen.F90:422:18:

     f_ptr = C_LOC(buf(1))
                  1
Warning: Procedure 'buf' called with an implicit interface at (1) [-Wimplicit-interface]
H5_gen.F90:422:18:

     f_ptr = C_LOC(buf(1))
                  1
Error: Function 'buf' at (1) has no IMPLICIT type
make[3]: *** [H5_gen.lo] Error 1
make[2]: *** [install] Error 2
make[1]: *** [install-recursive] Error 1
make: *** [install-recursive] Error 1

READ THIS: http://docs.brew.sh/Troubleshooting.html
```

#### Brief summary of issue:
hdf5 --with-fortran does not compile

#### The complete command that you issued:
`brew install hdf5 --with-fortran`

Because installing netcdf --with-fortran fails, and I wanted to reinstall some deps properly.
Note that hdf5 without fortran installs nicely.

#### Link output by `brew gist-logs <formula>`:
[https://gist.github.com/98787bea9f5c7dbfb5149be358394756](https://gist.github.com/98787bea9f5c7dbfb5149be358394756
)
#### Output of `brew config`:
```
HOMEBREW_VERSION: 1.2.4
ORIGIN: https://github.com/Homebrew/brew.git
HEAD: b5529084906af89827f6d9befd613457a1615918
Last commit: 2 weeks ago
Core tap ORIGIN: https://github.com/Homebrew/homebrew-core
Core tap HEAD: c17c01bd95e7b1fbd2e01ff32593eadb7a9747f7
Core tap last commit: 17 minutes ago
HOMEBREW_PREFIX: /usr/local
HOMEBREW_REPOSITORY: /usr/local/Homebrew
HOMEBREW_CELLAR: /usr/local/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://homebrew.bintray.com
CPU: quad-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648
Clang: 8.1 build 802
Git: 2.11.0 => /Applications/Xcode.app/Contents/Developer/usr/bin/git
Perl: /usr/bin/perl
Python: /usr/local/bin/python => /usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/bin/python2.7
Ruby: /usr/bin/ruby => /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
Java: 1.8.0_66, 1.6.0_65-b14-468
macOS: 10.12.5-x86_64
Xcode: 8.3.3
CLT: 8.3.2.0.1.1492020469
X11: 2.7.11 => /opt/X11
```

**Comment by MikeMcQuaid** [comment] 2017-07-17 14:18
I cannot reproduce this on 10.13 or 10.11 installs. Does `brew outdated` output anything?

**Comment by oliviermarti** [comment] 2017-07-17 15:10
No, absolutely nothing.

**Comment by ilovezfs** [comment] 2017-07-17 15:26
@oliviermarti do you have any compilation flags set in your environment, especially any related to fortran?

**Comment by oliviermarti** [comment] 2017-07-17 16:40
Don't think so:

```
marti@Spip-~ 👉  printenv | grep FC
MY_FCM=/Users/marti/local/softs/fcm-1.5
marti@Spip-~ 👉  printenv | grep F77
marti@Spip-~ 👉  printenv | grep F90
marti@Spip-~ 👉  printenv | grep FLAG
XPC_FLAGS=0x0
marti@Spip-~ 👉
``` 

Should I search something else ?

**Comment by MikeMcQuaid** [comment] 2017-07-17 16:52
Can you try to `HOMEBREW_ENV_FILTERING=1 brew install hdf5 --with-fortran`?

**Comment by oliviermarti** [comment] 2017-07-17 18:13
No progress :-(

Before uninstalling hdf5 (to reinstal with fortran), I ran:

```
marti@Spip-~ 👉  brew uninstall gdal netcdf cdo nco
Warning: Use hdf5 instead of deprecated homebrew/science/hdf5
```

May this be a clue ?

Olivier

**Comment by ilovezfs** [comment] 2017-07-17 18:52
Please try this:
```
mkdir ~/homebrew-20170717
sudo mv /usr/local ~/homebrew-20170717
/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
brew install --with-fortran hdf5
```

**Comment by oliviermarti** [comment] 2017-07-17 19:39
Which works ...

I can deal with that : keep that new brew install, and add the softwares I need.

But if you want me to test any things in my broken brew, please tell. That the least I can do if it could help.

Thanks !

**Comment by iMichka** [comment] 2017-08-02 20:18
Maybe something broke during the hdf5 migration to core? Don't know what happened here, but if a new fresh install works for you, I'm fine with that. No need to do more post-mortem here. Closing.

**Closed by iMichka** 2017-08-02 20:18 UTC
