### ISSUE TITLE
Error building opencv --with-java

### ISSUE THREAD

**Issue by aleksey-suprun** [Homebrew/homebrew-science#2106] opened 2015-04-15 20:41 UTC
Hello!

Today I tried to install opencv-2.4.11 on my mac and installation was interrupted with error:

$ brew install opencv --with-java
......
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/cmdparser.cpp.o] Error 1
1 error generated.
make[2]: *** [modules/core/CMakeFiles/opencv_core.dir/src/arithm.cpp.o] Error 1
make[1]: *** [modules/core/CMakeFiles/opencv_core.dir/all] Error 2
make: *** [all] Error 2

It will be great if somebody can help me with it

**Comment by dpo** [comment] 2015-04-15 21:26
Please paste the output of `brew gist-logs opencv`.

**Comment by aleksey-suprun** [comment] 2015-04-16 07:18
$ brew gist-logs opencv
https://gist.github.com/8e1bb8a2a067310727a3

**Comment by tdsmith** [comment] 2015-04-17 05:55
This is caused by https://github.com/Homebrew/homebrew/issues/38514; closing as duplicate. You can install Xcode to work around it until Apple fixes their C++ headers in the CLT.

**Closed by tdsmith** 2015-04-17 05:55 UTC
