### ISSUE TITLE
opencv3 fails to link with brew python3

### ISSUE THREAD

**Issue by impact27** [Homebrew/homebrew-science#3667] opened 2016-05-17 10:44 UTC
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

- Brief summary of issue:

Had to manually link opencv3 to brew python3. I would expect the formula to do that for me.

- Please state the complete command that you issued.

```
brew install opencv3 --with-python3
[...]
python3 -c "import cv2"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named 'cv2'
ln -s /usr/local/opt/opencv3/lib/python3.5/site-packages/cv2.cpython-35m-darwin.so /usr/local/lib/python3.5/site-packages/cv2.so
python3 -c "import cv2"
```

**Comment by heinemml** [comment] 2016-05-17 17:18
opencv3 is keg only as it conflicts with the opencv package. You can see this at the end of the build or by issuing `brew info opencv3`

```
==> Caveats
This formula is keg-only, which means it was not symlinked into /usr/local.

opencv3 and opencv install many of the same files.

Generally there are no consequences of this for you. If you build your
own software and it requires this formula, you'll need to add to your
build variables:

    LDFLAGS:  -L/usr/local/opt/opencv3/lib
    CPPFLAGS: -I/usr/local/opt/opencv3/include


If you need Python to find bindings for this keg-only formula, run:
  echo /usr/local/opt/opencv3/lib/python2.7/site-packages >> /usr/local/lib/python2.7/site-packages/opencv3.pth
```

The message is only show for python 2. But if you build with python3 support you have to issue a similar command. On my System that is:  `echo /usr/local/opt/opencv3/lib/python3.5/site-packages >> /usr/local/lib/python3.5/site-packages/opencv3.pth`

So in my opinion this is not a bug but a known limitation of maintaining opencv2.x and opencv3 at the same time.

**Comment by impact27** [comment] 2016-05-17 17:24
Ok but when I install --with-python3 why does it display the instructions for Python 2 and not 3?

**Comment by heinemml** [comment] 2016-05-18 07:49
Valid point. The message is generated by the homebrew system and is not formula specific. I opened an issue on the homebrew tracker. Let's see what's the opinion there.

**Comment by tdsmith** [comment] 2016-05-21 00:34
Closing as not a homebrew-science bug.

**Closed by tdsmith** 2016-05-21 00:34 UTC

**Comment by ReaddyEddy** [comment] 2016-09-06 13:03
I've picked up an issue with python 3.5.2_1 that _may_ explain some of this if you have installed 3.5.1 and have then upgraded to 3.5.2_1 you'll find the the opencv installation doesn't find the correct python when installing opencv3 from the command line and the Python3 include paths have to be explicitly set to point at the newer libraries in the cake configuration. SFAIKS the python 3.5.1 paths are taking precedence over the 3.5.2_1 paths in particular the header path is not found.
