### ISSUE TITLE
Deprecation of homebrew-science

### ISSUE THREAD

**Issue by iMichka** [Homebrew/homebrew-science#6365] opened 2017-09-29 16:23 UTC
Since #6348 we do not accept new formulae anymore. We also already migrated the most important formulae to core, and we have a list of other formulae that are being migrated: #6331

This is due to the fact that homebrew-science will loose OS X buildbot support / homebrew-core maintainer support around end of December.

I would like to discuss what happens with the rest of formulae and with homebrew-science in general after that date. There will be a massive amount of formulae that will not have been migrated.

I would like to have this discussion here, and be as transparent as possible about our plans.

@Homebrew/science @MikeMcQuaid

**Comment by tdsmith** [comment] 2017-09-29 17:17
What kind of options are under consideration? Splitting off into a separate organization? Closing shop and directing contributors to complementary efforts like conda-forge?

This is difficult in part because a lot of important scientific software has poor code quality and is difficult to package; build systems are not prioritized by tenure committees. :) Thanks to everyone who's fought to keep these tools building.

**Comment by iMichka** [comment] 2017-09-29 17:28
I think that some formulae could be hosted in private taps, maybe sorted by topic. There are a lot of formulae that have less than 10/20 downloads in the last 90 days, so these are really "low traffic" formulae.

This would allow to shift the maintenance effort to some users that really want to focus on a bunch of formulae and keep them working, while we provide a backbone of high-quality core formulae and dependencies.

**Comment by sjackman** [comment] 2017-09-29 17:52
When looking at download statistics, keep in mind that number of downloads in some time period doesn't indicate how many people installed the tool once ages ago have been using it ever since. Useful formula that are venerable and are no longer updated may not see recent downloads, even though they're still actively being used. That's one advantage that Debian Popularity Contest (Popcon) has over Homebrew Analytics. It reports the number of packages that are *currently* installed. Looking at the flux of package (number of new installations in a time period) is heavily biased toward formulae that were updated during that window.

**Comment by sjackman** [comment] 2017-09-29 17:55
@MikeMcQuaid How do you feel about doing a one-time test of all formulae in Homebrew/science, and purging any formulae that fail `brew audit`, `brew install`, `brew test`, or `brew linkage`, and keeping the formulae that pass all four? Note that I'm excluding `brew audit --online` for GitHub notability. If it were notable and passed all four tests, it would have been moved to Homebrew/core.

**Comment by MikeMcQuaid** [comment] 2017-09-29 19:02
I would suggest that Homebrew/homebrew-science gets moved to another organisation or user and we just make use of GitHub's redirection feature. That said, all these formulae will remain in Git history forevermore for users who want to pull them out and start maintaining them. Regardless, at the end of that time period the tap will either be moved (like dunn/homebrew-emacs) or marked as deprecated (like homebrew/homebrew-apache) and have all formulae removed.

Let's be brutally honestly here for a moment: one of the reasons this whole thing is happening is that Homebrew/homebrew-science is not consistently maintained at a quality that reflects well on the Homebrew organisation. There's been a proliferation of options, personal tweaks and Linux support added rather than fixing user issues, resolving audits and keeping formulae maintained and up-to-date. Open source is a volunteer effort so that's not a critique of anyone but I think we need to be open about the fact many of the current formulae aren't maintained and there's no silver bullet that's going to fix that so it's better to users to delete them (remembering the Git history) rather than keep them going in hope they'll get fixed.

**Comment by sjackman** [comment] 2017-09-29 19:10
My suggestion is to set a new threshold of quality for Homebrew/science, and ensure that all formulae in the tap pass `brew audit`, `brew install`, `brew test`, and `brew linkage`. Any formulae that don't pass these standards will be deleted.

**Comment by MikeMcQuaid** [comment] 2017-09-29 19:12
As I've mentioned: either this tap is migrated to another user or organisation or everything is deleted regardless. What happens if it is migrated I personally don't have any opinions on.

**Comment by sjackman** [comment] 2017-09-29 20:18
I wonder whether we could build bottles for macOS on TravisCI. I haven't yet found a secure way to transfer bottles from a pull request build to Bintray and GitHub without exposing those credentials. https://docs.travis-ci.com/user/reference/osx/

**Comment by sjackman** [comment] 2017-09-29 20:19
I've e-mailed CircleCI to request early access to their CircleCI 2.0 macOS builds.
https://discuss.circleci.com/t/os-x-macos-ios-support-on-circleci-2-0/16430

**Comment by MikeMcQuaid** [comment] 2017-09-30 08:10
@sjackman If you figure out a way to do that it'd be great for all third-party taps. It's possible on Travis today if you can get people to submit PRs to a branch and then make your own PR from that branch on the main repo (not fork) but obviously that's a pain.

**Comment by sjackman** [comment] 2017-09-30 16:00
Opening the PR could be automated using AWS Lambda or a similar service. Yes, a bit of a pain though.

**Comment by schoeps** [comment] 2017-10-01 11:16
did you guys considered the concept of maintainers to increase the quality of the formulae?

**Comment by schoeps** [comment] 2017-10-01 11:21
Ii would be happy to take care of a few formulae that I regularly use (octave, getdp, gmsh and some of their dependencies). I could do that in a separate repository but that would be considerably less visible. 
In conclusion, if somebody sets up a new science repository (for linux and mac?) then I am happy to contribute. Sorry, I have not the experience to do that on my own but maybe @sjackman and @dpo could start the first initiative?

**Comment by MikeMcQuaid** [comment] 2017-10-01 11:37
@schoeps That may be an option for third-party taps but not really for core. I think increasing the visibility would be a better idea than having repositories where some formulae are maintained by some people and others are not (which ends up with some being unmaintained).

**Comment by iMichka** [comment] 2017-10-01 11:49
> concept of maintainers
Like debian/macports? Not really the philosophy of homebrew I think. I like the fact that formulae in core "belong" to everybody. For low-usage formulae taps are fine though, were one dedicated maintainer can keep a bunch of formulae up to date.

> octave, getdp, gmsh
These are probably worth migrating to core  (not everything is in the list, but you can add formulae that are not hosted on GitHub at the end of the list)

We could also update the readme here with a selection of links to private taps once the formulae are gone here. This is not much work to maintain and would help for the visibility of private taps.

**Comment by MikeMcQuaid** [comment] 2017-10-01 12:07
> Like debian/macports? Not really the philosophy of homebrew I think.

And worth adding to that: unlike Debian our formulae don't just keep working indefinitely. We're too dependent on Apple's changes so formulae need kept up to date.

> We could also update the readme here with a selection of links to private taps once the formulae are gone here. This is not much work to maintain and would help for the visibility of private taps.

This seems like a good idea 👍

**Comment by sjackman** [comment] 2017-10-01 15:41
> And worth adding to that: unlike Debian our formulae don't just keep working indefinitely. We're too dependent on Apple's changes so formulae need kept up to date.

Linuxbrew formulae should keep working indefinitely, since it doesn't any dependences provided by the host. Untested in practice, but at least in principle. It's more likely in my experience that a formula will stop working because the `url` disappears. The bottle stays around forever though.

**Comment by mkhorton** [comment] 2017-10-03 00:13
Very sad to see this. Homebrew-science has been truly useful for both myself and colleagues... I'm sure no one here needs to be reminded how truly terrible installing/compiling a lot of scientific software is, and though it may be imperfect, it's been far better than the alternative, so thank you all for getting it to this stage!

(As for future contributions... 3 of the now-closed PRs were mine, I had a 4th ready to submit too. I'm happy to make a private materials science tap if necessary, but would be very glad to contribute elsewhere if homebrew-science finds a new home.)

**Comment by sjackman** [comment] 2017-10-03 02:25
One possibility is to transfer Homebrew/science to the Linuxbrew/ organization. Building Linux bottles is no problem. I'm looking into build macOS bottles with CircleCI. It may or may not be possible, or may require money to keep up with the load. If it's not possible to build macOS bottles on Linuxbrew/, does it still make sense to move Homebrew/science to the Linuxbrew/ organization? We would continue to support installing the formulae from source on macOS.

Note that all notable formulae are being moved to Homebrew/core. We're only talking about the remaining non-notable formulae here.

**Comment by sjackman** [comment] 2017-10-03 05:17
@mkhorton Sorry to hear about your closed pull requests, Matthew. Please do submit them to Homebrew/core if they pass `brew audit --online`.

**Comment by mkhorton** [comment] 2017-10-03 05:36
@sjackman many thanks, unfortunately I don't think they'd pass the notability requirement for homebrew core (at least in terms of GitHub stars, though they have plenty of citations in publications, it depends what metric you want to use but I think this is just how it is for a lot of scientific software)

**Comment by iMichka** [comment] 2017-10-03 10:10
I think there are two aspects for scientific packages:
- their quality as a scientific tool; number of citations in papers is important. Though older libraries are probably just cited as "first library doing this and that", but not used anymore. I can not judge what tool is worth being added, because it may depend on the topic.
- their quality to be packaged and how easy it is to maintain them. Github stars are a quite good metric, homebrew analytics for already added formula too.

I think these are two different goals/topics, and this is why homebrew-science is struggling.

New formula get added, then upstream disappears or never answers, and things never get fixed. I have been doing updates here and there in science, and I can clearly see that most of the formula do not meet the quality standards expected by a package manager.

We already migrated a bunch of high-usage formulae to core. I have the feeling that if they are used a lot, the community is bigger, and they are well-maintained. These migrations went over smoothly.

The energy we put into homebrew-science is not scaling. The more formula are added, the more painful it is to keep things up and running. Just look at the number of pull requests ... I closed 30 pull requests for new formulae, some were 1 year old. Maybe with 5 full time science maintainers, this could be doable.

Closing homebrew-science is moving that responsibility back to the few interested that want to maintain a private tap for their own specific formula. As said before, I am willing to keep an up to date list of taps in the README, which requires less effort on our side.

And I am not sure that moving all the science formula to the Linuxbrew organisation will help the solve the initial problem of maintainability. It is just shifting the problem somewhere else. But that may be a temporary solution (and you know what happen with temporary solution: they end up staying forever).

**Comment by schoeps** [comment] 2017-10-03 10:10
> One possibility is to transfer Homebrew/science to the Linuxbrew/ organization. Building Linux bottles is no problem. I'm looking into build macOS bottles with CircleCI. It may or may not be possible, or may require money to keep up with the load. If it's not possible to build macOS bottles on Linuxbrew/, does it still make sense to move Homebrew/science to the Linuxbrew/ organization? We would continue to support installing the formulae from source on macOS.

@sjackman I really prefer this solution. How could we start? What could I do to help? 

@MikeMcQuaid I guess there is only one problem left, let’s suppose package A in the new science repository requires package B from the same repository but B is also in core then we have a conflict, right? I think https://github.com/Homebrew/legacy-homebrew/pull/43535 should have covered this issue.

**Comment by schoeps** [comment] 2017-10-03 10:17
> We already migrated a bunch of high-usage formulae to core. I have the feeling that if they are used a lot, the community is bigger, and they are well-maintained. These migrations went over smoothly.

As I said before, the formulae moved to core do not necessarily meet the standards or requirements of all scientists (e.g. with respect to reproducubility etc). For example using Accelerate is in my computational community not an option. I think there is the need for a repository of scientific software, even if this has lower traffic...

> And I am not sure that moving all the science formula to the Linuxbrew organisation will help the solve the initial problem of maintainability. It is just shifting the problem somewhere else. But that may be a temporary solution (and you know what happen with temporary solution: they end up staying forever).

As I said before, one could assign maintainers to each formula. I do not see why this is worse than having packages spread in 1000 different local repositories that no user will find or trust. We could move only formula with at least one active maintainer.

**Comment by iMichka** [comment] 2017-10-03 10:25
> As I said before, one could assign maintainers to each formula. I do not see why this is worse than having packages spread in 1000 different local repositories that no user will find or trust. We could move only formula with at least one active maintainer.

Yes, splitting things up is a concern, and may be a problem. Not sure we can find as many maintainers as we wish we could.

What happens for revision bumps. For example the last `boost` bump is still to be done: #6296. Bumping the first 12 formulae took a lot of effort because some of them needed to be patched/fixed manually. There are still 41 open items there. Who is going to double-check them all and fix them? See also the `gsl` bump: #5841. Still some formulae that need to be fixed.

On the other side nobody complains about these being broken, so I have also the feeling that nobody is using these and we should not worry too much ... but it is unsatisfactory.

**Comment by schoeps** [comment] 2017-10-03 10:39
> What happens for revision bumps. For example the last boost bump is still to be done: #6296. Bumping the first 12 formulae took a lot of effort because some of them needed to be patched/fixed manually. There are still 41 open items there. Who is going to double-check them all and fix them? See also the gsl bump: #5841. Still some formulae that need to be fixed.

Why bump a formula A if nobody cares? Either another maintainer needs to update A as it the dependency of his/her package B or a user asks for a new version of A explicitly. In both cases one could contact the maintainer of A to take action or at least to help?

(I know, it's easy for me to say this as I was not helping you guys on the organisation level but I had the impression that it worked quite well with the formulas that I was involved in...)

**Comment by ilovezfs** [comment] 2017-10-03 11:00
@schoeps it's not a choice. The linkage breaks when the dependency is upgraded.

**Comment by MikeMcQuaid** [comment] 2017-10-03 11:01
> As said before, I am willing to keep an up to date list of taps in the README, which requires less effort on our side.

@imichka to be explicit: this tap will be moved to another org or archived so the README updates will not be able to keep happening if it’s archived in this org.

**Comment by iMichka** [comment] 2017-10-03 11:21
> Why bump a formula A if nobody cares?

Why keep these formula around if nobody cares? Formulated differently: why keep them under the homebrew org if nobody cares. And I think this is mostly why homebrew-science is being phased out.

> this tap will be moved to another org or archived so the README updates will not be able to keep happening

@MikeMcQuaid thanks for the precision. At least it is clear. I hope we can have at least one single link to some other org/page, so that people are not lost and get a hint where to find their formulae.

@sjackman I am not a big fan to move this to the Linuxbrew org.

Why not create a new org, called Homebrew-Science or Brew-Science, and have a bunch of taps in there? These may have just Linux bottles at the beginning (until we get a mac CI there). We could do something like:
Homebrew-Science/bioinformatics, Homebrew-Science/physics, Homebrew-Science/math ...

**Comment by schoeps** [comment] 2017-10-03 11:53
> Why keep these formula around if nobody cares? Formulated differently: why keep them under the homebrew org if nobody cares. And I think this is mostly why homebrew-science is being phased out.

Agreed. I think we only differ by the question on how to measure how much is cared about a formula :) I‘d say if somebody is willing to spend time to maintain it then we should keep the formula even if there are not many downloaders.

> Why not create a new org, called Homebrew-Science or Brew-Science, and have a bunch of taps in there? These may have just Linux bottles at the beginning (until we get a mac CI there). We could do something like: Homebrew-Science/bioinformatics, Homebrew-Science/physics, Homebrew-Science/math ...

Also fine for me! We could make a poll who wants to take care of which formula. If nobody cares about xyz, then xyz does not join the party.

**Comment by dpo** [comment] 2017-10-03 12:01
I would suggest moving all formulae to a boneyard and progressively move them out to taps as maintainers are identified.

**Comment by MikeMcQuaid** [comment] 2017-10-03 15:09
> Closing homebrew-science is moving that responsibility back to the few interested that want to maintain a private tap for their own specific formula. As said before, I am willing to keep an up to date list of taps in the README, which requires less effort on our side.
> 
> And I am not sure that moving all the science formula to the Linuxbrew organisation will help the solve the initial problem of maintainability. It is just shifting the problem somewhere else. But that may be a temporary solution (and you know what happen with temporary solution: they end up staying forever).

I agree completely with this. There is no quick fix that gets you from unmaintained to maintained formulae.

**Comment by sjackman** [comment] 2017-10-03 17:58
Unmaintained formulae can disappear by triage. If a formula fails to build after a dependency bump, post a GitHub message and tag the previous committers (could possibly be automated) saying that this formula currently fails to build and will go away if no one steps up to fix it.

Alternatively the idea that each formula has a list of maintainers could be formalized. If a formula fails to build, tag the current maintainers in a GitHub message. They have the option of either fixing it, or stepping down. If a formula has no current maintainers, and it fails to build, that formula is dropped.

I just recalled that GitHub has the concept of Code Owners: https://github.com/blog/2392-introducing-code-owners. We could possibly use this feature to keep track of the maintainers of each formula.

**Comment by sjackman** [comment] 2017-10-03 18:13
I would like to confirm whether each formula can be built from source. Those that fail to build ought to be removed, after notifying previous committers and waiting a period for their response. Tanya @tmozgach has done this audit for the formulae tagged `bioinformatics`. Other maintainers will need to step up to for the other domains.

**Comment by sjackman** [comment] 2017-10-04 19:19
Do any of the existing @Homebrew/science maintainers plan to create a private tap to hold formulae currently in `Homebrew/science` that will not migrate to `Homebrew/core`?

I am considering creating a `Linuxbrew/bioinformatics` tap to host the bioinformatics formulae that do not move to core. I plan for it to support both Linux and macOS. It will have bottles for Linux. It may have bottles for macOS if I can get it working. If not, installations on macOS will be from source only.

**Comment by mkhorton** [comment] 2017-10-04 19:23
(Not a maintainer, but I created https://github.com/mkhorton/homebrew-matsci for a few materials science formulae that wouldn't meet core notability reqs -- I'll only be testing for macOS though.)

**Comment by sjackman** [comment] 2017-10-04 19:24
@mkhorton Do you plan on using CI for testing? TravisCI is pretty easy to set up for macOS.

**Comment by mkhorton** [comment] 2017-10-04 19:29
@sjackman Yup, I can do that. Thanks for the suggestion.

**Comment by HadrienG** [comment] 2017-10-05 05:03
I was planning to maintain a small `metagenomics` tap but I'd be open to contributing to `Linuxbrew/bioinformatics` instead

**Comment by schoeps** [comment] 2017-10-05 09:16
@sjackman I would like to continue to maintain octave, gmsh and getdp and their dependencies if necessary. This is troublesome as some of them are in core but are lacking options that I consider important (e.g. openblas).

**Comment by ilovezfs** [comment] 2017-10-05 09:54
@schoeps Linuxbrew already uses OpenBLAS for those formulae so you're literally proposing a tap that is specific to macOS be housed within the Linuxbrew organization.

**Comment by schoeps** [comment] 2017-10-05 11:24
@ilovezfs yes, however it might make sense to move octave to `homebrew-numerics ` to mutually benefit from the common maintenance (I use linuxbrew for our cluster and homebrew for my laptop). I guess octave was moved to `linuxbrew-core` by @sjackman because it disappered from `homebrew-science`.

**Comment by ilovezfs** [comment] 2017-10-05 11:26
@schoeps the Linuxbrew version of the formula probably builds on macOS already.

**Comment by schoeps** [comment] 2017-10-05 11:27
@ilovezfs but how can I tap it? (and what about the dependencies https://github.com/Homebrew/legacy-homebrew/pull/43535)

**Comment by ilovezfs** [comment] 2017-10-05 11:29
`brew tap linuxbrew/core`

**Comment by schoeps** [comment] 2017-10-05 11:30
... but this will install the dependencies from `homebrew/core`, even if I have pined `linuxbrew/core`, right?

**Comment by ilovezfs** [comment] 2017-10-05 12:21
@schoeps that's a good question. I don't know.

**Comment by sjackman** [comment] 2017-10-05 15:54
@schoeps Although it's not a common use case, you can install and use Linuxbrew on macOS.

**Comment by sjackman** [comment] 2017-10-05 15:55
> I was planning to maintain a small metagenomics tap at https://github.com/HadrienG/brew-metagenomics but I'd be open to contributing to Linuxbrew/bioinformatics instead

@HadrienG You'd be most welcome to contribute to `Linuxbrew/bioinformatics`. It's not launched yet, but looking quite likely. You, @tseemann, and I are on board.

**Comment by sjackman** [comment] 2017-10-05 16:06
sjackman [9:05 AM] 
89 formulae in Homebrew/science are notable, 32 of those have `bin.install`, so 57 can be migrated to core (if I understand the migration criteria correctly). That leaves something like 570 formulae that need a home. I feel that a hard exit of deleting all the formulae is unnecessarily drastic and pretty rough on people that are currently using these formulae. I'd prefer to put end-of-life the tap and put it into maintenance mode. That means no new formulae (that's already the case). No new versions. We accept PRs to move a formula to a different tap. We accept PRs to delete the bottles from the formula if the bottles break (due for example to a version change in Homebrew/core). The end-of-life notification is displayed prominently in the `README.md` and `.github/*` files. That's my suggestion. I understand completely if the maintainers of the Homebrew organization don't have the time, energy, or inclination for that end-of-life process. If that's the case, I'd suggest transferring the repo to a different organization to carry out that plan.

**Comment by MikeMcQuaid** [comment] 2017-10-06 03:41
> The end-of-life notification is displayed prominently in the README.md and .github/* files. That's my suggestion. I understand completely if the maintainers of the Homebrew organization don't have the time, energy, or inclination for that end-of-life process. If that's the case, I'd suggest transferring the repo to a different organization to carry out that plan.

This repository will be made read-only (archived) and have all formulae deleted if it remains in the Homebrew organisation on 1st January 2018. When the tap is not part of the Homebrew organisation (or archived) it will no longer be able to have access to Homebrew's CI services. I have no preferences on how things are handled otherwise.

**Comment by sjackman** [comment] 2017-10-06 05:23
Yes. We agree then. We'll transfer Homebrew/science to a different organization prior to 2018-01-01.

**Comment by sjackman** [comment] 2017-10-07 02:17
My experiment of building a bottle for macOS on CircleCI is successful! As far as I know they only have macOS Sierra. Perhaps it'd be possible to use `:sierra_or_later` to support later versions of macOS if the bottle is confirmed to work there. Perhaps it'd be possible to support earlier version of macOS using `-mmacosx-version-min`.

**Comment by HadrienG** [comment] 2017-10-07 09:12
using `xcode: "8.2.1"` should build on El Capitan ([doc link](https://circleci.com/docs/1.0/build-image-macos/)) or did they drop that in CircleCI 2.0?

**Comment by sjackman** [comment] 2017-10-07 15:14
CircleCI 2.0 dropped `xcode: "8.2.1"` on El Capitan. They oldest they have is `xcode: "8.3.3"` on Sierra.

**Comment by audy** [comment] 2017-11-27 07:11
Did BLAST really not make the cut? I only ask because I'm surprised that it didn't show up in the analytics report. BLAST is an indispensable tool for bioinformatics.

**Comment by sjackman** [comment] 2017-11-27 07:14
`blast` is almost certainly used enough. I'll check the analytics tomorrow to figure out why it didn't show up on https://github.com/Homebrew/homebrew-science/issues/6331

**Comment by sjackman** [comment] 2017-11-27 07:15
I plan to migrate all the non-notable bioinformatics formulae to https://github.com/Linuxbrew/homebrew-bio

**Comment by audy** [comment] 2017-11-27 07:18
@sjackman sounds good. Hopefully there will be a way to migrate attribution to contributors as well.

**Comment by sjackman** [comment] 2017-11-27 07:19
Yep, I plan to migrate history.

**Comment by audy** [comment] 2017-11-27 07:20
@sjackman Awesome! Thanks for thinking of that.

**Comment by MikeMcQuaid** [comment] 2017-11-27 08:19
> I plan to migrate all the non-notable bioinformatics formulae to
> https://github.com/Linuxbrew/homebrew-bio

@sjackman If that tap is going to support macOS and Linux: please don't move it to the Linuxbrew organisation. We have enough confusion already with people submitting Linuxbrew issues to Homebrew. I'd suggest a HomebrewScience or HomebrewBio organisation.

**Comment by MikeMcQuaid** [comment] 2017-12-11 12:14
Note: I will be archiving this repository, disabling CI and removing all formulae on or shortly after 1st January 2018 (less than a month away). Please migrate any formulae to other taps before that point.

**Comment by audy** [comment] 2017-12-13 05:34
Does someone mind posting the analytics report (# of downloads by formula)? There are a few bioinformatics formula that I consider essential but didn't make the cut. I'd like to try to move over to homebrew/core (blast, cd-hit and maybe some others).

Also, (@sjackman) what commands are you using to move formula over while preserving contributor history? Is it [this](http://gbayer.com/development/moving-files-from-one-git-repository-to-another-preserving-history/)?

**Comment by sjackman** [comment] 2017-12-13 19:47
> Also, (@sjackman) what commands are you using to move formula over while preserving contributor history?

Yes, I was planning on use `git filter-branch`.

**Comment by sjackman** [comment] 2017-12-13 20:04
> Does someone mind posting the analytics report (# of downloads by formula)?

The following tables include the number of installations on macOS is in the last 90 days as of 2017-12-13. I also have installations for Linux, not included here. The GitHub `Notable` column is as of 2017-10-11. I plan to update this column with current data.

# Bioinformatics

https://gist.github.com/sjackman/d1db0d73597b674bb23b51221a2914cd#file-metrics-bioinformatics-macos-tsv

# Homebrew/science

https://gist.github.com/sjackman/d1db0d73597b674bb23b51221a2914cd#file-metrics-science-macos-tsv

**Comment by sjackman** [comment] 2017-12-13 20:09
@audy I'd love your help in migrating formulae from Homebrew/science to Homebrew/core! :heart:

**Comment by goxberry** [comment] 2017-12-16 04:45
@iMichka This is terrible news! I think trying to maintain a software stack without the benefit of a package manager is the height of stupidity, so whenever I have to write software with stable dependencies, I try to contribute packages for those pieces of software, or update them, when I can.

I'll second the observation that

> this is difficult in part because a lot of important scientific software has poor code quality and is difficult to package; build systems are not prioritized by tenure committees. :)

As an infrequent contributor (I'm #25 right now), I'm willing to pitch in and migrate some formula (probably along the lines of `mfem`, `hypre`, and `sundials`, maybe some others) over to core. My Ruby is abysmal, but if the Homebrew core maintainers are willing to work with me on that point, I'm happy to submit a few PRs to help.

I looked at the download statistics and noticed these packages don't get many install events -- my guess is that users of these packages are being directed instead to github.com/LLNL/spack if they want to use a package manager. Although I like spack a lot, the main drawback for me is that spack can be like macports, and will download, e.g., gcc unless you configure it not to. PETSc's build system also includes a mini-package manager that will download and install a bunch of dependencies, and the general advice to users has been to download from the git repo instead (for reasons probably not worth getting into), which probably draws more users away.

**Comment by sjackman** [comment] 2017-12-16 16:22
Thanks for your help migrating, Geoffrey! It's much appreciated.

**Comment by MikeMcQuaid** [comment] 2018-01-01 09:41
This tap has been deprecated and will shortly be archived.

If you wish to [migrate other widely used formulae](https://github.com/Homebrew/homebrew-science/issues/6331) to Homebrew/homebrew-core please [submit a pull request](http://docs.brew.sh/How-To-Open-a-Homebrew-Pull-Request.html) there.

**Closed by MikeMcQuaid** 2018-01-01 09:41 UTC
Labels: help wanted, in progress

**Comment by MikeMcQuaid** [comment] 2018-01-12 21:55
Please note, though, that https://github.com/brewsci/homebrew-science is the same tap with the same issues that led to this one being deprecated/archived and is not endorsed in any way by the Homebrew project.
