### ISSUE TITLE
ld: library not found for -lopencv_ts

### ISSUE THREAD

**Issue by fivetech** [Homebrew/homebrew-science#3692] opened 2016-05-22 15:05 UTC
After upgrading opencv3 via homebrew, when I try to build the project, Xcode says: 

```
 ld: library not found for -lopencv_ts
 clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

However, it works when I remove -lopencv_ts from "Other Linker Flags" section. 

By the way, I run "brew doctor" and get this result:

```
Warning: Your Xcode (7.3) is outdated
Please update to Xcode 7.3.1.
Xcode can be updated from the App Store.
```

However, I have up-to-date version of Xcode. There is no 7.3.1. version of Xcode.

**Comment by ilovezfs** [comment] 2016-05-22 15:21
>However, I have up-to-date version of Xcode. There is no 7.3.1. version of Xcode.

Yes, there is a 7.3.1: https://itunes.apple.com/us/app/xcode/id497799835?mt=12

You need to add the library path (`/usr/local/opt/opencv3/lib`) to `Build Settings > Search Paths > Library Search Paths` and the include path (`/usr/local/opt/opencv3/include`) to the `Header Search Paths`.

This may help you: http://blogs.wcode.org/2014/11/howto-setup-xcode-6-1-to-work-with-opencv-libraries/

**Comment by fivetech** [comment] 2016-05-22 15:28
> Yes, there is a 7.3.1: https://itunes.apple.com/us/app/xcode/id497799835?mt=12
I mean there is no update appeared in App Store for 7.3.1.

> You need to add the library path (/usr/local/opt/opencv3/lib) to Build Settings > Search Paths > Library Search Paths and the include path (/usr/local/opt/opencv3/include) to the Header Search Paths.

I have already done it. I could build the project before upgrading opencv3. After upgrading opencv3, the problem started to occur.

**Comment by ilovezfs** [comment] 2016-05-22 16:31
I only see these libraries:
```
libopencv_calib3d.3.1.0.dylib
libopencv_calib3d.3.1.dylib
libopencv_calib3d.dylib
libopencv_core.3.1.0.dylib
libopencv_core.3.1.dylib
libopencv_core.dylib
libopencv_features2d.3.1.0.dylib
libopencv_features2d.3.1.dylib
libopencv_features2d.dylib
libopencv_flann.3.1.0.dylib
libopencv_flann.3.1.dylib
libopencv_flann.dylib
libopencv_highgui.3.1.0.dylib
libopencv_highgui.3.1.dylib
libopencv_highgui.dylib
libopencv_imgcodecs.3.1.0.dylib
libopencv_imgcodecs.3.1.dylib
libopencv_imgcodecs.dylib
libopencv_imgproc.3.1.0.dylib
libopencv_imgproc.3.1.dylib
libopencv_imgproc.dylib
libopencv_ml.3.1.0.dylib
libopencv_ml.3.1.dylib
libopencv_ml.dylib
libopencv_objdetect.3.1.0.dylib
libopencv_objdetect.3.1.dylib
libopencv_objdetect.dylib
libopencv_photo.3.1.0.dylib
libopencv_photo.3.1.dylib
libopencv_photo.dylib
libopencv_shape.3.1.0.dylib
libopencv_shape.3.1.dylib
libopencv_shape.dylib
libopencv_stitching.3.1.0.dylib
libopencv_stitching.3.1.dylib
libopencv_stitching.dylib
libopencv_superres.3.1.0.dylib
libopencv_superres.3.1.dylib
libopencv_superres.dylib
libopencv_video.3.1.0.dylib
libopencv_video.3.1.dylib
libopencv_video.dylib
libopencv_videoio.3.1.0.dylib
libopencv_videoio.3.1.dylib
libopencv_videoio.dylib
libopencv_videostab.3.1.0.dylib
libopencv_videostab.3.1.dylib
libopencv_videostab.dylib
```

**Comment by fivetech** [comment] 2016-05-22 16:51
http://blogs.wcode.org/2014/11/howto-setup-xcode-6-1-to-work-with-opencv-libraries/
In this guide, we should link libraries with this:
-lopencv_calib3d -lopencv_core -lopencv_features2d -lopencv_flann -lopencv_highgui -lopencv_imgcodecs -lopencv_imgproc -lopencv_ml -lopencv_objdetect -lopencv_photo -lopencv_shape -lopencv_stitching -lopencv_superres **-lopencv_ts** -lopencv_video -lopencv_videoio -lopencv_videostab 

I tried to build opencv3 on Ubuntu and I can see libopencv_ts. I don't know why libopencv_ts disappeared after upgrading opencv3.

**Comment by ilovezfs** [comment] 2016-05-22 17:00
This diff will fix it if you build from source:
```
diff --git a/opencv3.rb b/opencv3.rb
index 4afd1ed..7d7fdb6 100644
--- a/opencv3.rb
+++ b/opencv3.rb
@@ -116,6 +116,7 @@ class Opencv3 < Formula
     with_qt = build.with?("qt") || build.with?("qt5")
 
     args = std_cmake_args + %W[
+      -DBUILD_opencv_ts=ON
       -DBUILD_JASPER=OFF
       -DBUILD_JPEG=OFF
       -DBUILD_TIFF=OFF
```

**Comment by ilovezfs** [comment] 2016-05-23 08:32
@fivetech were you able to get your project working again with that patch?

**Comment by ilovezfs** [comment] 2016-06-04 04:50
@fivetech This seems to have been an upstream packaging issue.
```
iMac-TMP:homebrew-science joe$ find /usr/local/Cellar/opencv/2.4.13/lib|grep ts
/usr/local/Cellar/opencv/2.4.13/lib/libopencv_ts.a
```

**Comment by ilovezfs** [comment] 2016-06-04 04:51
Closed via https://github.com/Homebrew/homebrew-science/commit/f83083037d30acd297ed37d1b028a9fd1af4907f

**Closed by ilovezfs** 2016-06-04 04:51 UTC

**Comment by engincandy** [comment] 2016-11-14 18:41
I have the same problem:

> ld: library not found for -lopencv_ts

How can I solve this? I am using Xcode 8.1 and the latest version of OpenCV...

**Comment by wateryoma** [comment] 2016-11-23 22:35
Same problem here
```sh
ld: library not found for -lopencv_ts
collect2: error: ld returned 1 exit status
make: *** [build] Error 1
```
opencv3 was installed with homebrew
```sh
brew install opencv3 --HEAD --with-python3 --with-examples --with-contrib --with-static
```

**Comment by StudentESE** [comment] 2017-10-10 10:27
Hi @ilovezfs,

the problem is still existing ?

I installed OpenCV like this:
`brew install opencv`

and got still the error:
> ld: library not found for -lopencv_ts
clang: error: linker command failed with exit code 1 (use -v to see invocation)

For me it helped to remove `-lopencv_ts` from the **Other Linker Flags** you can find in **Build Settings** searching for `linking`
