### ISSUE TITLE
brew install lammps error

### ISSUE THREAD

**Issue by aadrych** [Homebrew/homebrew-science#5269] opened 2017-03-14 11:15 UTC
Hi, 

I have just tried to get the latest version of lammps on my mac trhough homebrew but it has now crashed my lammps install. 

I got an error during the lammps install which was 
In file included from ../fix_mscg.cpp:21:
../fix_mscg.h:24:10: fatal error: 'mscg.h' file not found
#include "mscg.h"
         ^
1 error generated.
make[1]: *** [fix_mscg.o] Error 1
make: *** [mac] Error 2
Which I saw also appeared in the latest edit 
lammps (homebrew/science/lammps) on macOS 10.12.3 - Homebrew build logs
Now when I try and run lammps I get the error
[Alexs-MacBook-Pro.local:68589] [[44714,0],0] ORTE_ERROR_LOG: Bad parameter in file orted/pmix/pmix_server.c at line 262
[Alexs-MacBook-Pro.local:68589] [[44714,0],0] ORTE_ERROR_LOG: Bad parameter in file ess_hnp_module.c at line 666
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  pmix server init failed
  --> Returned value Bad parameter (-5) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
[Alexs-MacBook-Pro.local:68587] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 575
[Alexs-MacBook-Pro.local:68587] [[INVALID],INVALID] ORTE_ERROR_LOG: Unable to start a daemon on the local node in file ess_singleton_module.c at line 165
--------------------------------------------------------------------------
It looks like orte_init failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during orte_init; some of which are due to configuration or
environment problems.  This failure appears to be an internal failure;
here's some additional information (which may only be relevant to an
Open MPI developer):

  orte_ess_init failed
  --> Returned value Unable to start a daemon on the local node (-127) instead of ORTE_SUCCESS
--------------------------------------------------------------------------
--------------------------------------------------------------------------
It looks like MPI_INIT failed for some reason; your parallel process is
likely to abort.  There are many reasons that a parallel process can
fail during MPI_INIT; some of which are due to configuration or environment
problems.  This failure appears to be an internal failure; here's some
additional information (which may only be relevant to an Open MPI
developer):

  ompi_mpi_init: ompi_rte_init failed
  --> Returned "Unable to start a daemon on the local node" (-127) instead of "Success" (0)
--------------------------------------------------------------------------
*** An error occurred in MPI_Init
*** on a NULL communicator
*** MPI_ERRORS_ARE_FATAL (processes in this communicator will now abort,
***    and potentially your MPI job)
Even though I was trying to install the serial version?
How can I get back to and install a working version of lammps through home brew?

**Comment by aadrych** [comment] 2017-03-14 15:06
I just saw the same error in a previous post (Lammps openmpi error #5155) but even with the suggested uninstalling lammps and openmpi and reinstalling I get the same error.
I also found that the option of building lammps with mpi support no longer exists. I get the error
homebrew/science/lammps: this formula has no --with-mpi option so it will be ignored! which is not the same as the lammps download page.
I can get it to work temporarily using the export TMPDIR=/tmp command but fails if I try to use again in another directory.
Could anyone suggest a way for me to fix this please?
I only have el-captain at the moment so I'm not sure if there has been a cross over between the os sierra lammps tap and the el captain and so it's now getting confused?

**Comment by iMichka** [comment] 2017-03-14 16:32
Thanks. We have had multiple reports of this being broken.
For the `--with-mpi` option, this is normal, as it is always build against `mpi`. These is a `--without-mpi` option though, which allows to remove `mpi`.

It is still not clear why this breaks so often. Reporting the bug upstream may help. It is not clear for the moment if we are doing something wrong with packaging or if this is a real bug, which only upstream could fix.

**Comment by aadrych** [comment] 2017-03-14 17:40
Could it be something to do with os Sierra features being included with the el capitain bottle?
Is there a way for me to reload a previous version of lammps instead ?

Thanks in advance



Sent from my Samsung Galaxy smartphone.


-------- Original message --------

**Comment by iMichka** [comment] 2017-03-14 22:13
> Could it be something to do with os Sierra features being included with the el capitain bottle?

Not sure what you mean. Each bottle is built on it's own OS X version, so a mixup is unlikely. And if rebuilding from source did not help you, the problem is more general than the bottles being broken.

**Comment by iMichka** [comment] 2017-03-14 22:22
Also, it would be good to fill out the issue template. This information could be important for us. Please note that I just tested lammps on Sierra and the tests given in the caveats section seem to run on my machine.

**Comment by aadrych** [comment] 2017-03-17 10:15
________________________________
I haven't updated to mac os sierra yet, but I did get it to work temporarily by restarting my computer, although I am now back to an error as shown in the previous message.

I will look into installing mac os sierra and see if this will work too.

--------------------

**Comment by jcminerlanl** [comment] 2017-03-22 22:37
Has there been any progress on this front?
My own operating system is El Capitan 10.11.6 and I am seeing these same errors.
Have people given the upstream report to Homebrew or LAMMPS?

**Comment by akohlmey** [comment] 2017-03-23 02:18
guys, the `mscg.h` error has **nothing** to do with MPI. when you install the MSCG package, you need the corresponding library and configure its location in lib/mscg/Makefile.lammps. This is all documented in the Manual and corresponding README files and not different from, e.g., the VORONOI package that depends on libvoro++ or the USER-SMD package depending on the Eigen template library.

**Comment by akohlmey** [comment] 2017-03-23 02:26
i would suspect that the MPI related errors originate from having an updated MPI library installed, but an outdated LAMMPS executable (since the compilation failed) that was compiled against an older version of the same MPI library and because of that fails to load properly.

**Comment by aadrych** [comment] 2017-03-23 08:37
After a restart of my computer I'm not getting any errors.
I can't imagine this has actually fixed anything but I am going to try updating to os sierra and reinstall lammps.
________________________________

**Comment by iMichka** [comment] 2017-04-25 19:39
I opened a PR for the new version. I added a workaround for the missing mscg.h file, by not building that plugin/extension. See #5500

**Comment by iMichka** [comment] 2017-04-30 13:47
New version has just been merged. Closing here. Please open a new issue if you still encounter trouble installing lammps (and provide updated changelogs). Thanks

**Closed by iMichka** 2017-04-30 13:47 UTC
