### ISSUE TITLE
Maxima is broken, probably after SBCL update

### ISSUE THREAD

**Issue by alexeymuranov** [Homebrew/homebrew-science#2017] opened 2015-03-26 16:25 UTC
After i had brew SBCL updated, Maxima does not start anymore, i get
~~~
$ maxima<CR>
fatal error encountered in SBCL pid 1639(tid 140735091749648):
can't load .core for different runtime, sorry


Welcome to LDB, a low-level debugger for the Lisp runtime environment.
ldb>
~~~

`brew reinstall maxima` did not help.

**Comment by dpo** [comment] 2015-03-26 16:51
Duplicate of #1791.

**Closed** 2015-03-27 00:41 UTC

**Comment by kinsho6i7h** [comment] 2017-01-06 13:00
As per OP, I have just experienced the exact same issue with maxima 5.39 and SBCL 1.3.13

I had recently recompiled SBCL but not used maxima until today. 

Recompiling maxima against the new SBCL has fixed the issue but why did it break and will this become prerequisite if I choose to update again?
