### ISSUE TITLE
nfft: Installing bottle although brew install -cc=... would require an build from source

### ISSUE THREAD

**Issue by cmarquardt** [Homebrew/homebrew-science#1891] opened 2015-02-27 21:50 UTC
Hello,

this is probably more a question than an issue...

A while ago, the nfft formula was updated to optionally build a multithreaded version (#1767). This requires gcc, as clang doesn't support OpenMP. With

    brew install --cc=gcc-4.9 nfft

a multithreaded version of the library should be built along with the serial one; without the `--cc` option, i.e. if clang is the compiler, only the serial version of the compiler should be built.

I've had to redo my nfft installation and found that instead of building from source, an automatically build bottle is downloaded and installed. In principle, that's great - but there only is a bottle containing the serial version. When running `brew install`with the `--gcc=...` option, the same serial bottle is installed. The same is true for a `brew reinstall`, of course. In order to get the non-default argument `-cc=...` honoured, I have to issue an

    brew install --gcc=gcc-4.9 --build-from-source nfft

which works as expected.

My questions:

1. Is that behaviour (installing a bottle built with default settings even if non-default arguments are given to `brew (re)install`) intended? Shouldn't different bottles be selected based on the arguments given to `brew install`? Or a build from the sources be triggered as soon as non-standard arguments are given to `brew install`?
2. Alternatively, is there a way to force a build from source from within the formula if non-standard arguments are given to `brew (re)install`?

Thanks a lot,

   Christian.

**Comment by dpo** [comment] 2015-02-28 17:29
I thought a source build should be triggered if you supply non-default arguments, but @jacknagel will be able to confirm.

**Comment by jacknagel** [comment] 2015-02-28 17:33
We can't make "global" options like `--cc` trigger a source build because it would force installing all dependencies from source as well. Only `--interactive` or formula-specific options automatically trigger a source build.

**Comment by cmarquardt** [comment] 2015-03-01 10:06
Ok - it would be better then in the nfft formula to have a non-standard argument (say --multithreaded) which requires the gcc compiler?

How would one make sure in the formula that the gcc-x.y compiler (with a potentially unknown version x.y) is used for compilation, overwriting the default `clang`? I mean, is there a way to do the equivalent of --cc=gcc-x.y inside the formula?

Or alternatively, can one somehow trigger a build from source from within the formula?

Many thanks,

   Christian.

**Comment by iml** [comment] 2015-03-08 04:15
`needs :openmp if build.with? "multithreaded"` would work but it's not how that function was intended, and introduces further unwanted conditionals in the class body. We could consider introducing `:openmp` as a dependency in core, which would provide the `:optional/:recommended` DSL. In lieu of that, however, I would rather commit to `needs :openmp` or warning the user when building with clang.

**Comment by cmarquardt** [comment] 2015-03-08 09:15
I'm not sure if I completely understand what you are saying (sorry - absolutely my fault...) - right now, the user gets a warning if building with `clang`. I think there is support for `needs :openmp` already; all it does is failing with a warning if clang is used for compiling the formula. However, in case of `nfft`, the multithreaded build is just an option (which unfortunately requires the non-default compiler); the serial version alone builds fine with `clang`. We once had a version which required two arguments (`--with-openmp`and `-cc=...`, I believe). But we reduced it to the compiler one to make it simpler for users.

Another idea would be to have two formulae (`nfft` and `nfft_mt` or something) which exclude each other.

**Comment by dpo** [comment] 2015-03-08 16:41
You could do something like [this](https://github.com/Homebrew/homebrew-science/blob/master/cppad.rb#L43).

**Comment by cmarquardt** [comment] 2015-03-08 21:08
Oh yes; that is what's happening right now. OpenMP / multithreading is enabled as soon as clang isn't  used as a compiler, and a user would use the `--cc` option to make that happen.

The problem is that there is a bottle build with `clang`, and `--cc` isn't sufficient to trigger a build from source if a user wants a `gcc` build. I understand a formula specific option (say `--multithreaded`) would solve the bottle problem, but I don't know how to overwrite the choice of compiler from within the formula (and throw an error if an OpenMP capable compiler can't be found). Can that be done somehow?

**Comment by dpo** [comment] 2015-03-08 21:16
Oh sorry, I got confused. I agree with @iml that a construct like `depends_on :openmp => :recommended` would be ideal. We could use it in several other formulas as well.

@jacknagel Is something like that doable?

More immediately, we could just add `needs :openmp` in `nfft`, which would introduce a dependence on `gcc`.

**Comment by dpo** [comment] 2016-10-14 19:53
Closing as this is now obsolete.

**Closed by dpo** 2016-10-14 19:53 UTC
Labels: Math

**Comment by cmarquardt** [comment] 2016-10-15 21:08
Thanks.
