### ISSUE TITLE
blasr install failed

### ISSUE THREAD

**Issue by DINGYICHEN** [Homebrew/homebrew-science#2596] opened 2015-08-01 08:07 UTC
$ brew install blasr
==> Installing blasr from homebrew/homebrew-science
==> Downloading https://github.com/PacificBiosciences/blasr/archive/smrtanalysis
Already downloaded: /Library/Caches/Homebrew/blasr-2.2.tar.gz
==> make STATIC= HDF5INCLUDEDIR=/usr/local/opt/hdf5/include HDF5LIBDIR=/usr/loca
collect2: error: ld returned 1 exit status
make[1]: **\* [bin/filterBySubreadAgreement] Error 1
make[1]: **\* Waiting for unfinished jobs....
make: **\* [sequtils-build] Error 2
make: **\* [alignment-build] Error 2

**Comment by dunn** [comment] 2015-08-01 14:04
Could you post `brew gist-logs blasr`, please?

**Comment by DINGYICHEN** [comment] 2015-08-02 03:26
https://gist.github.com/6fae1cb2e5c4166c5713

**Comment by tdsmith** [comment] 2015-08-02 19:13
The error is:
```
Undefined symbols for architecture x86_64:
  "H5::H5Location::iterateAttrs(void (*)(H5::H5Location&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >, void*), unsigned int*, void*)", referenced from:
      HDFAttributable::ContainsAttribute(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) in StoreQualityByContext.o
  "H5::Attribute::read(H5::DataType const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) const", referenced from:
      HDFAtom<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Read(std::basic_string<char, std::char_traits<char>, std::allocator<char> >&) in StoreQualityByContext.o
  "H5::Attribute::write(H5::DataType const&, std::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const", referenced from:
      HDFAtom<std::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Write(std::basic_string<char, std::char_traits<char>, std::allocator<char> >) in StoreQualityByContext.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```

The root problem is that blasr doesn't build with clang, pending resolution of PacificBiosciences/blasr#28, and the hdf5 C++ libraries were built against clang's default stdlib and not g++'s.

I think the solution is to do `brew reinstall hdf5 --cc=gcc-5`.

**Comment by tdsmith** [comment] 2015-08-02 19:15
If I'm right, this is broken by default and we should add a caveat to blasr or even vendor hdf5.

**Comment by iml** [comment] 2015-08-02 22:05
I think we should move towards vendoring dependencies here and more broadly on some GCC-only builds, since most developers are not interested in maintaining support for Mac/Clang. Seems like to only way to resolve #1593.

**Comment by deannachurch** [comment] 2015-09-11 05:55
This is still failing on 10.10.5
````
brew install blasr
==> Installing blasr from homebrew/homebrew-science
==> Downloading https://github.com/PacificBiosciences/blasr/archive/smrtanalysis-2.2.tar.gz
==> Downloading from https://codeload.github.com/PacificBiosciences/blasr/tar.gz/smrtanalys
######################################################################## 100.0%
==> make STATIC= HDF5INCLUDEDIR=/usr/local/opt/hdf5/include HDF5LIBDIR=/usr/local/opt/hdf5/
collect2: error: ld returned 1 exit status
make[1]: *** [bin/blasr] Error 1
make[1]: *** Waiting for unfinished jobs....
make: *** [pbihdfutils-build] Error 2
make: *** [alignment-build] Error 2

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/homebrew/homebrew-science/issues
````

[10Sep 22:51:42 l-mp-dchurch1 ~]$ brew gist-logs blasr
https://gist.github.com/488f1a1c41ce46c3e1a5

**Comment by pb-cdunn** [comment] 2015-10-14 15:17
The problem is a mis-match in G++ ABI versions:
* https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

Or see bottom of PacificBiosciences/blasr/issues/125.

Also, blasr will now build with clang, which is another solution.

**Comment by jbadomics** [comment] 2015-12-29 22:27
The following worked for me with homebrew and a recent fresh install of OS X 10.11.2 El Capitan:

```
brew uninstall --force hdf5 gcc boost blasr
brew install gcc —without multilib  ## v. 5.3.0, be patient as this takes a long time to compile.
brew install boost --build-from-source --HEAD
brew install hdf5 --cc=gcc-5
brew install blasr --cc=gcc-5

$ brew install blasr --cc=gcc-5
==> Installing blasr from homebrew/science
==> Downloading https://github.com/PacificBiosciences/blasr/archive/smrtanalysis-2.2.tar.gz
Already downloaded: /Library/Caches/Homebrew/blasr-2.2.tar.gz
==> make STATIC= HDF5INCLUDEDIR=/usr/local/opt/hdf5/include HDF5LIBDIR=/usr/local/opt/hdf5/lib
==> make install PREFIX=/usr/local/Cellar/blasr/2.2
🍺  /usr/local/Cellar/blasr/2.2: 29 files, 6.2M, built in 1 minute 20 seconds
```

**Comment by iMichka** [comment] 2017-04-17 18:01
Blasr is sort of dead, see #4254. Maybe we should remove it completely but for the moment the formula can stay as-is until somebody wants to work on this. Closing here.

**Closed by iMichka** 2017-04-17 18:01 UTC
Labels: build-error
