### ISSUE TITLE
"brew install r --with-cairo" is fubar  (Linuxbrew)

### ISSUE THREAD

**Issue by jwhite007** [Homebrew/homebrew-science#4461] opened 2016-10-14 15:03 UTC
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

#### Brief summary of issue:
```brew install r --with-cairo``` simply does not work. One thing is that I've already installed cairo; but the R rb believes that it must reinstall cairo every time I install, upgrade, or reinstall R. Brew will proceed to install cairo, even though it's already installed and then finish without installing R.

```brew install r``` works just fine.

#### The complete command that you issued:
```
brew install cairo
brew install r --with-cairo
```
https://gist.github.com/jwhite007/0868746c0d6a30c3b401f78aef551fd3
#### Gist with output of `brew doctor`:
```
sbcuser$ brew dr
Your system is ready to brew.
```

#### Link output by `brew gist-logs <formula>`:
N/A

#### Output of `brew config`:
https://gist.github.com/jwhite007/d3b92fc36b9851fec0f2ef5e5518cee7

### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment] 2016-10-14 16:03
Duplicate of #4388. Please add additional information to that issue. Sorry it's taking a while to get back to you.

**Closed by dpo** 2016-10-14 16:03 UTC
