### ISSUE TITLE
installing opencv 2.4.11 works but refers to non existent library

### ISSUE THREAD

**Issue by jiho** [Homebrew/homebrew-science#2209] opened 2015-05-06 00:47 UTC
```
$ which python
/usr/local/bin/python

$ echo $PYTHONPATH
/usr/local/lib/python2.7/site-packages:

$ python
Python 2.7.9 (default, May  1 2015, 19:04:44) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: /usr/local/lib/libImath-2_1.11.dylib
  Referenced from: /usr/local/Cellar/opencv/2.4.11/lib/libopencv_highgui.2.4.dylib
  Reason: image not found
>>> 

$ ls /usr/local/lib/libImath*
/usr/local/lib/libImath-2_2.12.dylib /usr/local/lib/libImath.dylib
/usr/local/lib/libImath.a
```

This used to work with opencv 2.4.9. `libIMath` is in `ilmbase` which is at version 2.2.0.

A quick fix is:

```
$ brew switch ilmbase 2.1.0
Cleaning /usr/local/Cellar/ilmbase/2.1.0
Cleaning /usr/local/Cellar/ilmbase/2.2.0
73 links created for /usr/local/Cellar/ilmbase/2.1.0

$ python
Python 2.7.9 (default, May  1 2015, 19:04:44) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.49)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv2
```

**Comment by iml** [comment] 2015-05-06 01:44
https://github.com/Homebrew/homebrew/pull/39422 is also upcoming.

**Comment by myfavouritekk** [comment] 2015-05-06 05:39
Right, I just switched `ilmbase` to 2.1.0. I am not sure but I think rebuilding opencv from source rather than using bottle binary could also work.

**Comment by iml** [comment] 2015-05-06 05:57
Yes, rebuilding from source should fix it. The bottle is linked against the older libraries, so it needs to be revisioned once `openexr` has been updated.

**Comment by jiho** [comment] 2015-05-06 08:55
I tried building the devel version which also failed (there is a an issue about that already). How do I force building 2.4.11 from source rather than using the bottled version?

**Comment by dunn** [comment] 2015-05-06 14:57
`brew install -fs opencv`

**Comment by jiho** [comment] 2015-05-06 16:23
thank ;)

**Comment by iml** [comment] 2015-05-07 04:25
Fixed in 267a4fb.

**Closed by iml** 2015-05-07 04:25 UTC

**Comment by super-cache-money** [comment] 2015-05-17 08:51
Probably noob question - but if this is fixed, shouldn't `brew update`, then `brew upgrade opencv` work?

**Comment by mgoldsborough** [comment] 2015-06-01 13:02
Could someone elaborate on what the solution is for this?  It says the issue is closed but I'm having the same issues trying to install opencv on a Mac OSX 10.10.2.  Thanks!

```
Python 2.7.10 (default, May 26 2015, 13:01:57) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import cv
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/cv.py", line 1, in <module>
    from cv2.cv import *
ImportError: dlopen(/usr/local/lib/python2.7/site-packages/cv2.so, 2): Library not loaded: /usr/local/lib/libImath-2_1.11.dylib
  Referenced from: /usr/local/Cellar/opencv/2.4.10.1/lib/libopencv_highgui.2.4.dylib
  Reason: image not found
>>> 
```

**Comment by tdsmith** [comment] 2015-06-01 21:10
@mgoldsborough The fix was for us to rebuild our bottles. Have you run `brew update` recently?

**Comment by mgoldsborough** [comment] 2015-06-01 21:32
Thanks for the heads up.  I just ran ```brew update``` and had a bunch of git errors.  Not sure what happened on my end but an uninstall/reinstall of homebrew and homebrew/science seems to fix the issue.  Appreciate the quick response!
