### ISSUE TITLE
brew tap homebrew/science error with invalid attribute version (nil) in sortmerna

### ISSUE THREAD

**Issue by ccshao** [Homebrew/homebrew-science#4353] opened 2016-09-27 09:22 UTC
### Indicate troubleshooting steps taken

- [x] Ran `brew update` and retried your prior step?
- [x] Ran `brew doctor`, fixed as many issues as possible and retried your prior step?
- [x] Checked that a similar issue hasn't already been filed?
- [ ] Looked up the software bug tracker if reporting a build error?
- [ ] If you're seeing permission errors tried running `sudo chown -R $(whoami) $(brew --prefix)`?

### Bug reports / build errors:

```brew tap homebrew/science```
Error: Invalid formula: /home/XXX/.linuxbrew/Library/Taps/homebrew/homebrew-science/sortmerna.rb
invalid attribute for formula 'homebrew/science/sortmerna': version (nil)
Error: Cannot tap homebrew/science: invalid syntax in tap!

#### Brief summary of issue:
could not tap homebrew/science. Something wronig with sortmerna formular?

#### The complete command that you issued:
```brew tap homebrew/science```
#### Output of `brew config`:
HOMEBREW_VERSION: 0.9.9
ORIGIN: https://github.com/Linuxbrew/brew
HEAD: 28c79defe0ed12f524998a68f22c19ab058b288f
Last commit: 2 days ago
Core tap ORIGIN: https://github.com/Linuxbrew/homebrew-core
Core tap HEAD: 600e2df32333a66f21d60437446c68e4716a60c5
Core tap last commit: 3 days ago
HOMEBREW_PREFIX: /home/xxx/.linuxbrew
HOMEBREW_REPOSITORY: /home/xxx/.linuxbrew
HOMEBREW_CELLAR: /home/xxx/.linuxbrew/Cellar
HOMEBREW_BOTTLE_DOMAIN: https://linuxbrew.bintray.com
CPU: 16-core 64-bit haswell
Homebrew Ruby: 2.0.0-p648 => /home/xxx/.linuxbrew/Library/Homebrew/vendor/portable-ruby/2.0.0-p648/bin/ruby
Clang: N/A
Git: 1.9.1 => /usr/bin/git
Perl: /usr/bin/perl
Python: /usr/bin/python => /usr/bin/python2.7
Ruby: /usr/bin/ruby => /usr/bin/ruby1.9.1
Java: 1.7.0_111
Kernel: Linux 4.4.0-40-generic x86_64 GNU/Linux
OS: Ubuntu 14.04.5 LTS
Codename: trusty
OS glibc: 2.19
OS gcc: 4.8.4
Linuxbrew glibc: N/A
Linuxbrew gcc: N/A
Linuxbrew xorg: N/A
### Formula Requests:

**The quickest way to get a new formula into Homebrew is to file a [Pull Request](https://github.com/Homebrew/homebrew-science/pulls)**.

We will consider your request but it may be closed if it's something we're not actively planning to work on.

**Comment by dpo** [comment] 2016-09-27 14:25
I cannot reproduce this. Could you try `brew untap homebrew/science; brew tap --repair; brew tap homebrew/science`?

**Comment by jonchang** [comment] 2016-09-27 15:07
This is a known issue with Linuxbrew caused by incompatible changes in how we parse version numbers out of URLS, which changed after Homebrew 1.0. (Linuxbrew is still on homebrew 0.99.)

**Comment by ccshao** [comment] 2016-09-28 07:43
@jonchang  is there a temporary fix before the linuxbrew goes to 1.0?

**Comment by ccshao** [comment] 2016-09-28 07:45
@dpo `-- repair` does not work.

**Comment by shekhei** [comment] 2016-09-28 08:27
I am having the same problem under osx el capitan 10.11.6

**Comment by drejom** [comment] 2016-09-28 12:14
+1 for Ubuntu 14.04

**Comment by macmanes** [comment] 2016-09-29 15:53
I have same problem in Ubuntu 14.04

**Comment by tseemann** [comment] 2016-09-29 15:57
I'm on RHEL and get it too:
```
brew info sortmerna
Error: invalid attribute for formula 'homebrew/science/sortmerna': version (nil)
Please report this bug:
    https://github.com/Linuxbrew/brew/blob/master/share/doc/homebrew/Troubleshooting.md#troubleshooting
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:225:in `validate_attributes!'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formula.rb:183:in `initialize'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formulary.rb:81:in `new'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formulary.rb:81:in `get_formula'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formulary.rb:219:in `factory'
/home/linuxbrew/.linuxbrew/Library/Homebrew/formulary.rb:378:in `find_with_priority'
/home/linuxbrew/.linuxbrew/Library/Homebrew/cmd/info.rb:53:in `block in print_info'
/home/linuxbrew/.linuxbrew/Library/Homebrew/cmd/info.rb:47:in `each'
/home/linuxbrew/.linuxbrew/Library/Homebrew/cmd/info.rb:47:in `each_with_index'
/home/linuxbrew/.linuxbrew/Library/Homebrew/cmd/info.rb:47:in `print_info'
/home/linuxbrew/.linuxbrew/Library/Homebrew/cmd/info.rb:36:in `info'
/home/linuxbrew/.linuxbrew/Library/Homebrew/brew.rb:96:in `<main>'
```

**Comment by sjackman** [comment] 2016-09-29 16:02
Fixed with a workaround. Merging `Homebrew/brew` into `Linuxbrew/brew` should hopefully fix this issue properly.

**Closed** 2016-09-29 16:02 UTC
Labels: bug, Linux

**Comment by tseemann** [comment] 2016-09-30 08:19
Thanks for patching that @sjackman
